IBM_ILOG_JViews_Enterprise_Deployment = "String  \"JViews-Enterprise\""
IBM_ILOG_JViews_Charts_Deployment = "String  \"JViews-Charts\""
IBM_ILOG_JViews_Diagrammer_Deployment = "String  \"JViews-Diagrammer\""
IBM_ILOG_JViews_Gantt_Deployment = "String  \"JViews-Gantt\""
IBM_ILOG_JViews_Maps_Deployment = "String  \"JViews-Maps\""
IBM_ILOG_JViews_Maps_for_Defense_Deployment = "String  \"JViews-Maps-Defense\""
IBM_ILOG_JViews_TGO_Deployment = "String  \"JTGO\""
IBM_ILOG_JViews_Graph_Layout_for_Eclipse_Deployment = "String  \"JViews-GL-Eclipse\""
