DT_NOT_DERIVED = "int  0"
DT_RESTRICTION = "int  1"
DT_EXTENSION = "int  2"
BTC_NOT_BUILTIN = "int  0"
BTC_ANY_TYPE = "int  1"
BTC_FIRST_PRIMITIVE = "int  2"
BTC_ANY_SIMPLE = "int  2"
BTC_BOOLEAN = "int  3"
BTC_BASE_64_BINARY = "int  4"
BTC_HEX_BINARY = "int  5"
BTC_ANY_URI = "int  6"
BTC_QNAME = "int  7"
BTC_NOTATION = "int  8"
BTC_FLOAT = "int  9"
BTC_DOUBLE = "int  10"
BTC_DECIMAL = "int  11"
BTC_STRING = "int  12"
BTC_DURATION = "int  13"
BTC_DATE_TIME = "int  14"
BTC_TIME = "int  15"
BTC_DATE = "int  16"
BTC_G_YEAR_MONTH = "int  17"
BTC_G_YEAR = "int  18"
BTC_G_MONTH_DAY = "int  19"
BTC_G_DAY = "int  20"
BTC_G_MONTH = "int  21"
BTC_LAST_PRIMITIVE = "int  21"
BTC_INTEGER = "int  22"
BTC_LONG = "int  23"
BTC_INT = "int  24"
BTC_SHORT = "int  25"
BTC_BYTE = "int  26"
BTC_NON_POSITIVE_INTEGER = "int  27"
BTC_NEGATIVE_INTEGER = "int  28"
BTC_NON_NEGATIVE_INTEGER = "int  29"
BTC_POSITIVE_INTEGER = "int  30"
BTC_UNSIGNED_LONG = "int  31"
BTC_UNSIGNED_INT = "int  32"
BTC_UNSIGNED_SHORT = "int  33"
BTC_UNSIGNED_BYTE = "int  34"
BTC_NORMALIZED_STRING = "int  35"
BTC_TOKEN = "int  36"
BTC_NAME = "int  37"
BTC_NCNAME = "int  38"
BTC_LANGUAGE = "int  39"
BTC_ID = "int  40"
BTC_IDREF = "int  41"
BTC_IDREFS = "int  42"
BTC_ENTITY = "int  43"
BTC_ENTITIES = "int  44"
BTC_NMTOKEN = "int  45"
BTC_NMTOKENS = "int  46"
BTC_LAST_BUILTIN = "int  46"
NOT_COMPLEX_TYPE = "int  0"
EMPTY_CONTENT = "int  1"
SIMPLE_CONTENT = "int  2"
ELEMENT_CONTENT = "int  3"
MIXED_CONTENT = "int  4"
FACET_LENGTH = "int  0"
FACET_MIN_LENGTH = "int  1"
FACET_MAX_LENGTH = "int  2"
FACET_MIN_EXCLUSIVE = "int  3"
FACET_MIN_INCLUSIVE = "int  4"
FACET_MAX_INCLUSIVE = "int  5"
FACET_MAX_EXCLUSIVE = "int  6"
FACET_TOTAL_DIGITS = "int  7"
FACET_FRACTION_DIGITS = "int  8"
LAST_BASIC_FACET = "int  8"
FACET_WHITE_SPACE = "int  9"
FACET_PATTERN = "int  10"
FACET_ENUMERATION = "int  11"
LAST_FACET = "int  11"
PROPERTY_ORDERED = "int  12"
PROPERTY_BOUNDED = "int  13"
PROPERTY_CARDINALITY = "int  14"
PROPERTY_NUMERIC = "int  15"
LAST_PROPERTY = "int  15"
UNORDERED = "int  0"
PARTIAL_ORDER = "int  1"
TOTAL_ORDER = "int  2"
NOT_SIMPLE = "int  0"
ATOMIC = "int  1"
UNION = "int  2"
LIST = "int  3"
NOT_DECIMAL = "int  0"
SIZE_BYTE = "int  8"
SIZE_SHORT = "int  16"
SIZE_INT = "int  32"
SIZE_LONG = "int  64"
SIZE_BIG_INTEGER = "int  1000000"
SIZE_BIG_DECIMAL = "int  1000001"
WS_UNSPECIFIED = "int  0"
WS_PRESERVE = "int  1"
WS_REPLACE = "int  2"
WS_COLLAPSE = "int  3"
def Ref():
'''public Ref(final SchemaType type)
public Ref(final SchemaTypeSystem system, final String handle)
'''
pass
def getComponentType():
'''public final int getComponentType()
'''
pass
def get():
'''public final SchemaType get()
'''
pass
