ELEMENT_NODE = "short  1"
TEXT_NODE = "short  4"
CDATA_SECTION_NODE = "short  12"
COMMENT_NODE = "short  5"
DTD_NODE = "short  11"
PI_NODE = "short  3"
ENTITY_REFERENCE_NODE = "short  9"
SPACE_NODE = "short  6"
