COPYRIGHT_NOTICE = "String  \"Copyright IBM Corporation 2005,2012\""
MODEL_NAME_PROPERTIES_TAG = "String  \"name\""
MODEL_ALGORITHM_PROPERTIES_TAG = "String  \"algorithm\""
MODEL_ALGORITHM_TYPE_ATTR = "String  \"solveanywayType\""
MODEL_TYPE_ATTR = "String  \"modelType\""
MONITORING_SUPPORT_ATTR = "String  \"monitoringSupport\""
