ADMIN_ROLE = "String  \"administrator\""
CONFIG_ROLE = "String  \"configurator\""
OPERATOR_ROLE = "String  \"operator\""
MONITOR_ROLE = "String  \"monitor\""
DEPLOYER_ROLE = "String  \"deployer\""
ADMINSECURITY_ROLE = "String  \"adminsecuritymanager\""
AUDITOR_ROLE = "String  \"auditor\""
