SELECTED_ACTIVITIES_EVENT = "String  selected_activities_event""
TOGGLE_RESOURCE_FILTER_EVENT = "String  toggle_resource_filter_event""
CHANGE_RESOURCE_BUTTON_STATE_EVENT = "String  change_resource_button_state""
PROJECT_LOADED = "String  project_loaded""
MODEL_ADJUSTING = "String  model_adjusting""
