def newMessage():
    '''    public Message newMessage(final CharSequence message)
    public Message newMessage(final Object message)
    public Message newMessage(final String message)
    public Message newMessage(final String message, final Object p0)
    public Message newMessage(final String message, final Object p0, final Object p1)
    public Message newMessage(final String message, final Object p0, final Object p1, final Object p2)
    public Message newMessage(final String message, final Object p0, final Object p1, final Object p2, final Object p3)
    public Message newMessage(final String message, final Object p0, final Object p1, final Object p2, final Object p3, final Object p4)
    public Message newMessage(final String message, final Object p0, final Object p1, final Object p2, final Object p3, final Object p4, final Object p5)
    public Message newMessage(final String message, final Object p0, final Object p1, final Object p2, final Object p3, final Object p4, final Object p5, final Object p6)
    public Message newMessage(final String message, final Object p0, final Object p1, final Object p2, final Object p3, final Object p4, final Object p5, final Object p6, final Object p7)
    public Message newMessage(final String message, final Object p0, final Object p1, final Object p2, final Object p3, final Object p4, final Object p5, final Object p6, final Object p7, final Object p8)
    public Message newMessage(final String message, final Object p0, final Object p1, final Object p2, final Object p3, final Object p4, final Object p5, final Object p6, final Object p7, final Object p8, final Object p9)
    '''
