NOLIMIT = "byte  0"
LT = "byte  1"
MT = "byte  2"
names = "String[]  { \"M\", \"F\", \"N\" }"
NODIRECTION = "byte  0"
PAST = "byte  1"
FUTURE = "byte  2"
PLURALIZED = "byte  0"
MEDIUM = "byte  1"
SHORT = "byte  1"
INTEGER = "byte  0"
INTEGER_CUSTOM = "byte  1"
HALF_FRACTION = "byte  2"
DECIMAL1 = "byte  3"
DECIMAL2 = "byte  4"
DECIMAL3 = "byte  5"
NONE = "byte  0"
PLURAL = "byte  1"
DUAL = "byte  2"
PAUCAL = "byte  3"
HEBREW = "byte  4"
ARABIC = "byte  5"
PREFIX = "byte  0"
AFTER_FIRST = "byte  1"
LAST = "byte  2"
DEFAULT = "byte  0"
CHINESE_TRADITIONAL = "byte  1"
CHINESE_SIMPLIFIED = "byte  2"
KOREAN = "byte  3"
ZPLURAL = "byte  0"
ZSINGULAR = "byte  1"
DPLURAL = "byte  0"
DSINGULAR = "byte  1"
DSINGULAR_SUBONE = "byte  2"
DPAUCAL = "byte  3"
FPLURAL = "byte  0"
FSINGULAR_PLURAL = "byte  1"
FSINGULAR_PLURAL_ANDAHALF = "byte  2"
FPAUCAL = "byte  3"
YES = "byte  0"
NO = "byte  1"
ONE_PLUS = "byte  2"
WITH_SECONDS = "byte  2"
FULL = "byte  2"
M = "byte  0"
F = "byte  1"
N = "byte  2"
def read():
    '''public static DataRecord read(final String ln, final RecordReader in)
    public static ScopeData read(final RecordReader in)
    '''
def write():
    '''public void write(final RecordWriter out)
    public void write(final RecordWriter out)
    '''
