def ():
    '''returns Header\n\n
    ()\n
    (final String name, final String value)\n
    (final String name, final String value, final boolean isAutogenerated)\n
    '''
def toExternalForm():
    '''returns String\n\n
    toExternalForm()\n
    '''
def toString():
    '''returns String\n\n
    toString()\n
    '''
def getValues():
    '''returns HeaderElement[]\n\n
    getValues()\n
    '''
def getElements():
    '''returns HeaderElement[]\n\n
    getElements()\n
    '''
def isAutogenerated():
    '''returns boolean\n\n
    isAutogenerated()\n
    '''
