def Header():
    '''    public Header()
    public Header(final String name, final String value)
    public Header(final String name, final String value, final boolean isAutogenerated)
    '''
def toExternalForm():
    '''    public String toExternalForm()
    '''
def toString():
    '''    public String toString()
    '''
def getValues():
    '''    public HeaderElement[] getValues()
    '''
def getElements():
    '''    public HeaderElement[] getElements()
    '''
def isAutogenerated():
    '''    public boolean isAutogenerated()
    '''
