def Header():
'''public Header()
public Header(final String name, final String value)
public Header(final String name, final String value, final boolean isAutogenerated)
'''
pass
def toExternalForm():
'''public String toExternalForm()
'''
pass
def toString():
'''public String toString()
'''
pass
def getValues():
'''public HeaderElement[] getValues()
'''
pass
def getElements():
'''public HeaderElement[] getElements()
'''
pass
def isAutogenerated():
'''public boolean isAutogenerated()
'''
pass
