IBM_COPYRIGHT = "String  \"\n\nLicensed Materials - Property of IBM\n5725-E24\n(C)Copyright IBM Corporation 2007, 2013.\nAll Rights Reserved.\nUS Government Users Restricted Rights - Use, duplication \nor disclosure restricted by GSA ADP Schedule Contract with IBM Corp.\n\n\""
DEBUG_LEVEL = "int  0"
INFO_LEVEL = "int  1"
WARN_LEVEL = "int  2"
ERROR_LEVEL = "int  3"
FATAL_LEVEL = "int  4"
