MAXIMO_INBOUND_ILYNN = "String  \"ILYNN\""
MAXIMO_OUTBOUND_ICYNN = "String  \"ICYNN\""
ERR_KEY_INVALID_ATTRIBUTES = "String  \"invalid.bidi.attributes\""
ERR_KEY_INVALID_IN_OUT_ATTRIBUTES = "String  \"invalid.bidi.attributes.pair\""
ERR_KEY_NULL_ATTRIBUTES = "String  \"null.attributes\""
ERR_KEY_NULL_XML_DOCUMENT = "String  \"null.xml\""
ERR_KEY_BAD_XML_DOCUMENT = "String  \"bad.xml\""
