VT_EMPTY = "int  0"
VT_NULL = "int  1"
VT_I2 = "int  2"
VT_I4 = "int  3"
VT_R4 = "int  4"
VT_R8 = "int  5"
VT_CY = "int  6"
VT_DATE = "int  7"
VT_BSTR = "int  8"
VT_DISPATCH = "int  9"
VT_ERROR = "int  10"
VT_BOOL = "int  11"
VT_VARIANT = "int  12"
VT_UNKNOWN = "int  13"
VT_DECIMAL = "int  14"
VT_I1 = "int  16"
VT_UI1 = "int  17"
VT_UI2 = "int  18"
VT_UI4 = "int  19"
VT_I8 = "int  20"
VT_UI8 = "int  21"
VT_INT = "int  22"
VT_UINT = "int  23"
VT_VOID = "int  24"
VT_HRESULT = "int  25"
VT_PTR = "int  26"
VT_SAFEARRAY = "int  27"
VT_CARRAY = "int  28"
VT_USERDEFINED = "int  29"
VT_LPSTR = "int  30"
VT_LPWSTR = "int  31"
VT_FILETIME = "int  64"
VT_BLOB = "int  65"
VT_STREAM = "int  66"
VT_STORAGE = "int  67"
VT_STREAMED_OBJECT = "int  68"
VT_STORED_OBJECT = "int  69"
VT_BLOB_OBJECT = "int  70"
VT_CF = "int  71"
VT_CLSID = "int  72"
VT_VERSIONED_STREAM = "int  73"
VT_VECTOR = "int  4096"
VT_ARRAY = "int  8192"
VT_BYREF = "int  16384"
VT_RESERVED = "int  32768"
VT_ILLEGAL = "int  65535"
VT_ILLEGALMASKED = "int  4095"
VT_TYPEMASK = "int  4095"
def getVariantName():
'''public static String getVariantName(final long variantType)
'''
pass
def getVariantLength():
'''public static int getVariantLength(final long variantType)
'''
pass
