CONNECT_TIMEOUT = "String  \"connectTimeout\""
READ_TIMEOUT = "String  \"readTimeout\""
FOLLOW_REDIRECTS = "String  \"followRedirects\""
GET = "String  \"GET\""
POST = "String  \"POST\""
PUT = "String  \"PUT\""
DELETE = "String  \"DELETE\""
