NodesConstantAliasBase = "String  \"N\""
TriplesTableBase = "String  \"T\""
QuadTableBase = "String  \"Q\""
CoalesceAliasBase = "String  \"M\""
NodesResultAliasBase = "String  \"R\""
VarBase = "String  \"V\""
VarCollasce = "String  \"VC\""
SelectBlock = "String  \"S\""
