def getFormatString():
    '''    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    public String getFormatString()
    public String getFormatString(final Locale locale)
    '''
def format():
    '''    public String format(final DateFormat dateFormat, final Calendar calendar)
    public String format(final DateFormat dateFormat, final Calendar calendar, final Locale locale)
    public String format(final DateFormat dateFormat, final Calendar calendar, final Locale locale)
    '''
def previousUnitTime():
    '''    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    public Calendar previousUnitTime(final Calendar calendar)
    '''
def incrementTime():
    '''    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    public Calendar incrementTime(final Calendar calendar)
    '''
def getMillis():
    '''    public double getMillis()
    public double getMillis()
    public double getMillis()
    public double getMillis()
    public double getMillis()
    public double getMillis()
    public double getMillis()
    public double getMillis()
    public double getMillis()
    public double getMillis()
    public double getMillis()
    '''
def toString():
    '''    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    '''
def get():
    '''    public T get(final Locale locale)
    '''
