def processRepositoryDataFactoryX():
    '''    public static void processRepositoryDataFactoryX(final CentralStoreKey centralStoreKey)
    '''
def getData():
    '''    public static Data getData()
    public static Data getData(final Hook hook)
    public static Data getData(final Hook hook, final Map<Object, Object> map)
    public static Data getData(final Connection connection)
    public static Data getData(final Connection connection, final Hook hook)
    public static Data getData(final Connection connection, final Hook hook, final Map<Object, Object> map)
    public static Data getData(final Connection connection, final Hook hook, final Properties properties)
    public static Data getData(final Connection connection, final Map<Object, Object> map)
    public static Data getData(final Connection connection, final Properties properties)
    public static Data getData(final DataSource dataSource)
    public static Data getData(final DataSource dataSource, final Hook hook)
    public static Data getData(final DataSource dataSource, final Hook hook, final Map<Object, Object> map)
    public static Data getData(final DataSource dataSource, final Hook hook, final Properties properties)
    public static Data getData(final DataSource dataSource, final Map<Object, Object> map)
    public static Data getData(final DataSource dataSource, final Properties properties)
    public static <T> T getData(final Class<T> clazz)
    public static <T> T getData(final Class<T> clazz, final Hook hook)
    public static <T> T getData(final Class<T> clazz, final Hook hook, final Map<Object, Object> map)
    public static <T> T getData(final Class<T> clazz, final Connection connection)
    public static <T> T getData(final Class<T> clazz, final Connection connection, final Hook hook)
    public static <T> T getData(final Class<T> clazz, final Connection connection, final Hook hook, final Map<Object, Object> map)
    public static <T> T getData(final Class<T> clazz, final Connection connection, final Hook hook, final Properties properties)
    public static <T> T getData(final Class<T> clazz, final Connection connection, final Map<Object, Object> map)
    public static <T> T getData(final Class<T> clazz, final Connection connection, final Properties properties)
    public static <T> T getData(final Class<T> clazz, final DataSource dataSource)
    public static <T> T getData(final Class<T> clazz, final DataSource dataSource, final Hook hook)
    public static <T> T getData(final Class<T> clazz, final DataSource dataSource, final Hook hook, final Map<Object, Object> map)
    public static <T> T getData(final Class<T> clazz, final DataSource dataSource, final Hook hook, final Properties properties)
    public static <T> T getData(final Class<T> clazz, final DataSource dataSource, final Map<Object, Object> map)
    public static <T> T getData(final Class<T> clazz, final DataSource dataSource, final Properties properties)
    public static <T> T getData(final Class<T> clazz, Data data)
    '''
