TYPE_BOOLEAN = "String  \"BOOLEAN\""
TYPE_BLOB = "String  \"BLOB\""
TYPE_DATETIME = "String  \"DATETIME\""
TYPE_ALN = "String  \"ALN\""
TYPE_INTEGER = "String  \"INTEGER\""
TYPE_BIGINT = "String  \"BIGINT\""
TYPE_DECIMAL = "String  \"DECIMAL\""
