def getSqlStatementKeyWithSQLCursorNameReplacedByReferencedQueryValueReadFromXML():
    '''returns SqlStatementKey\n\n
    getSqlStatementKeyWithSQLCursorNameReplacedByReferencedQueryValueReadFromXML()\n
    '''
def getSqlStatementKeyWithSQLCursorNameReplacedByReferencedQueryValue():
    '''returns SqlStatementKey\n\n
    getSqlStatementKeyWithSQLCursorNameReplacedByReferencedQueryValue(final String s)\n
    '''
def hashCode():
    '''returns int\n\n
    hashCode()\n
    '''
def equals():
    '''returns boolean\n\n
    equals(final Object o)\n
    '''
def toString():
    '''returns String\n\n
    toString()\n
    '''
def areAutoGenKeysRequested():
    '''returns boolean\n\n
    areAutoGenKeysRequested()\n
    '''
def isAutoGeneratedKeysJDBCMethodUsed():
    '''returns boolean\n\n
    isAutoGeneratedKeysJDBCMethodUsed()\n
    '''
def isMatchingSqlStr():
    '''returns boolean\n\n
    isMatchingSqlStr(final Set<SqlStatementKey> set)\n
    '''
def reportWhyStatementNotFound():
    '''returns String\n\n
    reportWhyStatementNotFound()\n
    '''
def getOrdinalPosition():
    '''returns int\n\n
    getOrdinalPosition()\n
    '''
def setOrdinalPosition():
    '''returns None\n\n
    setOrdinalPosition(final int ordinalPosition_)\n
    '''
def getStatementAttributesFormatted():
    '''returns String\n\n
    getStatementAttributesFormatted(final boolean b, final String s, final SqlStatementKey sqlStatementKey)\n
    '''
