type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(STInsetMode.class.getClassLoader(), \"schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2\").resolveHandle(\"stinsetmode3b89type\")"
AUTO = "Enum  Enum.forString(\"auto\")"
CUSTOM = "Enum  Enum.forString(\"custom\")"
INT_AUTO = "int  1"
INT_CUSTOM = "int  2"
