def unmarshall():
    '''    public String unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public BigDecimal unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public BigInteger unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Double unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Integer unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Boolean unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Float unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Long unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Byte unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Date unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public ByteBuffer unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Character unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    public Short unmarshall(final StaxUnmarshallerContext unmarshallerContext)
    '''
def getInstance():
    '''    public static StringStaxUnmarshaller getInstance()
    public static BigDecimalStaxUnmarshaller getInstance()
    public static BigIntegerStaxUnmarshaller getInstance()
    public static DoubleStaxUnmarshaller getInstance()
    public static IntegerStaxUnmarshaller getInstance()
    public static BooleanStaxUnmarshaller getInstance()
    public static FloatStaxUnmarshaller getInstance()
    public static LongStaxUnmarshaller getInstance()
    public static ByteStaxUnmarshaller getInstance()
    public static DateStaxUnmarshaller getInstance()
    public static ByteBufferStaxUnmarshaller getInstance()
    public static CharacterJsonUnmarshaller getInstance()
    public static ShortJsonUnmarshaller getInstance()
    '''
