APPLICATION_XML = "String  application/xml""
APPLICATION_JSON = "String  application/json""
APPLICATION_OCTET_STREAM = "String  application/octet-stream""
TEXT_PLAIN = "String  text/plain""
TEXT_XML = "String  text/xml""
TEXT_HTML = "String  text/html""
