ERROR_TAG_NOT_IN_POLICY = "String  \"error.tag.notfound\""
ERROR_TAG_DISALLOWED = "String  \"error.tag.removed\""
ERROR_TAG_FILTERED = "String  \"error.tag.filtered\""
ERROR_TAG_ENCODED = "String  \"error.tag.encoded\""
ERROR_TAG_EMPTY = "String  \"error.tag.empty\""
ERROR_CDATA_FOUND = "String  \"error.cdata.found\""
ERROR_PI_FOUND = "String  \"error.pi.found\""
ERROR_ATTRIBUTE_CAUSE_FILTER = "String  \"error.attribute.invalid.filtered\""
ERROR_ATTRIBUTE_CAUSE_ENCODE = "String  \"error.attribute.invalid.encoded\""
ERROR_ATTRIBUTE_INVALID_FILTERED = "String  \"error.attribute.invalid.filtered\""
ERROR_ATTRIBUTE_INVALID_REMOVED = "String  \"error.attribute.invalid.removed\""
ERROR_ATTRIBUTE_NOT_IN_POLICY = "String  \"error.attribute.notfound\""
ERROR_ATTRIBUTE_INVALID = "String  \"error.attribute.invalid\""
ERROR_COMMENT_REMOVED = "String  \"error.comment.removed\""
ERROR_INPUT_SIZE = "String  \"error.size.toolarge\""
ERROR_CSS_ATTRIBUTE_MALFORMED = "String  \"error.css.attribute.malformed\""
ERROR_CSS_TAG_MALFORMED = "String  \"error.css.tag.malformed\""
ERROR_STYLESHEET_NOT_ALLOWED = "String  \"error.css.disallowed\""
ERROR_CSS_IMPORT_DISABLED = "String  \"error.css.import.disabled\""
ERROR_CSS_IMPORT_EXCEEDED = "String  \"error.css.import.exceeded\""
ERROR_CSS_IMPORT_FAILURE = "String  \"error.css.import.failure\""
ERROR_CSS_IMPORT_INPUT_SIZE = "String  \"error.css.import.toolarge\""
ERROR_CSS_IMPORT_URL_INVALID = "String  \"error.css.import.url.invalid\""
ERROR_STYLESHEET_RELATIVE = "String  \"error.css.stylesheet.relative\""
ERROR_CSS_TAG_RELATIVE = "String  \"error.css.tag.relative\""
ERROR_STYLESHEET_RULE_NOTFOUND = "String  \"error.css.stylesheet.rule.notfound\""
ERROR_CSS_TAG_RULE_NOTFOUND = "String  \"error.css.tag.rule.notfound\""
ERROR_STYLESHEET_SELECTOR_NOTFOUND = "String  \"error.css.stylesheet.selector.notfound\""
ERROR_CSS_TAG_SELECTOR_NOTFOUND = "String  \"error.css.tag.selector.notfound\""
ERROR_STYLESHEET_SELECTOR_DISALLOWED = "String  \"error.css.stylesheet.selector.disallowed\""
ERROR_CSS_TAG_SELECTOR_DISALLOWED = "String  \"error.css.tag.selector.disallowed\""
ERROR_STYLESHEET_PROPERTY_INVALID = "String  \"error.css.stylesheet.property.invalid\""
ERROR_CSS_TAG_PROPERTY_INVALID = "String  \"error.css.tag.property.invalid\""
def getMessage():
    '''    public static String getMessage(final ResourceBundle messages, final String msgKey, final Object[] arguments)
    '''
