CLUSTER_TYPE_APPLICATION_SERVER = "String  \"APPLICATION_SERVER\""
CLUSTER_TYPE_PROXY_SERVER = "String  \"PROXY_SERVER\""
CLUSTER_TYPE_ONDEMAND_ROUTER = "String  \"ONDEMAND_ROUTER\""
def ClusterData():
    '''    public ClusterData()
    '''
