MICHIGO = "int 0"
DOUSHI = "int 1"
ADD_V = "int 2"
ADD_V2 = "int 3"
MEISHI = "int 4"
FUKUSHITEKI_MEISHI = "int 5"
JOSUUSHI = "int 6"
KEISHIKI_MEISHI = "int 7"
KOYUU_KOYUU_MEISHI = "int 8"
KOYUU_MEISHI = "int 9"
KOYUU_MEISHI_SEI = "int 10"
KOYUU_MEISHI_MEI = "int 11"
KOYUU_MEISHI_SOSHIKI = "int 12"
KOYUU_MEISHI_KUNI = "int 13"
KOYUU_MEISHI_CHIMEI = "int 14"
KOYUU_MEISHI_SONOTA = "int 15"
KOYUU_MEISHI_SEIMEI = "int 16"
KEIYOU_DOUSHI = "int 17"
ADD_AN = "int 18"
ADD_AN2 = "int 19"
SUUJI = "int 20"
DAIMEISHI = "int 21"
ADD_A = "int 22"
KEIYOUSHI = "int 23"
FUKUSHI = "int 24"
RENTAISHI = "int 25"
SETSUZOKUSHI = "int 26"
SETSUBIJI = "int 27"
SETTOUJI = "int 28"
SUUSHI_SETSUBI = "int 29"
SUUSHI_SETTOU = "int 30"
JODOUSHI = "int 31"
AUX_A1 = "int 32"
AUX_V = "int 33"
AUX_V1 = "int 34"
JODOUSHI_DESU = "int 35"
PART_AUX = "int 36"
INYOU_JOSHI = "int 37"
JOSHI_NO = "int 38"
KAKU_JOSHI = "int 39"
KAKU_JOSHI1 = "int 40"
PARTICLE_ADNOMINAL = "int 41"
PARTICLE_V = "int 42"
SETSUZOKU_JOSHI = "int 43"
FUKU_JOSHI = "int 44"
FUKU_JOSHI1 = "int 45"
SHUU_JOSHI = "int 46"
FUTEI_JOSHI = "int 47"
HEIRETSU_JOSHI = "int 48"
RENTAI_HEIRETSU_JOSHI = "int 49"
KEI_JOSHI = "int 50"
PART_PARTICLE = "int 51"
PARTICLE_IDIOM_RY = "int 52"
RENTAI_JOSHI = "int 53"
JOUKYOU_KA = "int 54"
JOUKYOUKA_FUNC = "int 55"
JUN_TAIGEN = "int 56"
CUSHION = "int 57"
V_INFL = "int 58"
ADD_V_INFL = "int 59"
PART_V_INFL = "int 60"
A_INFL = "int 61"
AN_INFL = "int 62"
AUX_INFL = "int 63"
PART_AUX_INFL = "int 64"
PART_V_SUF = "int 65"
KIGOU = "int 66"
HIRAKI_KAKKO = "int 67"
TOJI_KAKKO = "int 68"
KUTEN = "int 69"
TOUTEN = "int 70"
DELIMITER = "int 71"
SUUJI_COMMA = "int 72"
def toString():
'''public static final String toString(final int n)
'''
pass
def toPOS():
'''public static final int toPOS(final int n)
'''
pass
def isStopword():
'''public static final boolean isStopword(final int n)
'''
pass
