USERNAME_PROPERTY = "String  javax.xml.rpc.security.auth.username""
PASSWORD_PROPERTY = "String  javax.xml.rpc.security.auth.password""
OPERATION_STYLE_PROPERTY = "String  javax.xml.rpc.soap.operation.style""
SOAPACTION_USE_PROPERTY = "String  javax.xml.rpc.soap.http.soapaction.use""
SOAPACTION_URI_PROPERTY = "String  javax.xml.rpc.soap.http.soapaction.uri""
ENCODINGSTYLE_URI_PROPERTY = "String  javax.xml.rpc.encodingstyle.namespace.uri""
SESSION_MAINTAIN_PROPERTY = "String  javax.xml.rpc.session.maintain""
