sdbIRI = "String  \"http://jena.hpl.hp.com/#sdb\""
namespace = "String  \"http://jena.hpl.hp.com/2007/sdb#\""
symbolPrefix = "String  \"sdb\""
symbolSpace = "String  \"http://jena.hpl.hp.com/SDB/symbol#\""
PATH = "String  \"com.hp.hpl.jena.sdb\""
NAME = "String  \"SDB\""
