BEAN_NAME_DELIMITERS = "String  \",; \""
TRUE_VALUE = "String  \"true\""
DEFAULT_VALUE = "String  \"default\""
DESCRIPTION_ELEMENT = "String  \"description\""
AUTOWIRE_BY_NAME_VALUE = "String  \"byName\""
AUTOWIRE_BY_TYPE_VALUE = "String  \"byType\""
AUTOWIRE_CONSTRUCTOR_VALUE = "String  \"constructor\""
AUTOWIRE_AUTODETECT_VALUE = "String  \"autodetect\""
DEPENDENCY_CHECK_ALL_ATTRIBUTE_VALUE = "String  \"all\""
DEPENDENCY_CHECK_SIMPLE_ATTRIBUTE_VALUE = "String  \"simple\""
DEPENDENCY_CHECK_OBJECTS_ATTRIBUTE_VALUE = "String  \"objects\""
DEFAULT_LAZY_INIT_ATTRIBUTE = "String  \"default-lazy-init\""
DEFAULT_AUTOWIRE_ATTRIBUTE = "String  \"default-autowire\""
DEFAULT_DEPENDENCY_CHECK_ATTRIBUTE = "String  \"default-dependency-check\""
IMPORT_ELEMENT = "String  \"import\""
RESOURCE_ATTRIBUTE = "String  \"resource\""
ALIAS_ELEMENT = "String  \"alias\""
NAME_ATTRIBUTE = "String  \"name\""
ALIAS_ATTRIBUTE = "String  \"alias\""
BEAN_ELEMENT = "String  \"bean\""
ID_ATTRIBUTE = "String  \"id\""
PARENT_ATTRIBUTE = "String  \"parent\""
CLASS_ATTRIBUTE = "String  \"class\""
ABSTRACT_ATTRIBUTE = "String  \"abstract\""
SINGLETON_ATTRIBUTE = "String  \"singleton\""
LAZY_INIT_ATTRIBUTE = "String  \"lazy-init\""
AUTOWIRE_ATTRIBUTE = "String  \"autowire\""
DEPENDENCY_CHECK_ATTRIBUTE = "String  \"dependency-check\""
DEPENDS_ON_ATTRIBUTE = "String  \"depends-on\""
INIT_METHOD_ATTRIBUTE = "String  \"init-method\""
DESTROY_METHOD_ATTRIBUTE = "String  \"destroy-method\""
FACTORY_METHOD_ATTRIBUTE = "String  \"factory-method\""
FACTORY_BEAN_ATTRIBUTE = "String  \"factory-bean\""
CONSTRUCTOR_ARG_ELEMENT = "String  \"constructor-arg\""
INDEX_ATTRIBUTE = "String  \"index\""
TYPE_ATTRIBUTE = "String  \"type\""
PROPERTY_ELEMENT = "String  \"property\""
REF_ATTRIBUTE = "String  \"ref\""
VALUE_ATTRIBUTE = "String  \"value\""
LOOKUP_METHOD_ELEMENT = "String  \"lookup-method\""
REPLACED_METHOD_ELEMENT = "String  \"replaced-method\""
REPLACER_ATTRIBUTE = "String  \"replacer\""
ARG_TYPE_ELEMENT = "String  \"arg-type\""
ARG_TYPE_MATCH_ATTRIBUTE = "String  \"match\""
REF_ELEMENT = "String  \"ref\""
IDREF_ELEMENT = "String  \"idref\""
BEAN_REF_ATTRIBUTE = "String  \"bean\""
LOCAL_REF_ATTRIBUTE = "String  \"local\""
PARENT_REF_ATTRIBUTE = "String  \"parent\""
VALUE_ELEMENT = "String  \"value\""
NULL_ELEMENT = "String  \"null\""
LIST_ELEMENT = "String  \"list\""
SET_ELEMENT = "String  \"set\""
MAP_ELEMENT = "String  \"map\""
ENTRY_ELEMENT = "String  \"entry\""
KEY_ELEMENT = "String  \"key\""
KEY_ATTRIBUTE = "String  \"key\""
KEY_REF_ATTRIBUTE = "String  \"key-ref\""
VALUE_REF_ATTRIBUTE = "String  \"value-ref\""
PROPS_ELEMENT = "String  \"props\""
PROP_ELEMENT = "String  \"prop\""
def ():
    '''returns DefaultXmlBeanDefinitionParser\n\n
    ()\n
    '''
def registerBeanDefinitions():
    '''returns int\n\n
    registerBeanDefinitions(final BeanDefinitionReader reader, final Document doc, final Resource resource)\n
    '''
