CLOSE = "String  \"close\""
CHUNKED = "String  \"chunked\""
GZIP = "String  \"gzip\""
IDENTITY = "String  \"identity\""
KEEP_ALIVE = "String  \"keep-alive\""
CONTINUE = "String  \"100-continue\""
PROCESSING = "String  \"102-processing\""
TE = "String  \"TE\""
BYTES = "String  \"bytes\""
NO_CACHE = "String  \"no-cache\""
UPGRADE = "String  \"Upgrade\""
CLOSE_ORDINAL = "int  1"
CHUNKED_ORDINAL = "int  2"
GZIP_ORDINAL = "int  3"
IDENTITY_ORDINAL = "int  4"
KEEP_ALIVE_ORDINAL = "int  5"
CONTINUE_ORDINAL = "int  6"
PROCESSING_ORDINAL = "int  7"
TE_ORDINAL = "int  8"
BYTES_ORDINAL = "int  9"
NO_CACHE_ORDINAL = "int  10"
UPGRADE_ORDINAL = "int  11"
def hasKnownValues():
    '''public static boolean hasKnownValues(final int httpHeaderOrdinal)
    '''
