type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((NamespaceList$1.class$org$apache$xmlbeans$impl$xb$xmlconfig$NamespaceList$Member2$Item$Member == null) ? (NamespaceList$1.class$org$apache$xmlbeans$impl$xb$xmlconfig$NamespaceList$Member2$Item$Member = NamespaceList$1.class$(\"org.apache.xmlbeans.impl.xb.xmlconfig.NamespaceList$Member2$Item$Member\")) : NamespaceList$1.class$org$apache$xmlbeans$impl$xb$xmlconfig$NamespaceList$Member2$Item$Member).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLCONFIG\").resolveHandle(\"anon1dd3type\")"
ANY = "Enum  Enum.forString(\"##any\")"
INT_ANY = "int  1"
LOCAL = "Enum  Enum.forString(\"##local\")"
INT_LOCAL = "int  1"
