type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((Qnametargetenum$1.class$org$apache$xmlbeans$impl$xb$xmlconfig$Qnametargetenum == null) ? (Qnametargetenum$1.class$org$apache$xmlbeans$impl$xb$xmlconfig$Qnametargetenum = Qnametargetenum$1.class$(\"org.apache.xmlbeans.impl.xb.xmlconfig.Qnametargetenum\")) : Qnametargetenum$1.class$org$apache$xmlbeans$impl$xb$xmlconfig$Qnametargetenum).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLCONFIG\").resolveHandle(\"qnametargetenum9f8ftype\")"
TYPE = "Enum  Enum.forString(\"type\")"
DOCUMENT_TYPE = "Enum  Enum.forString(\"document-type\")"
ACCESSOR_ELEMENT = "Enum  Enum.forString(\"accessor-element\")"
ACCESSOR_ATTRIBUTE = "Enum  Enum.forString(\"accessor-attribute\")"
INT_TYPE = "int  1"
INT_DOCUMENT_TYPE = "int  2"
INT_ACCESSOR_ELEMENT = "int  3"
INT_ACCESSOR_ATTRIBUTE = "int  4"
