def copyConRef():
    '''public ConRef copyConRef(final Connection refCon)
    '''
def isValid():
    '''public boolean isValid()
    public boolean isValid(final int timeout)
    '''
def checkConnection():
    '''public boolean checkConnection()
    '''
def createStatement():
    '''public Statement createStatement()
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency)
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
    '''
def prepareStatement():
    '''public PreparedStatement prepareStatement(final String sql)
    public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency)
    public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
    public PreparedStatement prepareStatement(final String sql, final int autoGeneratedKeys)
    public PreparedStatement prepareStatement(final String sql, final int[] columnIndexes)
    public PreparedStatement prepareStatement(final String sql, final String[] columnNames)
    '''
def prepareCall():
    '''public CallableStatement prepareCall(final String sql)
    public CallableStatement prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency)
    public CallableStatement prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
    '''
def nativeSQL():
    '''public String nativeSQL(final String sql)
    '''
def setAutoCommit():
    '''public void setAutoCommit(final boolean autoCommit)
    '''
def getAutoCommit():
    '''public boolean getAutoCommit()
    '''
def commit():
    '''public void commit()
    '''
def rollback():
    '''public void rollback()
    public void rollback(final Savepoint savepoint)
    '''
def close():
    '''public void close()
    '''
def isClosed():
    '''public boolean isClosed()
    '''
def getMetaData():
    '''public DatabaseMetaData getMetaData()
    '''
def setReadOnly():
    '''public void setReadOnly(final boolean readOnly)
    '''
def isReadOnly():
    '''public boolean isReadOnly()
    '''
def setCatalog():
    '''public void setCatalog(final String catalog)
    '''
def getCatalog():
    '''public String getCatalog()
    '''
def setTransactionIsolation():
    '''public void setTransactionIsolation(final int level)
    '''
def getTransactionIsolation():
    '''public int getTransactionIsolation()
    '''
def getWarnings():
    '''public SQLWarning getWarnings()
    '''
def clearWarnings():
    '''public void clearWarnings()
    '''
def getTypeMap():
    '''public Map getTypeMap()
    '''
def setTypeMap():
    '''public void setTypeMap(final Map map)
    '''
def setHoldability():
    '''public void setHoldability(final int holdability)
    '''
def getHoldability():
    '''public int getHoldability()
    '''
def setSavepoint():
    '''public Savepoint setSavepoint()
    public Savepoint setSavepoint(final String name)
    '''
def releaseSavepoint():
    '''public void releaseSavepoint(final Savepoint savepoint)
    '''
def setConnectionPool():
    '''public void setConnectionPool(final OracleOCIConnectionPool p)
    '''
def getConnectionPool():
    '''public OracleOCIConnectionPool getConnectionPool()
    '''
def getSPID():
    '''public String getSPID()
    '''
def copySPID():
    '''public void copySPID(final ConRef old)
    '''
def createArrayOf():
    '''public Array createArrayOf(final String typeName, final Object[] elements)
    '''
def createBlob():
    '''public Blob createBlob()
    '''
def createClob():
    '''public Clob createClob()
    '''
def createNClob():
    '''public NClob createNClob()
    '''
def createSQLXML():
    '''public SQLXML createSQLXML()
    '''
def createStruct():
    '''public Struct createStruct(final String typeName, final Object[] attributes)
    '''
def getClientInfo():
    '''public Properties getClientInfo()
    public String getClientInfo(final String name)
    '''
def setClientInfo():
    '''public void setClientInfo(final Properties properties)
    public void setClientInfo(final String name, final String value)
    '''
def isWrapperFor():
    '''public boolean isWrapperFor(final Class<?> iface)
    '''
def unwrap():
    '''public <T> T unwrap(final Class<T> iface)
    '''
def setNetworkTimeout():
    '''public void setNetworkTimeout(final Executor executor, final int milliseconds)
    '''
def getNetworkTimeout():
    '''public int getNetworkTimeout()
    '''
def setSchema():
    '''public void setSchema(final String schema)
    '''
def getSchema():
    '''public String getSchema()
    '''
def abort():
    '''public void abort(final Executor executor)
    '''
def print():
    '''public void print()
    '''
