def copyConRef():
    '''returns ConRef\n\n
    copyConRef(final Connection refCon)\n
    '''
def isValid():
    '''returns boolean\n\n
    isValid()\n
    isValid(final int timeout)\n
    '''
def checkConnection():
    '''returns boolean\n\n
    checkConnection()\n
    '''
def createStatement():
    '''returns Statement\n\n
    createStatement()\n
    createStatement(final int resultSetType, final int resultSetConcurrency)\n
    createStatement(final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)\n
    '''
def prepareStatement():
    '''returns PreparedStatement\n\n
    prepareStatement(final String sql)\n
    prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency)\n
    prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)\n
    prepareStatement(final String sql, final int autoGeneratedKeys)\n
    prepareStatement(final String sql, final int[] columnIndexes)\n
    prepareStatement(final String sql, final String[] columnNames)\n
    '''
def prepareCall():
    '''returns CallableStatement\n\n
    prepareCall(final String sql)\n
    prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency)\n
    prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)\n
    '''
def nativeSQL():
    '''returns String\n\n
    nativeSQL(final String sql)\n
    '''
def setAutoCommit():
    '''returns None\n\n
    setAutoCommit(final boolean autoCommit)\n
    '''
def getAutoCommit():
    '''returns boolean\n\n
    getAutoCommit()\n
    '''
def commit():
    '''returns None\n\n
    commit()\n
    '''
def rollback():
    '''returns None\n\n
    rollback()\n
    rollback(final Savepoint savepoint)\n
    '''
def close():
    '''returns None\n\n
    close()\n
    '''
def isClosed():
    '''returns boolean\n\n
    isClosed()\n
    '''
def getMetaData():
    '''returns DatabaseMetaData\n\n
    getMetaData()\n
    '''
def setReadOnly():
    '''returns None\n\n
    setReadOnly(final boolean readOnly)\n
    '''
def isReadOnly():
    '''returns boolean\n\n
    isReadOnly()\n
    '''
def setCatalog():
    '''returns None\n\n
    setCatalog(final String catalog)\n
    '''
def getCatalog():
    '''returns String\n\n
    getCatalog()\n
    '''
def setTransactionIsolation():
    '''returns None\n\n
    setTransactionIsolation(final int level)\n
    '''
def getTransactionIsolation():
    '''returns int\n\n
    getTransactionIsolation()\n
    '''
def getWarnings():
    '''returns SQLWarning\n\n
    getWarnings()\n
    '''
def clearWarnings():
    '''returns None\n\n
    clearWarnings()\n
    '''
def getTypeMap():
    '''returns Map\n\n
    getTypeMap()\n
    '''
def setTypeMap():
    '''returns None\n\n
    setTypeMap(final Map map)\n
    '''
def setHoldability():
    '''returns None\n\n
    setHoldability(final int holdability)\n
    '''
def getHoldability():
    '''returns int\n\n
    getHoldability()\n
    '''
def setSavepoint():
    '''returns Savepoint\n\n
    setSavepoint()\n
    setSavepoint(final String name)\n
    '''
def releaseSavepoint():
    '''returns None\n\n
    releaseSavepoint(final Savepoint savepoint)\n
    '''
def setConnectionPool():
    '''returns None\n\n
    setConnectionPool(final OracleOCIConnectionPool p)\n
    '''
def getConnectionPool():
    '''returns OracleOCIConnectionPool\n\n
    getConnectionPool()\n
    '''
def getSPID():
    '''returns String\n\n
    getSPID()\n
    '''
def copySPID():
    '''returns None\n\n
    copySPID(final ConRef old)\n
    '''
def createArrayOf():
    '''returns Array\n\n
    createArrayOf(final String typeName, final Object[] elements)\n
    '''
def createBlob():
    '''returns Blob\n\n
    createBlob()\n
    '''
def createClob():
    '''returns Clob\n\n
    createClob()\n
    '''
def createNClob():
    '''returns NClob\n\n
    createNClob()\n
    '''
def createSQLXML():
    '''returns SQLXML\n\n
    createSQLXML()\n
    '''
def createStruct():
    '''returns Struct\n\n
    createStruct(final String typeName, final Object[] attributes)\n
    '''
def getClientInfo():
    '''returns String\n\n
    getClientInfo()\n
    getClientInfo(final String name)\n
    '''
def setClientInfo():
    '''returns None\n\n
    setClientInfo(final Properties properties)\n
    setClientInfo(final String name, final String value)\n
    '''
def isWrapperFor():
    '''returns boolean\n\n
    isWrapperFor(final Class<?> iface)\n
    '''
def setNetworkTimeout():
    '''returns None\n\n
    setNetworkTimeout(final Executor executor, final int milliseconds)\n
    '''
def getNetworkTimeout():
    '''returns int\n\n
    getNetworkTimeout()\n
    '''
def setSchema():
    '''returns None\n\n
    setSchema(final String schema)\n
    '''
def getSchema():
    '''returns String\n\n
    getSchema()\n
    '''
def abort():
    '''returns None\n\n
    abort(final Executor executor)\n
    '''
def print():
    '''returns None\n\n
    print()\n
    '''
