sid = "short  4133"
HORIZONTAL_ALIGNMENT_LEFT = "byte  1"
HORIZONTAL_ALIGNMENT_CENTER = "byte  2"
HORIZONTAL_ALIGNMENT_BOTTOM = "byte  3"
HORIZONTAL_ALIGNMENT_JUSTIFY = "byte  4"
VERTICAL_ALIGNMENT_TOP = "byte  1"
VERTICAL_ALIGNMENT_CENTER = "byte  2"
VERTICAL_ALIGNMENT_BOTTOM = "byte  3"
VERTICAL_ALIGNMENT_JUSTIFY = "byte  4"
DISPLAY_MODE_TRANSPARENT = "short  1"
DISPLAY_MODE_OPAQUE = "short  2"
ROTATION_NONE = "short  0"
ROTATION_TOP_TO_BOTTOM = "short  1"
ROTATION_ROTATED_90_DEGREES = "short  2"
ROTATION_ROTATED_90_DEGREES_CLOCKWISE = "short  3"
DATA_LABEL_PLACEMENT_CHART_DEPENDENT = "short  0"
DATA_LABEL_PLACEMENT_OUTSIDE = "short  1"
DATA_LABEL_PLACEMENT_INSIDE = "short  2"
DATA_LABEL_PLACEMENT_CENTER = "short  3"
DATA_LABEL_PLACEMENT_AXIS = "short  4"
DATA_LABEL_PLACEMENT_ABOVE = "short  5"
DATA_LABEL_PLACEMENT_BELOW = "short  6"
DATA_LABEL_PLACEMENT_LEFT = "short  7"
DATA_LABEL_PLACEMENT_RIGHT = "short  8"
DATA_LABEL_PLACEMENT_AUTO = "short  9"
DATA_LABEL_PLACEMENT_USER_MOVED = "short  10"
def ():
    '''returns TextRecord\n\n
    ()\n
    (final RecordInputStream in)\n
    '''
def toString():
    '''returns String\n\n
    toString()\n
    '''
def serialize():
    '''returns None\n\n
    serialize(final LittleEndianOutput out)\n
    '''
def getSid():
    '''returns short\n\n
    getSid()\n
    '''
def clone():
    '''returns Object\n\n
    clone()\n
    '''
def getHorizontalAlignment():
    '''returns byte\n\n
    getHorizontalAlignment()\n
    '''
def setHorizontalAlignment():
    '''returns None\n\n
    setHorizontalAlignment(final byte field_1_horizontalAlignment)\n
    '''
def getVerticalAlignment():
    '''returns byte\n\n
    getVerticalAlignment()\n
    '''
def setVerticalAlignment():
    '''returns None\n\n
    setVerticalAlignment(final byte field_2_verticalAlignment)\n
    '''
def getDisplayMode():
    '''returns short\n\n
    getDisplayMode()\n
    '''
def setDisplayMode():
    '''returns None\n\n
    setDisplayMode(final short field_3_displayMode)\n
    '''
def getRgbColor():
    '''returns int\n\n
    getRgbColor()\n
    '''
def setRgbColor():
    '''returns None\n\n
    setRgbColor(final int field_4_rgbColor)\n
    '''
def getX():
    '''returns int\n\n
    getX()\n
    '''
def setX():
    '''returns None\n\n
    setX(final int field_5_x)\n
    '''
def getY():
    '''returns int\n\n
    getY()\n
    '''
def setY():
    '''returns None\n\n
    setY(final int field_6_y)\n
    '''
def getWidth():
    '''returns int\n\n
    getWidth()\n
    '''
def setWidth():
    '''returns None\n\n
    setWidth(final int field_7_width)\n
    '''
def getHeight():
    '''returns int\n\n
    getHeight()\n
    '''
def setHeight():
    '''returns None\n\n
    setHeight(final int field_8_height)\n
    '''
def getOptions1():
    '''returns short\n\n
    getOptions1()\n
    '''
def setOptions1():
    '''returns None\n\n
    setOptions1(final short field_9_options1)\n
    '''
def getIndexOfColorValue():
    '''returns short\n\n
    getIndexOfColorValue()\n
    '''
def setIndexOfColorValue():
    '''returns None\n\n
    setIndexOfColorValue(final short field_10_indexOfColorValue)\n
    '''
def getOptions2():
    '''returns short\n\n
    getOptions2()\n
    '''
def setOptions2():
    '''returns None\n\n
    setOptions2(final short field_11_options2)\n
    '''
def getTextRotation():
    '''returns short\n\n
    getTextRotation()\n
    '''
def setTextRotation():
    '''returns None\n\n
    setTextRotation(final short field_12_textRotation)\n
    '''
def setAutoColor():
    '''returns None\n\n
    setAutoColor(final boolean value)\n
    '''
def isAutoColor():
    '''returns boolean\n\n
    isAutoColor()\n
    '''
def setShowKey():
    '''returns None\n\n
    setShowKey(final boolean value)\n
    '''
def isShowKey():
    '''returns boolean\n\n
    isShowKey()\n
    '''
def setShowValue():
    '''returns None\n\n
    setShowValue(final boolean value)\n
    '''
def isShowValue():
    '''returns boolean\n\n
    isShowValue()\n
    '''
def setVertical():
    '''returns None\n\n
    setVertical(final boolean value)\n
    '''
def isVertical():
    '''returns boolean\n\n
    isVertical()\n
    '''
def setAutoGeneratedText():
    '''returns None\n\n
    setAutoGeneratedText(final boolean value)\n
    '''
def isAutoGeneratedText():
    '''returns boolean\n\n
    isAutoGeneratedText()\n
    '''
def setGenerated():
    '''returns None\n\n
    setGenerated(final boolean value)\n
    '''
def isGenerated():
    '''returns boolean\n\n
    isGenerated()\n
    '''
def setAutoLabelDeleted():
    '''returns None\n\n
    setAutoLabelDeleted(final boolean value)\n
    '''
def isAutoLabelDeleted():
    '''returns boolean\n\n
    isAutoLabelDeleted()\n
    '''
def setAutoBackground():
    '''returns None\n\n
    setAutoBackground(final boolean value)\n
    '''
def isAutoBackground():
    '''returns boolean\n\n
    isAutoBackground()\n
    '''
def setRotation():
    '''returns None\n\n
    setRotation(final short value)\n
    '''
def getRotation():
    '''returns short\n\n
    getRotation()\n
    '''
def setShowCategoryLabelAsPercentage():
    '''returns None\n\n
    setShowCategoryLabelAsPercentage(final boolean value)\n
    '''
def isShowCategoryLabelAsPercentage():
    '''returns boolean\n\n
    isShowCategoryLabelAsPercentage()\n
    '''
def setShowValueAsPercentage():
    '''returns None\n\n
    setShowValueAsPercentage(final boolean value)\n
    '''
def isShowValueAsPercentage():
    '''returns boolean\n\n
    isShowValueAsPercentage()\n
    '''
def setShowBubbleSizes():
    '''returns None\n\n
    setShowBubbleSizes(final boolean value)\n
    '''
def isShowBubbleSizes():
    '''returns boolean\n\n
    isShowBubbleSizes()\n
    '''
def setShowLabel():
    '''returns None\n\n
    setShowLabel(final boolean value)\n
    '''
def isShowLabel():
    '''returns boolean\n\n
    isShowLabel()\n
    '''
def setDataLabelPlacement():
    '''returns None\n\n
    setDataLabelPlacement(final short value)\n
    '''
def getDataLabelPlacement():
    '''returns short\n\n
    getDataLabelPlacement()\n
    '''
