NS_URI_HTTP = "String  \"http://schemas.xmlsoap.org/wsdl/http/\""
ELEM_ADDRESS = "String  \"address\""
ELEM_URL_ENCODED = "String  \"urlEncoded\""
ELEM_URL_REPLACEMENT = "String  \"urlReplacement\""
ATTR_VERB = "String  \"verb\""
