def DiffBuilder():
    '''public DiffBuilder(final Object lhs, final Object rhs, final ToStringStyle style, final boolean testTriviallyEqual)
    public DiffBuilder(final Object lhs, final Object rhs, final ToStringStyle style)
    '''
def append():
    '''public DiffBuilder append(final String fieldName, final boolean lhs, final boolean rhs)
    public DiffBuilder append(final String fieldName, final boolean[] lhs, final boolean[] rhs)
    public DiffBuilder append(final String fieldName, final byte lhs, final byte rhs)
    public DiffBuilder append(final String fieldName, final byte[] lhs, final byte[] rhs)
    public DiffBuilder append(final String fieldName, final char lhs, final char rhs)
    public DiffBuilder append(final String fieldName, final char[] lhs, final char[] rhs)
    public DiffBuilder append(final String fieldName, final double lhs, final double rhs)
    public DiffBuilder append(final String fieldName, final double[] lhs, final double[] rhs)
    public DiffBuilder append(final String fieldName, final float lhs, final float rhs)
    public DiffBuilder append(final String fieldName, final float[] lhs, final float[] rhs)
    public DiffBuilder append(final String fieldName, final int lhs, final int rhs)
    public DiffBuilder append(final String fieldName, final int[] lhs, final int[] rhs)
    public DiffBuilder append(final String fieldName, final long lhs, final long rhs)
    public DiffBuilder append(final String fieldName, final long[] lhs, final long[] rhs)
    public DiffBuilder append(final String fieldName, final short lhs, final short rhs)
    public DiffBuilder append(final String fieldName, final short[] lhs, final short[] rhs)
    public DiffBuilder append(final String fieldName, final Object lhs, final Object rhs)
    public DiffBuilder append(final String fieldName, final Object[] lhs, final Object[] rhs)
    '''
def getLeft():
    '''public Boolean getLeft()
    public Boolean[] getLeft()
    public Byte getLeft()
    public Byte[] getLeft()
    public Character getLeft()
    public Character[] getLeft()
    public Double getLeft()
    public Double[] getLeft()
    public Float getLeft()
    public Float[] getLeft()
    public Integer getLeft()
    public Integer[] getLeft()
    public Long getLeft()
    public Long[] getLeft()
    public Short getLeft()
    public Short[] getLeft()
    public Object getLeft()
    public Object[] getLeft()
    '''
def getRight():
    '''public Boolean getRight()
    public Boolean[] getRight()
    public Byte getRight()
    public Byte[] getRight()
    public Character getRight()
    public Character[] getRight()
    public Double getRight()
    public Double[] getRight()
    public Float getRight()
    public Float[] getRight()
    public Integer getRight()
    public Integer[] getRight()
    public Long getRight()
    public Long[] getRight()
    public Short getRight()
    public Short[] getRight()
    public Object getRight()
    public Object[] getRight()
    '''
def build():
    '''public DiffResult build()
    '''
