ATTR_ID = "String  \"id\""
ATTR_SCHEMA_LOCATION = "String  \"schemaLocation\""
ELEM_SCHEMA = "String  \"schema\""
ELEM_INCLUDE = "String  \"include\""
ELEM_REDEFINE = "String  \"redefine\""
NS_URI_XSD_1999 = "String  \"http://www.w3.org/1999/XMLSchema\""
NS_URI_XSD_2000 = "String  \"http://www.w3.org/2000/10/XMLSchema\""
NS_URI_XSD_2001 = "String  \"http://www.w3.org/2001/XMLSchema\""
