KEY_RELAXED_UNFOLDING = "String  \"ical4j.unfolding.relaxed\""
KEY_RELAXED_PARSING = "String  \"ical4j.parsing.relaxed\""
KEY_RELAXED_VALIDATION = "String  \"ical4j.validation.relaxed\""
KEY_OUTLOOK_COMPATIBILITY = "String  \"ical4j.compatibility.outlook\""
KEY_NOTES_COMPATIBILITY = "String  \"ical4j.compatibility.notes\""
KEY_VCARD_COMPATIBILITY = "String  \"ical4j.compatibility.vcard\""
