UPDATE_INTERVAL = "String  updateInterval""
AUTO_UPDATE_CAPABILITIES = "String  autoUpdateCapabilities""
PARAM_COMPID = "String  facesComponentId""
FILENAME = "String  filename""
COLUMN_RESIZE_MESSAGE = "String  columnResizeMessage""
SESSION_ID_PREFIX = "String  ILOGGanttChart""
