USEWITH_SCHEDULER = "String  SCHEDULER""
USEWITH_ASSET_SCHEDULER = "String  SCHEDACM""
USEWITH_SCHEDULER_LARGEPROJECT = "String  SCHEDMAX""
USEWITH_REPAIR_LOCATION_CAPACTIY_PLANNING = "String  RLCAPACITY""
USEWITH_REPAIR_LOCATION_ASSIGN = "String  RLASSIGN""
USEWITH_GRAPHICAL_ASSIGN = "String  GRPASSIGN""
USEWITH_CREW_GRAPHICAL_ASSIGN = "String  CGRPASSIGN""
USEWITH_GWORKASSIGN = "String  GWORKASSIGN""
USEWITH_SCHEDULER_DATA_MANAGER = "String  SCHEDDM""
def useWith():
'''public static boolean useWith(final String useWith, final String... values)
'''
pass
