LOG_FILE_PROPERTY = "String  \"pdq.traceFile\""
LOG_FILE_DEFAULT = "String  \"pdq.log\""
ENABLE_CMX_SERVER_LOG_PROPERTY = "String  \"pdq.enableCMXServerLog\""
ENABLE_CMX_SERVER_LOG_DEFAULT = "String  \"ON\""
CMX_SERVER_LOG_FILE_COUNT_PROPERTY = "String  \"pdq.cmxServerLogFileCount\""
CMX_SERVER_LOG_FILE_COUNT_DEFAULT = "String  \"6\""
CMX_SERVER_LOG_FILE_SIZE_PROPERTY = "String  \"pdq.cmxServerLogFileSize\""
CMX_SERVER_LOG_FILE_SIZE_DEFAULT = "String  \"50000000\""
CMX_SERVER_LOG_TRACE_LEVEL_PROPERTY = "String  \"pdq.cmxServerLogTraceLevel\""
CMX_SERVER_LOG_TRACE_LEVEL_DEFAULT = "String  \"INFO\""
ENABLE_ROLLING_LOG_PROPERTY = "String  \"pdq.enableRollingLog\""
ENABLE_ROLLING_LOG_DEFAULT = "String  \"ON\""
ROLLING_LOG_FILE_COUNT_PROPERTY = "String  \"pdq.rollingLogFileCount\""
ROLLING_LOG_FILE_COUNT_DEFAULT = "String  \"5\""
ROLLING_LOG_FILE_SIZE_PROPERTY = "String  \"pdq.rollingLogFileSize\""
ROLLING_LOG_FILE_SIZE_DEFAULT = "String  \"50000000\""
ENABLE_TRACE_POLLING_PROPERTY = "String  \"pdq.enableTracePolling\""
ENABLE_TRACE_POLLING_DEFAULT = "String  \"ON\""
TRACE_POLLING_INTERVAL_PROPERTY = "String  \"pdq.tracePollingInterval\""
TRACE_POLLING_INTERVAL_DEFAULT = "String  \"30\""
LOG_FILE_LEVEL_PROPERTY = "String  \"pdq.traceLevel\""
LOG_FILE_LEVEL_DEFAULT = "String  \"OFF\""
LOG_TRACE_BUFFER_ROW_COUNT = "String  \"pdq.traceBufferRowCount\""
LOG_TRACE_BUFFER_ROW_COUNT_DEFAULT = "String  \"0\""
LOG_SQL_ERR_CODE_DUMP_PROPERTY = "String  \"pdq.dumpLogsOnSqlCodes\""
LOG_EXCLUDED_SQL_ERR_CODE_PROPERTY = "String  \"pdq.dumpLogsExcludingSqlCodes\""
LOG_EXCLUDED_SQL_ERR_CODE_DEFAULT = "String  \"\""
EXECUTION_MODE_PROPERTY = "String  \"pdq.executionMode\""
EXECUTION_MODE_DEFAULT = "String  \"DYNAMIC\""
QUERY_TIMEOUT = "String  \"pdq.queryTimeoutInSeconds\""
MAX_ROWS = "String  \"pdq.maxResultRows\""
PROPERTIES_REFRESH_INTERVAL = "String  \"pdq.propertiesRefreshInterval\""
PROPERTIES_REFRESH_INTERVAL_DEFAULT = "String  \"0\""
REPOSITORY_RTG_ACTIVATION_CHECK_INTERVAL = "String  \"pdq.runtimeGroupActivationCheckInterval\""
REPOSITORY_RTG_ACTIVATION_CHECK_INTERVAL_DEFAULT = "String  \"2\""
DISABLE_REPOSITORY_PROPERTIES_AND_XML_RELOAD = "String  \"pdq.disableRepositoryPropertiesAndXMLReload\""
DISABLE_REPOSITORY_PROPERTIES_AND_XML_RELOAD_DEFAULT = "String  \"FALSE\""
ALLOW_GETTER_SETTER_METHOD_WITH_PUBLIC_FIELD = "String  \"pdq.allowGetterSetterMethodWithPublicField\""
ALLOW_GETTER_SETTER_METHOD_WITH_PUBLIC_FIELD_DEFAULT = "String  \"false\""
IGNORE_ORPHAN_GETTER_SETTER_METHODS = "String  \"pdq.ignoreOrphanGetterSetterMethods\""
IGNORE_ORPHAN_GETTER_SETTER_METHODS_DEFAULT = "String  \"false\""
ALLOW_MDM_BEAN_RULES = "String  \"pdq.allowMDMBeanRules\""
ALLOW_MDM_BEAN_RULES_DEFAULT = "String  \"false\""
CONTROLLER_DISCOVERY_PORT = "String  \"pdq.cmx.controllerDiscoveryPort\""
CONTROLLER_DISCOVERY_PORT_DEFAULT = "String  \"50000\""
CONTROLLER_DISCOVERY_INTERVAL = "String  \"pdq.cmx.controllerDiscoveryInterval\""
CONTROLLER_DISCOVERY_INTERVAL_DEFAULT = "String  \"-1\""
CONTROLLER_DISCOVERY_DISABLED = "String  \"-2\""
CONTROLLER_URL_PROPERTY = "String  \"pdq.cmx.controllerURL\""
CMX_SERVER_PROPERTY = "String  \"pdq.cmx.server\""
CMX_CONTROLLER_ACCESS_POLICY = "String  \"pdq.cmx.controllerAccessPolicy\""
CMX_READ_TIMEOUT_PROPERTY = "String  \"pdq.cmx.readTimeout\""
CMX_CONNECT_TIMEOUT_PROPERTY = "String  \"pdq.cmx.connectTimeout\""
CMX_HTTP_CONTROLLER_URL_PROPERTY = "String  \"pdq.cmx.http.controllerURL\""
CMX_HTTP_PROXY_URL_PROPERTY = "String  \"pdq.cmx.http.proxyURL\""
CMX_CLIENT_CACHE_DIRECTORY = "String  \"pdq.cmx.clientCacheDirectory\""
CMX_UUID_PROPERTY = "String  \"pdq.cmx.uuid\""
CMX_HTTP_REQUEST_PATH_PROPERTY = "String  \"pdq.cmx.http.requestPath\""
CMX_HTTP_REQUEST_PATH_PROPERTY_DEFAULT = "String  \"/cmx/controller\""
CMX_HTTP_DISCONNECT_PROPERTY = "String  \"pdq.cmx.http.disconnect\""
CMX_HTTP_DISCONNECT_PROPERTY_DEFAULT = "String  \"false\""
MULTICAST_TTL_PROPERTY = "String  \"pdq.cmx.multicastTimeToLive\""
MULTICAST_TTL_DEFAULT = "String  \"10\""
DATASOURCE_LOOKUP_INTERVAL_PROPERTY = "String  \"pdq.cmx.dataSourceLookupInterval\""
DATASOURCE_LOOKUP_INTERVAL_DEFAULT = "String  \"20\""
PACKAGE_PREFIX_EXCLUSIONS = "String  \"pdq.packagePrefixExclusions\""
ENABLE_DYN_SQL_REPLACEMENT = "String  \"pdq.enableDynamicSQLReplacement\""
ENABLE_DYN_SQL_REPLACEMENT_DEFAULT = "String  \"false\""
MAX_STACK_TRACES_CAPTURED = "String  \"pdq.maxStackTracesCaptured\""
MAX_STACK_TRACES_CAPTURED_DEFAULT = "String  \"5\""
CAPTURE_MODE = "String  \"pdq.captureMode\""
CAPTURE_MODE_DEFAULT = "String  \"OFF\""
ALLOW_DYN_SQL = "String  \"pdq.allowDynamicSQL\""
ALLOW_DYN_SQL_DEFAULT = "String  \"true\""
INPUT_PUREQUERY_XML = "String  \"pdq.pureQueryXml\""
OUTPUT_PUREQUERY_XML = "String  \"pdq.outputPureQueryXml\""
STACK_TRACE_DEPTH = "String  \"pdq.stackTraceDepth\""
STACK_TRACE_DEPTH_DEFAULT = "String  \"10\""
MAX_NON_PARAM_SQL = "String  \"pdq.maxNonParmSQL\""
MAX_NON_PARAM_SQL_DEFAULT = "String  \"-1\""
CAPTURE_STMT_BATCH_SQL = "String  \"pdq.captureStatementBatchSQL\""
CAPTURE_STMT_BATCH_SQL_DEFAULT = "String  \"ON\""
CAPTURED_ONLY = "String  \"pdq.capturedOnly\""
CAPTURED_ONLY_DEFAULT = "String  \"false\""
DISABLE_JDBC_PREREQUISITE_ENFORCEMENT = "String  \"pdq.disableJDBCPrerequisiteEnforcement\""
DISABLE_JDBC_PREREQUISITE_ENFORCEMENT_DEFAULT = "String  \"false\""
SQL_LITERAL_SUBSTITUTION = "String  \"pdq.sqlLiteralSubstitution\""
SQL_LITERAL_SUBSTITUTION_DEFAULT = "String  \"NOT_SET\""
FINAL_REPOSITORY_PROPERTIES = "String  \"pdq.finalRepositoryProperties\""
PROPERTIES_GROUP_ID = "String  \"pdq.propertiesGroupId\""
REPOSITORY_SCHEMA = "String  \"pdq.repositorySchema\""
REPOSITORY_SCHEMA_DEFAULT = "String  \"IBMPDQ\""
OUTPUT_XML_REPOSITORY = "String  \"pdq.outputXmlRepository\""
REPOSITORY_REQUIRED = "String  \"pdq.repositoryRequired\""
RepositoryErrorCheckTime = "long  10L"
DS_NAME_KEY = "String  \"dataSourceName\""
PDQ_DS_PROPERTIES_ABSOLUTE_PATH_KEY = "String  \"pdq.dataSourceName.properties\""
PDQ_APPWIDE_PROPERTIES_ABSOLUTE_PATH_KEY = "String  \"pdq.appwide.properties\""
PDQ_WAS_EXT_CLASS_LOADER = "String  \"wasExtClassLoader\""
CMX_WAS_PURGEPOOL = "String  \"pdq.cmx.purgeWASPool\""
CMX_WAS_PURGEPOOL_TYPE = "String  \"pdq.cmx.purgeWASPool.type\""
def run():
    '''returns ProtectionDomain\n\n
    run()\n
    run()\n
    run()\n
    run()\n
    run()\n
    run()\n
    run()\n
    run()\n
    '''
def getPropertyValue():
    '''returns String\n\n
    getPropertyValue()\n
    '''
def ():
    '''returns SourceInfoForNonGlobalProperties\n\n
    ()\n
    '''
