PROTOCOL_TYPE = "String  \"consumer\""
VERSION_KEY_NAME = "String  \"version\""
TOPICS_KEY_NAME = "String  \"topics\""
TOPIC_KEY_NAME = "String  \"topic\""
PARTITIONS_KEY_NAME = "String  \"partitions\""
TOPIC_PARTITIONS_KEY_NAME = "String  \"topic_partitions\""
USER_DATA_KEY_NAME = "String  \"user_data\""
CONSUMER_PROTOCOL_V0 = "short  0"
