ID_CI_IMPL_TASK_CATAGORY = "String ID_CI_TASK""
ID_OWNER_IMPL_TASK_CATAGORY = "String ID_OWNER_TASK""
ID_BLACKOUT_PERIOD_CATAGORY = "String ID_BLACKOUT_PERIOD""
ID_CHANGE_WINDOW_CATAGORY = "String ID_CHANGE_WINDOW""
ID_WORK_SHIFT_TWSET = "String ID_WORK_SHIFT""
PATH_OWNER_IMPL_TASK_CATAGORY = "String _ID_ROOT>ID_OWNER_TASK""
IMAGE_PERSON = "String pmchg/tr_person.gif""
IMAGE_PERSONGROUP = "String pmchg/tr_personGroup.gif""
IMAGE_TARGET_CI = "String pmchg/tr_CI_target.gif""
IMAGE_IMPACT_CI = "String pmchg/tr_CI_impacted.gif""
IMAGE_LOCKDOWN_BLACKOUT = "String pmchg/tr_CI_lockdown.gif""
IMAGE_RESTRICTED_BLACKOUT = "String pmchg/tr_CI_restricted.gif""
IMAGE_CHANGE_WINDOW = "String pmchg/tr_CI_changeWindow.gif""
IMAGE_CALENDAR = "String pmchg/tr_calendar.gif""
WORKORDER_ACTIVE = "String (select value from synonymdomain where domainid='WOSTATUS' and maxvalue<>'COMP' and maxvalue<>'CAN' and maxvalue<>'CLOSE')""
