CORE_PROPERTIES_PART = "String  \"application/vnd.openxmlformats-package.core-properties+xml\""
DIGITAL_SIGNATURE_CERTIFICATE_PART = "String  \"application/vnd.openxmlformats-package.digital-signature-certificate\""
DIGITAL_SIGNATURE_ORIGIN_PART = "String  \"application/vnd.openxmlformats-package.digital-signature-origin\""
DIGITAL_SIGNATURE_XML_SIGNATURE_PART = "String  \"application/vnd.openxmlformats-package.digital-signature-xmlsignature+xml\""
RELATIONSHIPS_PART = "String  \"application/vnd.openxmlformats-package.relationships+xml\""
CUSTOM_XML_PART = "String  \"application/vnd.openxmlformats-officedocument.customXmlProperties+xml\""
PLAIN_OLD_XML = "String  \"application/xml\""
IMAGE_JPEG = "String  \"image/jpeg\""
EXTENSION_JPG_1 = "String  \"jpg\""
EXTENSION_JPG_2 = "String  \"jpeg\""
IMAGE_PNG = "String  \"image/png\""
EXTENSION_PNG = "String  \"png\""
IMAGE_GIF = "String  \"image/gif\""
EXTENSION_GIF = "String  \"gif\""
IMAGE_TIFF = "String  \"image/tiff\""
EXTENSION_TIFF = "String  \"tiff\""
IMAGE_PICT = "String  \"image/pict\""
EXTENSION_PICT = "String  \"tiff\""
XML = "String  \"text/xml\""
EXTENSION_XML = "String  \"xml\""
def getContentTypeFromFileExtension():
    '''public static String getContentTypeFromFileExtension(final String filename)
    '''
