NodeName = "String  \"global_prop\""
Grids_CookieExpires = "String  \"Grids.CookieExpires\""
Grids_CookieParam = "String  \"Grids.CookieParam\""
Grids_Focused = "String  \"Grids.Focused\""
Grids_NoTryActiveX = "String  \"Grids.NoTryActiveX\""
