NodeName = "String  \"Header\""
CanCopy = "String  \"CanCopy\""
CanDelete = "String  \"CanDelete\""
CanSelect = "String  \"CanSelect\""
NoEscape = "String  \"NoEscape\""
PanelHeaderxxxTip = "String  \"PanelHeaderTip\""
SortIcons = "String  \"SortIcons\""
