NodeName = "String  \"Root\""
AcceptDef = "String  \"AcceptDef\""
AddParent = "String  \"AddParent\""
CDef = "String  \"CDef\""
CanSort = "String  \"CanSort\""
FocusCell = "String  \"FocusCell\""
FocusRow = "String  \"FocusRow\""
