Start = "String  Start""
End = "String  End""
Duration = "String  Duration""
Type = "String  Type""
Text = "String  Text""
Class = "String  Class""
Tip = "String  Tip""
Id = "String  Id""
Group = "String  Group""
State = "String  State""
Top = "String  Top""
Height = "String  Height""
Manual = "String  Manual""
Complete = "String  Complete""
Resources = "String  Resources""
TextLeft = "String  TextLeft""
TextRight = "String  TextRight""
STATE_disabled_ = "int  1"
STATE_locked = "int  2"
STATE_selected = "int  4"
STATE_added = "int  8"
STATE_deleted = "int  16"
STATE_moved = "int  32"
STATE_resized = "int  64"
STATE_changed = "int  128"
TYPE_Box = "String  Box""
TYPE_Solid = "String  Solid""
TYPE_Left = "String  Left""
TYPE_Right = "String  Right""
TYPE_Fixed = "String  Fixed""
TYPE_Milestone = "String  Milestone""
TYPE_Stop = "String  Stop""
TYPE_Empty = "String  Empty""
TYPE_Nbsp = "String  Nbsp""
TYPE_Bound = "String  Bound""
TYPE_End = "String  End""
def newJSONRunItem():
'''public static JSONObject newJSONRunItem(final String id)
'''
pass
