MEP_FIREANDFORGET = "String  \"fireandforget\""
MEP_SENDRECEIVE = "String  \"sendreceive\""
MEP_SENDROBUST = "String  \"sendrobust\""
def invokeWebService():
    '''returns Document\n\n
    invokeWebService(final String serviceName, final String endpointURL, final OMElement payload, final String httpProtocolVersion, final String httpUserName, final String httpPassword, final String soapAction, final String mep, final String soapVersion, final String wsAddrVersion, final String utUser, final String utPassword, final String configXMLPath)\n
    invokeWebService(final String serviceName, final String endpointURL, final OMElement payload, final String httpProtocolVersion, final String httpUserName, final String httpPassword, final String soapAction, final String mep, final String soapVersion, final String wsAddrVersion, final String utUser, final String utPassword, final int httpReadTimeout, final int httpConnTimeout, final String configXMLPath)\n
    invokeWebService(final String serviceName, final String endpointURL, final OMElement payload, final String httpProtocolVersion, final String httpUserName, final String httpPassword, final String soapAction, final String mep, final String soapVersion, final String wsAddrVersion, final String utUser, final String utPassword, final int httpReadTimeout, final int httpConnTimeout, final String configXMLPath, final Map<QName, String> soapHeaderProps, final List<OMElement> soapHeaderElements)\n
    invokeWebService(final String serviceName, final String endpointURL, final byte[] payload, final String httpProtocolVersion, final String httpUserName, final String httpPassword, final String soapAction, final String mep, final String soapVersion, final String wsAddrVersion, final String utUser, final String utPassword, final int httpReadTimeout, final int httpConnTimeout, final String configXMLPath)\n
    invokeWebService(final String serviceName, final String endpointURL, final byte[] payload, final String httpProtocolVersion, final String httpUserName, final String httpPassword, final String soapAction, final String mep, final String soapVersion, final String wsAddrVersion, final String utUser, final String utPassword, final int httpReadTimeout, final int httpConnTimeout, final String configXMLPath, final Map<QName, String> soapHeaderProps, final List<byte[]> soapHeaderData)\n
    invokeWebService(final String serviceName, final String endpointURL, final Document payload, final String httpProtocolVersion, final String httpUserName, final String httpPassword, final String soapAction, final String mep, final String soapVersion, final String wsAddrVersion, final String utUser, final String utPassword, final int httpReadTimeout, final int httpConnTimeout, final String configXMLPath)\n
    '''
