tdbIRI = "String  \"http://jena.hpl.hp.com/#tdb\""
logInfoName = "String  \"com.hp.hpl.jena.tdb.info\""
logLoaderName = "String  \"com.hp.hpl.jena.tdb.loader\""
logExecName = "String  \"com.hp.hpl.jena.tdb.exec\""
namespace = "String  \"http://jena.hpl.hp.com/2008/tdb#\""
PATH = "String  \"com.hp.hpl.jena.tdb\""
NAME = "String  \"TDB\""
