def writeJsonText():
    '''public static void writeJsonText(final Map<?, ?> map, final Appendable out)
    public static void writeJsonText(final Collection<?> collection, final Appendable out)
    public static void writeJsonText(final byte[] array, final Appendable out)
    public static void writeJsonText(final short[] array, final Appendable out)
    public static void writeJsonText(final int[] array, final Appendable out)
    public static void writeJsonText(final long[] array, final Appendable out)
    public static void writeJsonText(final float[] array, final Appendable out)
    public static void writeJsonText(final double[] array, final Appendable out)
    public static void writeJsonText(final boolean[] array, final Appendable out)
    public static void writeJsonText(final char[] array, final Appendable out)
    public static void writeJsonText(final Object[] array, final Appendable out)
    '''
def writeJsonTextAsString():
    '''public static String writeJsonTextAsString(final Map<?, ?> map)
    public static String writeJsonTextAsString(final Collection<?> collection)
    public static String writeJsonTextAsString(final byte[] array)
    public static String writeJsonTextAsString(final short[] array)
    public static String writeJsonTextAsString(final int[] array)
    public static String writeJsonTextAsString(final long[] array)
    public static String writeJsonTextAsString(final float[] array)
    public static String writeJsonTextAsString(final double[] array)
    public static String writeJsonTextAsString(final boolean[] array)
    public static String writeJsonTextAsString(final char[] array)
    public static String writeJsonTextAsString(final Object[] array)
    '''
