def XPath2XMLVisitor():
    '''public XPath2XMLVisitor()
    public XPath2XMLVisitor(final PrintWriter printer)
    '''
def visit():
    '''public void visit(final PathExpr expr)
    public void visit(final LocationPath expr)
    public void visit(final LogicalExpr expr)
    public void visit(final EqualityExpr expr)
    public void visit(final FilterExpr expr)
    public void visit(final RelationalExpr expr)
    public void visit(final AdditiveExpr expr)
    public void visit(final MultiplicativeExpr expr)
    public void visit(final UnaryExpr expr)
    public void visit(final UnionExpr expr)
    public void visit(final NumberExpr expr)
    public void visit(final LiteralExpr expr)
    public void visit(final VariableReferenceExpr expr)
    public void visit(final FunctionCallExpr expr)
    public void visit(final NameStep step)
    public void visit(final ProcessingInstructionNodeStep step)
    public void visit(final AllNodeStep step)
    public void visit(final TextNodeStep step)
    public void visit(final CommentNodeStep step)
    public void visit(final Predicate predicate)
    '''
