OPTION_USE_XMI_TYPE = "String  \"USE_XMI_TYPE\""
VERSION_NAME = "String  \"version\""
VERSION_VALUE = "String  \"2.0\""
XMI_NS = "String  \"xmi\""
XMI_ID = "String  \"id\""
XMI_TAG_NAME = "String  \"XMI\""
XMI_URI = "String  \"http://www.omg.org/XMI\""
