def isNullable():
    '''public boolean isNullable()
    public boolean isNullable()
    public boolean isNullable()
    public boolean isNullable()
    '''
def write():
    '''public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    public void write(final ByteBuffer buffer, final Object o)
    '''
def read():
    '''public Object read(final ByteBuffer buffer)
    public Object read(final ByteBuffer buffer)
    public Object read(final ByteBuffer buffer)
    public Object read(final ByteBuffer buffer)
    public Object read(final ByteBuffer buffer)
    public Object read(final ByteBuffer buffer)
    public String read(final ByteBuffer buffer)
    public String read(final ByteBuffer buffer)
    public Object read(final ByteBuffer buffer)
    public Object read(final ByteBuffer buffer)
    public Records read(final ByteBuffer buffer)
    public Integer read(final ByteBuffer buffer)
    public Long read(final ByteBuffer buffer)
    '''
def sizeOf():
    '''public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    public int sizeOf(final Object o)
    '''
def toString():
    '''public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    '''
def validate():
    '''public Boolean validate(final Object item)
    public Byte validate(final Object item)
    public Short validate(final Object item)
    public Integer validate(final Object item)
    public Long validate(final Object item)
    public Long validate(final Object item)
    public String validate(final Object item)
    public String validate(final Object item)
    public ByteBuffer validate(final Object item)
    public ByteBuffer validate(final Object item)
    public Records validate(final Object item)
    public Integer validate(final Object item)
    public Long validate(final Object item)
    '''
