DEFAULT_BIDI_FORMAT = "String  \"ILYNN\""
TEXT_ORDERING_IMPLICIT = "char  'I'"
TEXT_ORDERING_VISUAL = "char  'V'"
TEXT_ORDERING_DEFAULT = "char  'I'"
TEXT_DIRECTION_LTR = "char  'L'"
TEXT_DIRECTION_RTL = "char  'R'"
TEXT_DIRECTION_CLTR = "char  'C'"
TEXT_DIRECTION_CRTL = "char  'D'"
TEXT_DIRECTION_DEFAULT = "char  'L'"
TEXT_SYM_SWAPPING_OFF = "char  'N'"
TEXT_SYM_SWAPPING_ON = "char  'Y'"
TEXT_SYM_SWAPPING_DEFAULT = "char  'Y'"
TEXT_SHAPING_UNSHAPED = "char  'N'"
TEXT_SHAPING_SHAPED = "char  'S'"
TEXT_SHAPING_ISOLATED = "char  'B'"
TEXT_SHAPING_INTIAL = "char  'I'"
TEXT_SHAPING_MDDLE = "char  'M'"
TEXT_SHAPING_FINAL = "char  'F'"
TEXT_SHAPING_DEFAULT = "char  'N'"
NUMERIC_SHAPING_HINDI = "char  'H'"
NUMERIC_SHAPING_ARABIC = "char  'N'"
NUMERIC_SHAPING_CONTEXTUAL_NATIONAL = "char  'C'"
NUMERIC_SHAPING_CONTEXTUAL_NOMINAL = "char  'T'"
NUMERIC_SHAPING_DEFAULT = "char  'N'"
def isValidBidiFlags():
    '''public static boolean isValidBidiFlags(String flagsStr, final boolean deepValidation)
    '''
