def getValue():
    '''public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    public float getValue(final IlvControlNode ilvControlNode)
    '''
def setValue():
    '''public void setValue(final IlvControlNode ilvControlNode, final float x)
    public void setValue(final IlvControlNode ilvControlNode, final float y)
    public void setValue(final IlvControlNode ilvControlNode, final float width)
    public void setValue(final IlvControlNode ilvControlNode, final float height)
    public void setValue(final IlvControlNode ilvControlNode, final float n)
    public void setValue(final IlvControlNode ilvControlNode, final float n)
    public void setValue(final IlvControlNode ilvControlNode, final float n)
    public void setValue(final IlvControlNode ilvControlNode, final float n)
    public void setValue(final IlvControlNode ilvControlNode, final float n)
    public void setValue(final IlvControlNode ilvControlNode, final float n)
    public void setValue(final IlvControlNode ilvControlNode, final float n)
    public void setValue(final IlvControlNode ilvControlNode, final float n)
    public void setValue(final IlvControlNode ilvControlNode, final float x)
    public void setValue(final IlvControlNode ilvControlNode, final float x)
    public void setValue(final IlvControlNode ilvControlNode, final float x)
    '''
def getComposedAnchors():
    '''public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    public Anchor[] getComposedAnchors(final ComponentOrientation componentOrientation)
    '''
def getDefaultReferenceAnchor():
    '''public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    public Anchor getDefaultReferenceAnchor(final ComponentOrientation componentOrientation)
    '''
def isBIDISensitive():
    '''public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    public boolean isBIDISensitive()
    '''
def toString():
    '''public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    public String toString()
    '''
