COL_ID = "String  \"id\""
COL_RESOURCE = "String  \"CRAFT\""
COL_DESCRIPTION = "String  \"name\""
COL_LOAD = "String  \"load\""
COL_OVERLOAD = "String  \"overload\""
COL_AVAIL = "String  \"avail\""
COL_COMMON = "String  \"common\""
