CURRENT_TIME_CONDITION_KEY = "String  \"aws:CurrentTime\""
SECURE_TRANSPORT_CONDITION_KEY = "String  \"aws:SecureTransport\""
SOURCE_IP_CONDITION_KEY = "String  \"aws:SourceIp\""
USER_AGENT_CONDITION_KEY = "String  \"aws:UserAgent\""
EPOCH_TIME_CONDITION_KEY = "String  \"aws:EpochTime\""
REFERER_CONDITION_KEY = "String  \"aws:Referer\""
SOURCE_ARN_CONDITION_KEY = "String  \"aws:SourceArn\""
