CANNED_ACL_CONDITION_KEY = "String  \"s3:x-amz-acl\""
LOCATION_CONSTRAINT_CONDITION_KEY = "String  \"s3:LocationConstraint\""
PREFIX_CONDITION_KEY = "String  \"s3:prefix\""
DELIMITER_CONDITION_KEY = "String  \"s3:delimiter\""
MAX_KEYS_CONDITION_KEY = "String  \"s3:max-keys\""
COPY_SOURCE_CONDITION_KEY = "String  \"s3:x-amz-copy-source\""
METADATA_DIRECTIVE_CONDITION_KEY = "String  \"s3:x-amz-metadata-directive\""
VERSION_ID_CONDITION_KEY = "String  \"s3:VersionId\""
