EPOCH_NOT_INITIALIZED = "long  -2L"
EPOCH_NO_INFORMATION = "long  -1L"
EPOCH_STANDALONE_MEMBER = "long  0L"
DEFAULT_MAX_BACKUP_CLUSTERS = "int  1"
TYPE_QUIESCE_STATE_CHANGED = "String  \"type.quiesce.state.changed\""
TYPE_SELECTION_DESCRIPTION_MODIFIED = "String  \"type.selection.description.modified\""
