ARTICLE = "int  0"
BODY = "int  1"
GROUP = "int  2"
HEAD = "int  3"
HELP = "int  4"
IHAVE = "int  5"
LAST = "int  6"
LIST = "int  7"
NEWGROUPS = "int  8"
NEWNEWS = "int  9"
NEXT = "int  10"
POST = "int  11"
QUIT = "int  12"
SLAVE = "int  13"
STAT = "int  14"
AUTHINFO = "int  15"
XOVER = "int  16"
XHDR = "int  17"
def getCommand():
    '''public static final String getCommand(final int command)
    '''
