ERROR = "Level  LoggerFactory.getLevel(\"ERROR\")"
WARNING = "Level  LoggerFactory.getLevel(\"WARNING\")"
INFO = "Level  LoggerFactory.getLevel(\"INFO\")"
VERBOSE = "Level  LoggerFactory.getLevel(\"VERBOSE\")"
FINE = "Level  LoggerFactory.getLevel(\"FINE\")"
FINER = "Level  LoggerFactory.getLevel(\"FINER\")"
FINEST = "Level  LoggerFactory.getLevel(\"FINEST\")"
