STATUS_CODE_OK = "int  200"
STATUS_CODE_CREATED = "int  201"
STATUS_CODE_ACCEPTED = "int  202"
STATUS_CODE_NO_CONTENT = "int  204"
STATUS_CODE_MULTIPLE_CHOICES = "int  300"
STATUS_CODE_MOVED_PERMANENTLY = "int  301"
STATUS_CODE_FOUND = "int  302"
STATUS_CODE_SEE_OTHER = "int  303"
STATUS_CODE_NOT_MODIFIED = "int  304"
STATUS_CODE_TEMPORARY_REDIRECT = "int  307"
STATUS_CODE_BAD_REQUEST = "int  400"
STATUS_CODE_UNAUTHORIZED = "int  401"
STATUS_CODE_FORBIDDEN = "int  403"
STATUS_CODE_NOT_FOUND = "int  404"
STATUS_CODE_METHOD_NOT_ALLOWED = "int  405"
STATUS_CODE_CONFLICT = "int  409"
STATUS_CODE_PRECONDITION_FAILED = "int  412"
STATUS_CODE_UNPROCESSABLE_ENTITY = "int  422"
STATUS_CODE_SERVER_ERROR = "int  500"
STATUS_CODE_BAD_GATEWAY = "int  502"
STATUS_CODE_SERVICE_UNAVAILABLE = "int  503"
def isSuccess():
    '''public static boolean isSuccess(final int statusCode)
    '''
def isRedirect():
    '''public static boolean isRedirect(final int statusCode)
    '''
