TABLE_NAME = "String  BIMATTRIBUTEMAPENTRY""
FIELD_BIMATTRIBUTEMAPID = "String  BIMATTRIBUTEMAPID""
FIELD_OBJECTNAME = "String  OBJECTNAME""
FIELD_ATTRIBUTENAME = "String  ATTRIBUTENAME""
FIELD_COBIEATTRIBUTE = "String  COBIEATTRIBUTE""
FIELD_MAXTYPE = "String  MAXTYPE""
FIELD_ISLDOWNER = "String  ISLDOWNER""
def BIMAttributeMapEntry():
'''public BIMAttributeMapEntry(final MboSet ms)
'''
pass
def add():
'''public void add()
'''
pass
