TABLE_NAME = "String  BIMATTRIBUTEMAPLIST""
RELATIONSHIP_BIMATTRIBUTEMAPLIST = "String  BIMATTRIBUTEMAPLIST""
RELATIONSHIP_BIMATTRIBUTEMAP = "String  BIMATTRIBUTEMAP""
FIELD_MAPNAME = "String  MAPNAME""
FIELD_SITEID = "String  SITEID""
FIELD_ORGID = "String  ORGID""
FIELD_BIMPROJECTID = "String  BIMPROJECTID""
FIELD_DESCRIPTION = "String  DESCRIPTION""
def BIMAttributeMapList():
'''public BIMAttributeMapList(final MboSet ms)
'''
pass
def add():
'''public void add()
'''
pass
