TABLE_NAME = "String  \"BIMCONFIGURATION\""
FIELD_ASSETCLASSIFICATIONID = "String  \"ASSETCLASSIFICATIONID\""
FIELD_COMPANYCLASSIFICATIONID = "String  \"COMPANYCLASSIFICATIONID\""
FIELD_FACILITYCLASSIFICATIONID = "String  \"FACILITYCLASSIFICATIONID\""
FIELD_FLOORCLASSIFICATIONID = "String  \"FLOORCLASSIFICATIONID\""
FIELD_ITEMCLASSIFICATIONID = "String  \"ITEMCLASSIFICATIONID\""
FIELD_JPCLASSIFICATIONID = "String  \"JOBPLANCLASSIFICATIONID\""
FIELD_OPERLOCCLASSIFICATIONID = "String  \"OPERLOCCLASSIFICATIONID\""
FIELD_PERSONCLASSIFICATIONID = "String  \"PERSONCLASSIFICATIONID\""
FIELD_PRODUCTCLASSIFICATIONID = "String  \"PRODUCTCLASSIFICATIONID\""
FIELD_SPACECLASSIFICATIONID = "String  \"SPACECLASSIFICATIONID\""
FIELD_SYSTEMCLASSIFICATIONID = "String  \"SYSTEMCLASSIFICATIONID\""
FIELD_ZONECLASSIFICATIONID = "String  \"ZONECLASSIFICATIONID\""
FIELD_PRODUCTSEQ = "String  \"PRODUCTSEQ\""
FIELD_ATTRIBSEQ = "String  \"ATTRIBSEQ\""
def BIMConfiguration():
    '''    public BIMConfiguration(final MboSet ms)
    '''
def add():
    '''    public void add()
    '''
def init():
    '''    public void init()
    '''
