TABLE_NAME = "String  \"BIMCOMMISSION\""
FIELD_BIMCOMMISSIONID = "String  \"BIMCOMMISSIONID\""
FIELD_BIMPROJECTID = "String  \"BIMPROJECTID\""
FIELD_FACILITY = "String  \"FACILITY\""
FIELD_MEMO = "String  \"MEMO\""
FIELD_CURRENTASSETSTATUS = "String  \"CURRENTASSETSTATUS\""
FIELD_NEWASSETSTATUS = "String  \"NEWASSETSTATUS\""
FIELD_AREMOVEFROMACTIVEROUTES = "String  \"AREMOVEFROMACTIVEROUTES\""
FIELD_AREMOVEFROMACTIVESP = "String  \"AREMOVEFROMACTIVESP\""
FIELD_AROLLTOALLCHILDREN = "String  \"AROLLTOALLCHILDREN\""
FIELD_CURRENTLOCSTATUS = "String  \"CURRENTLOCSTATUS\""
FIELD_NEWLOCSTATUS = "String  \"NEWLOCSTATUS\""
FIELD_LREMOVEFROMACTIVESP = "String  \"LREMOVEFROMACTIVESP\""
FIELD_LREMOVEFROMALLJP = "String  \"LREMOVEFROMALLJP\""
FIELD_LREMOVEFROMALLROUTES = "String  \"LREMOVEFROMALLROUTES\""
FIELD_CURRENTJOBPLANSTATUS = "String  \"CURRENTJOBPLANSTATUS\""
FIELD_NEWJOBPLANSTATUS = "String  \"NEWJOBPLANSTATUS\""
FIELD_CURRENTPRODSTATUS = "String  \"CURRENTPRODSTATUS\""
FIELD_NEWPRODSTATUS = "String  \"NEWPRODSTATUS\""
FIELD_CURRENTREQSTATUS = "String  \"CURRENTREQSTATUS\""
FIELD_NEWREQSTATUS = "String  \"NEWREQSTATUS\""
FIELD_CURRENTPMSTATUS = "String  \"CURRENTPMSTATUS\""
FIELD_NEWPMSTATUS = "String  \"NEWPMSTATUS\""
FIELD_UPDATEFACILITY = "String  \"UPDATEFACILITY\""
FIELD_UPDATEFLOORS = "String  \"UPDATEFLOORS\""
FIELD_UPDATESPACE = "String  \"UPDATESPACE\""
FIELD_UPDATEASSET = "String  \"UPDATEASSET\""
FIELD_UPDATEPRODUCT = "String  \"UPDATEPRODUCT\""
FIELD_UPDATEREQ = "String  \"UPDATEREQ\""
FIELD_UPDATEJOBPLAN = "String  \"UPDATEJOBPLAN\""
FIELD_UPDATEPM = "String  \"UPDATEPM\""
def BIMCommission():
    '''public BIMCommission(final MboSet ms)
    '''
def add():
    '''public void add()
    '''
def commision():
    '''public void commision()
    '''
