TABLE_NAME = "String  BIMSESSION""
RELATIONSHIP_PARENT = "String  PARENT""
RELATIONSHIP_FACILITYCLASS = "String  FACILITYCLASS""
DOMAIN_ASSETTYPE = "String  ASSETTYPE""
DOMAIN_BIMATTRIBLOC = "String  BIMATTRIBLOC""
DOMAIN_BIMATTRIBTYPEID = "String  BIMATTRIBTYPEID""
DOMAIN_BIMCOMPONENTID = "String  BIMCOMPONENTID""
DOMAIN_BIMCTCTREATMENT = "String  BIMCTCTREATMENT""
DOMAIN_BIMEXPORTID = "String  BIMEXPORTID""
DOMAIN_BIMPRODUCTSTATUS = "String  BIMPRODUCTSTATUS""
DOMAIN_BIMSESSIONTYPE = "String  BIMSESSIONTYPE""
DOMAIN_BIMFACILITYID = "String  BIMFACILITYID""
DOMAIN_BIMFLOORID = "String  BIMFLOORID""
DOMAIN_BIMOBJECTLEVEL = "String  BIMOBJECTLEVEL""
DOMAIN_BIMOPRLOCID = "String  BIMOPRLOCID""
DOMAIN_BIMSPACEID = "String  BIMSPACEID""
DOMAIN_BIMUNITTREATMENT = "String  BIMUNITTREATMENT""
DOMAIN_BIMWARRANTYCALC = "String  BIMWARRANTYCALC""
DOMAIN_JOBPLANSTATUS = "String  JOBPLANSTATUS""
DOMAIN_BIMUPDATEMODE = "String  BIMUPDATEMODE""
DOMAIN_LOCASSETSTATUS = "String  LOCASSETSTATUS""
FIELD_BIMPROJECTID = "String  BIMPROJECTID""
FIELD_BIMSESSIONID = "String  BIMSESSIONID""
FIELD_FACILITY = "String  FACILITY""
FIELD_SESSIONTYPE = "String  SESSIONTYPE""
FIELD_ATTRIBCREATELEVEL = "String  ATTRIBCREATELEVEL""
FIELD_JPCREATELEVEL = "String  JPCREATELEVEL""
FIELD_ASSETATTRIBLOC = "String  ASSETATTRIBLOC""
FIELD_ASSOCIATEATTRIBUTETYPE = "String  ASSOCIATEATTRIBUTETYPE""
FIELD_ATTRIBTYPEID = "String  ATTRIBTYPEID""
FIELD_AUTONUMBER = "String  AUTONUMBER""
FIELD_BARCODEATTRIB = "String  BARCODEATTRIB""
FIELD_BARCODEASASSETNUM = "String  BARCODEASASSETNUM""
FIELD_CONTACTTREATMENT = "String  CONTACTTREATMENT""
FIELD_CONVERTGUID = "String  CONVERTGUID""
FIELD_CONVERTUNIQUEIDS = "String  CONVERTUNIQUEIDS""
FIELD_DOCDELETEFILES = "String  DOCDELETEFILES""
FIELD_DOCOVERWRITE = "String  DOCOVERWRITE""
FIELD_CHANGEDATEFILTER = "String  CHANGEDATEFILTER""
FIELD_COMPONENTID = "String  COMPONENTID""
FIELD_COPYTYPEATTRIBTOASSETS = "String  COPYTYPEATTRIBTOASSETS""
FIELD_COPYTYPEATTRIBTOITEM = "String  COPYTYPEATTRIBTOITEM""
FIELD_COPYTYPEDOCTOASSET = "String  COPYTYPEDOCTOASSET""
FIELD_CREATECLASSIFICATIONS = "String  CREATECLASSIFICATIONS""
FIELD_CREATEITEMMASTER = "String  CREATEITEMMASTER""
FIELD_CREATEOPERLOC = "String  CREATEOPERLOC""
FIELD_CREATEPRODUCT = "String  CREATEPRODUCT""
FIELD_FACILITYID = "String  FACILITYID""
FIELD_FLOORID = "String  FLOORID""
FIELD_IDSEPCHAR = "String  IDSEPCHAR""
FIELD_INFERLEVELS = "String  INFERLEVELS""
FIELD_INFEROMNICLASS = "String  INFEROMNICLASS""
FIELD_INFERSYSTEMS = "String  INFERSYSTEMS""
FIELD_INITASSETSTATUS = "String  INITASSETSTATUS""
FIELD_INITASSETTYPE = "String  INITASSETTYPE""
FIELD_INITJOBPLANSTATUS = "String  INITJOBPLANSTATUS""
FIELD_INITLOCSTATUS = "String  INITLOCSTATUS""
FIELD_INITPRODSTATUS = "String  INITPRODSTATUS""
FIELD_LEVELATTRIBUTE = "String  LEVELATTRIBUTE""
FIELD_MAPNAME = "String  MAPNAME""
FIELD_TYPEMAPNAME = "String  TYPEMAPNAME""
FIELD_MAPEXTENSIONCOLS = "String  MAPEXTENSIONCOLS""
FIELD_OMNICALSSATTRIBUTE = "String  OMNICALSSATTRIBUTE""
FIELD_OPRLOCID = "String  OPRLOCID""
FIELD_PERSONNAMEISEMAIL = "String  PERSONNAMEISEMAIL""
FIELD_PROJECTADDRESSATTRIBUTE = "String  PROJECTADDRESSATTRIBUTE""
FIELD_POPULATESYSTEMMAP = "String  POPULATESYSTEMMAP""
FIELD_PROMOTECOMPONENTS = "String  PROMOTECOMPONENTS""
FIELD_PROMOTESPACES = "String  PROMOTESPACES""
FIELD_SKIPEMPTYSYS = "String  SKIPEMPTYSYS""
FIELD_SKIPNULL = "String  SKIPNULL""
FIELD_SKIPVALUEISNAME = "String  SKIPVALUEISNAME""
FIELD_SPACEID = "String  SPACEID""
FIELD_SYSTEMATTRIBUTE = "String  SYSTEMATTRIBUTE""
FIELD_TYPESARESPECS = "String  TYPESARESPECS""
FIELD_UNITTREATMENT = "String  UNITTREATMENT""
FIELD_VENDORATTRIBUTE = "String  VENDORATTRIBUTE""
FIELD_WARRANTYCALC = "String  WARRANTYCALC""
FIELD_CREATEATTRIBUTETYPES = "String  CREATEATTRIBUTETYPES""
FIELD_CREATECOMAPNYMASTER = "String  CREATECOMAPNYMASTER""
FIELD_CREATECOMPANIES = "String  CREATECOMPANIES""
FIELD_CREATEMASTERPM = "String  CREATEMASTERPM""
FIELD_CREATEPM = "String  CREATEPM""
FIELD_INFERSPACES = "String  INFERSPACES""
FIELD_SPACEATTRIBUTE = "String  SPACEATTRIBUTE""
FIELD_EXPORTNULLATTRIBUTES = "String  EXPORTNULLATTRIBUTES""
FIELD_FACILITYCLASSIFICATIONID = "String  FACILITYCLASSIFICATIONID""
FIELD_BILLTOADDRESSCODE = "String  BILLTOADDRESSCODE""
FIELD_SERVICEADDRESSCODE = "String  SERVICEADDRESSCODE""
FIELD_SHIPTOADDRESSCODE = "String  SHIPTOADDRESSCODE""
FIELD_GLACCOUNT = "String  GLACCOUNT""
FIELD_AREAMEASURMENT = "String  AREAMEASURMENT""
FIELD_AREAUNITS = "String  AREAUNITS""
FIELD_CURRENCYCODE = "String  CURRENCYCODE""
FIELD_FACILITYNAME = "String  FACILITYNAME""
FIELD_LINEARUNITS = "String  LINEARUNITS""
FIELD_PROJECTNAME = "String  PROJECTNAME""
FIELD_PROJECTDESC = "String  PROJECTDESC""
FIELD_PHASE = "String  PHASE""
FIELD_PROJECTTIMESTAMP = "String  PROJECTTIMESTAMP""
FIELD_SITEDESC = "String  SITEDESC""
FIELD_SITENAME = "String  SITENAME""
FIELD_VOLUMEUNITS = "String  VOLUMEUNITS""
FIELD_UPDATEMODE = "String  UPDATEMODE""
FIELD_UPDATECATEGORY = "String  UPDATECATEGORY""
FIELD_UPDATEATTRIBUTES = "String  UPDATEATTRIBUTES""
FIELD_DELETESYSTEMMEMBERS = "String  DELETESYSTEMMEMBERS""
FIELD_TARGETFACILITY = "String  TARGETFACILITY""
FIELD_MERGEFACILITY = "String  MERGEFACILITY""
FIELD_EXPORTFLOOR = "String  EXPORTFLOOR""
FIELD_EXPORTSPACE = "String  EXPORTSPACE""
FIELD_EXPORTCOMPONENT = "String  EXPORTCOMPONENT""
FIELD_EXPORTTYPE = "String  EXPORTTYPE""
FIELD_EXPORTSYSTEM = "String  EXPORTSYSTEM""
FIELD_EXPORTZONE = "String  EXPORTZONE""
FIELD_EXPORTATTRIBUTE = "String  EXPORTATTRIBUTE""
FIELD_EXPORTCONTACT = "String  EXPORTCONTACT""
FIELD_EXPORTDOCUMENT = "String  EXPORTDOCUMENT""
FIELD_EXPORTJOB = "String  EXPORTJOB""
FIELD_EXPORTRESOURCE = "String  EXPORTRESOURCE""
FIELD_EXPORTSPARE = "String  EXPORTSPARE""
FIELD_EXPORTASSEMBLY = "String  EXPORTASSEMBLY""
FIELD_EXPORTID = "String  EXPORTID""
ATTRIB_LOC_OPPER_LOC = "long  1L"
ATTRIB_LOC_ASSET = "long  2L"
CONTACT_PERSON = "int  1"
CONTACT_USE = "int  2"
CONTACT_BOTH = "int  3"
CONTACT_COMPANY = "int  4"
EXPORTID_IFC = "int  1"
EXPORTID_MAXIMO = "int  2"
EXPORTID_BOTH = "int  3"
SESSION_TYPE_UNKNOWN = "int  0"
SESSION_TYPE_VALIDATE = "int  1"
SESSION_TYPE_IMPORT = "int  2"
SESSION_TYPE_UPDATE = "int  3"
SESSION_TYPE_EXPORT = "int  5"
SESSION_TYPE_MERGE = "int  6"
ATTRIB_TYPE_ID_AUTOKEY = "int  1"
ATTRIB_TYPE_ID_IMPORT = "int  2"
ATTRIB_TYPE_ID_NAME = "int  3"
ATTRIB_TYPE_ID_TRUNCATE = "int  4"
FACILITY_ID_AUTOKEY = "int  1"
FACILITY_ID_IMPORT = "int  2"
FACILITY_ID_PREFIX = "int  3"
FACILITY_ID_NAME = "int  4"
FLOOR_ID_AUTOKEY = "int  1"
FLOOR_ID_IMPORT = "int  2"
FLOOR_ID_PREFIXTAG = "int  3"
FLOOR_ID_TAG = "int  4"
FLOOR_ID_NAME = "int  5"
FLOOR_ID_PREFIXNAME = "int  6"
SPACE_ID_AUTOKEY = "int  1"
SPACE_ID_IMPORT = "int  2"
SPACE_ID_PREFIXTAG = "int  3"
SPACE_ID_TAG = "int  4"
SPACE_ID_NAME = "int  5"
SPACE_ID_PREFIXNAME = "int  6"
SPACE_ID_PREFIXFLOORNAME = "int  7"
OPRLOC_ID_AUTOKEY = "int  1"
OPRLOC_ID_IMPORT = "int  2"
OPRLOC_ID_ASSET = "int  3"
COMPONENT_ID_AUTOKEY = "int  1"
COMPONENT_ID_IMPORT = "int  2"
COMPONENT_ID_BARCODE = "int  3"
COMPONENT_ID_NAME = "int  4"
COMPONENT_ID_PREFIXBAR = "int  5"
COMPONENT_ID_PREFIXNAME = "int  6"
OBJETLEVEL_SYSTEM = "int  1"
OBJETLEVEL_ORG = "int  2"
OBJETLEVEL_SITE = "int  3"
UNITS_LAX = "int  1"
UNITS_IMPORT = "int  2"
UNITS_ENFORCE = "int  3"
UPDATE_VALIDATE_ONLY = "int  1"
UPDATE_INCREMENTAL = "int  2"
UPDATE_BLANKONLY = "int  3"
UPDATE_TIMESTAMP = "int  4"
UPDATE_OVERWRITE = "int  5"
WARRANTY_NONE = "int  0"
WARRANTY_PARTS = "int  1"
WARRANTY_LABOR = "int  2"
WARRANTY_SHORT = "int  3"
WARRANTY_LONG = "int  4"
def BIMSession():
'''public BIMSession(final MboSet ms)
'''
pass
def add():
'''public void add()
'''
pass
def init():
'''public void init()
'''
pass
def delete():
'''public void delete(final long accessModifier)
'''
pass
def cleanUploadDir():
'''public void cleanUploadDir()
'''
pass
def exportToCOBie():
'''public void exportToCOBie()
'''
pass
def getInitialAssetStatus():
'''public String getInitialAssetStatus()
'''
pass
def getInitialAssetType():
'''public String getInitialAssetType()
'''
pass
def getInitialJobPlanStatus():
'''public String getInitialJobPlanStatus()
'''
pass
def getInitialLocationStatus():
'''public String getInitialLocationStatus()
'''
pass
def getInitialProductStatus():
'''public String getInitialProductStatus()
'''
pass
def getComponentAttributeLocation():
'''public long getComponentAttributeLocation()
'''
pass
def getContactTreatment():
'''public int getContactTreatment()
'''
pass
def getExportIdType():
'''public int getExportIdType()
'''
pass
def getSessionType():
'''public int getSessionType()
public int getSessionType(String sessionType)
'''
pass
def getAttribTypeIdCalc():
'''public int getAttribTypeIdCalc()
'''
pass
def getFacilityrIdCalc():
'''public int getFacilityrIdCalc()
'''
pass
def getFloorIdCalc():
'''public int getFloorIdCalc()
'''
pass
def getSpaceIdCalc():
'''public int getSpaceIdCalc()
'''
pass
def getOperatingLocIdCalc():
'''public int getOperatingLocIdCalc()
'''
pass
def getComponentIdCalc():
'''public int getComponentIdCalc()
'''
pass
def getObjectLevel():
'''public int getObjectLevel(final String objectName)
'''
pass
def getUnitTreatment():
'''public int getUnitTreatment()
'''
pass
def getUpdateBehavior():
'''public int getUpdateBehavior()
'''
pass
def getWarrantyCalcMethod():
'''public int getWarrantyCalcMethod()
'''
pass
def setOptionsReadOnly():
'''public void setOptionsReadOnly()
'''
pass
def getUploadDirectory():
'''public String getUploadDirectory()
'''
pass
def setWriteStatusForFacilityFields():
'''public void setWriteStatusForFacilityFields(final boolean status)
'''
pass
