TABLE_NAME = "String  \"BIMUPLOAD\""
DOMAIN_COBIESHEETTYPE = "String  \"COBIESHEETTYPE\""
FIELD_BIMSESSIONID = "String  \"BIMSESSIONID\""
FIELD_COBIESHEET = "String  \"COBIESHEET\""
FIELD_FILENAME = "String  \"FILENAME\""
FIELD_SOURCEFILENAME = "String  \"SOURCEFILENAME\""
FIELD_IMPORTFACILITY = "String  \"IMPORTFACILITY\""
FIELD_IMPORTFLOOR = "String  \"IMPORTFLOOR\""
FIELD_IMPORTSPACE = "String  \"IMPORTSPACE\""
FIELD_IMPORTCOMPONENT = "String  \"IMPORTCOMPONENT\""
FIELD_IMPORTTYPE = "String  \"IMPORTTYPE\""
FIELD_IMPORTSYSTEM = "String  \"IMPORTSYSTEM\""
FIELD_IMPORTZONE = "String  \"IMPORTZONE\""
FIELD_IMPORTATTRIBUTE = "String  \"IMPORTATTRIBUTE\""
FIELD_IMPORTCONTACT = "String  \"IMPORTCONTACT\""
FIELD_IMPORTDOCUMENT = "String  \"IMPORTDOCUMENT\""
FIELD_IMPORTJOB = "String  \"IMPORTJOB\""
FIELD_IMPORTRESOURCE = "String  \"IMPORTRESOURCE\""
FIELD_IMPORTSPARES = "String  \"IMPORTSPARES\""
FIELD_IMPORTASSEMBLY = "String  \"IMPORTASSEMBLY\""
def BIMUpload():
    '''public BIMUpload(final MboSet ms)
    '''
def add():
    '''public void add()
    '''
def getFileName():
    '''public String getFileName()
    '''
def getSheetName():
    '''public String getSheetName()
    '''
