def getPropertyUsingCaseSensitiveName():
    '''returns BeanPropertyInformation\n\n
    getPropertyUsingCaseSensitiveName(final String s)\n
    '''
def getPropertyUsingCaseInSensitiveName():
    '''returns BeanPropertyInformation\n\n
    getPropertyUsingCaseInSensitiveName(final String s, final String s2)\n
    '''
def mapPropertiesByTableColumnName():
    '''returns None\n\n
    mapPropertiesByTableColumnName()\n
    '''
def ():
    '''returns BeanInformation\n\n
    (final Map<String, BeanPropertyInformation> beanPropertyMap_)\n
    (final String nameFullyQualified_)\n
    '''
def toString():
    '''returns String\n\n
    toString()\n
    '''
def setBeanPropertyMap():
    '''returns None\n\n
    setBeanPropertyMap(final Map<String, BeanPropertyInformation> beanPropertyMap_)\n
    '''
def getAutoGenColumnNames():
    '''returns String[]\n\n
    getAutoGenColumnNames()\n
    '''
def setAutoGenColumnNames():
    '''returns None\n\n
    setAutoGenColumnNames(final String[] autoGeneratedColumns_)\n
    '''
def addBeanPropertyMap():
    '''returns None\n\n
    addBeanPropertyMap(final String s, final BeanPropertyInformation beanPropertyInformation)\n
    '''
def getParameterWrapperForGetMethod():
    '''returns String\n\n
    getParameterWrapperForGetMethod()\n
    '''
def setParameterWrapperForGetMethod():
    '''returns None\n\n
    setParameterWrapperForGetMethod(final String parameterWrapperForGet_)\n
    '''
def getParameterWrapperForSetMethod():
    '''returns String\n\n
    getParameterWrapperForSetMethod()\n
    '''
def setParameterWrapperForSetMethod():
    '''returns None\n\n
    setParameterWrapperForSetMethod(final String parameterWrapperForSet_)\n
    '''
def getAutoGeneratedKeys():
    '''returns List<String>\n\n
    getAutoGeneratedKeys()\n
    '''
def addAutoGeneratedKeys():
    '''returns None\n\n
    addAutoGeneratedKeys(final String s)\n
    '''
def getIdKeys():
    '''returns List<BeanPropertyInformation>\n\n
    getIdKeys()\n
    '''
def addIdKeys():
    '''returns None\n\n
    addIdKeys(final BeanPropertyInformation beanPropertyInformation)\n
    '''
def setIdKeys():
    '''returns None\n\n
    setIdKeys(final List<BeanPropertyInformation> idKeys_)\n
    '''
def getBeanInteritanceList():
    '''returns List<String>\n\n
    getBeanInteritanceList()\n
    '''
def setBeanInteritanceList():
    '''returns None\n\n
    setBeanInteritanceList(final LinkedList<String> beanInteritanceList_)\n
    '''
def getGenericSetWithParamsMethod():
    '''returns Method\n\n
    getGenericSetWithParamsMethod()\n
    '''
def setGenericSetWithParamsMethod():
    '''returns None\n\n
    setGenericSetWithParamsMethod(final Method genericSetWithParamsMethod_)\n
    '''
def getGenericSetMethod():
    '''returns Method\n\n
    getGenericSetMethod()\n
    '''
def setGenericSetMethod():
    '''returns None\n\n
    setGenericSetMethod(final Method genericSetMethod_)\n
    '''
def getFullyQualifiedName():
    '''returns String\n\n
    getFullyQualifiedName()\n
    '''
def hasGenericSetWithParamsMethod():
    '''returns boolean\n\n
    hasGenericSetWithParamsMethod()\n
    '''
def setHasGenericSetWithParamsMethod():
    '''returns None\n\n
    setHasGenericSetWithParamsMethod(final boolean hasGenericSetWithParamsMethod_)\n
    '''
def addAutoGeneratedKeysTable():
    '''returns None\n\n
    addAutoGeneratedKeysTable(final String s)\n
    '''
def getAutoGeneratedKeysTable():
    '''returns List<String>\n\n
    getAutoGeneratedKeysTable()\n
    '''
def addIdKeysTable():
    '''returns None\n\n
    addIdKeysTable(final String s)\n
    '''
def getIdKeysTable():
    '''returns List<String>\n\n
    getIdKeysTable()\n
    '''
def getTableNameAnnotation():
    '''returns String\n\n
    getTableNameAnnotation()\n
    '''
def setTableNameAnnotation():
    '''returns None\n\n
    setTableNameAnnotation(final String tableNameAnnotation_)\n
    '''
def isNestedBean():
    '''returns boolean\n\n
    isNestedBean()\n
    '''
def setNestedBean():
    '''returns None\n\n
    setNestedBean(final boolean nestedBean_)\n
    '''
def getJoinPointProperties():
    '''returns List<BeanPropertyInformation>\n\n
    getJoinPointProperties()\n
    '''
def getBeanClass():
    '''returns Class\n\n
    getBeanClass()\n
    '''
def setBeanClass():
    '''returns None\n\n
    setBeanClass(final Class beanClass_)\n
    '''
def clone():
    '''returns Object\n\n
    clone()\n
    '''
def getPropertyByTablecolumn():
    '''returns BeanPropertyInformation\n\n
    getPropertyByTablecolumn(final String s, final String str)\n
    '''
