IC_NOTAPPLY = "String IC.notapply""
IC_CANCEL = "String IC.cancel""
IC_CHECK = "String IC.check""
IC_CHECKDONE = "String IC.checkdone""
IC_REPORT = "String IC.report""
IC_TENANT = "String IC.tenant""
IC_ALLREPAIRS = "String IC.allrepairs""
IC_REPAIR = "String IC.repair""
