HOUR = "String  \"hourFormat\""
GMT = "String  \"gmtFormat\""
REGION_FORMAT = "String  \"regionFormat\""
FALLBACK_FORMAT = "String  \"fallbackFormat\""
ZONE_STRINGS = "String  \"zoneStrings\""
FORWARD_SLASH = "String  \"/\""
