def visit():
    '''returns Object\n\n
    visit(final AnyTypePattern node, final Object data)\n
    visit(final NoTypePattern node, final Object data)\n
    visit(final EllipsisTypePattern node, final Object data)\n
    visit(final AnyWithAnnotationTypePattern node, final Object data)\n
    visit(final AnyAnnotationTypePattern node, final Object data)\n
    visit(final EllipsisAnnotationTypePattern node, final Object data)\n
    visit(final AndAnnotationTypePattern node, final Object data)\n
    visit(final AndPointcut node, final Object data)\n
    visit(final AndTypePattern node, final Object data)\n
    visit(final AnnotationPatternList node, final Object data)\n
    visit(final AnnotationPointcut node, final Object data)\n
    visit(final ArgsAnnotationPointcut node, final Object data)\n
    visit(final ArgsPointcut node, final Object data)\n
    visit(final BindingAnnotationTypePattern node, final Object data)\n
    visit(final BindingTypePattern node, final Object data)\n
    visit(final CflowPointcut node, final Object data)\n
    visit(final ConcreteCflowPointcut node, final Object data)\n
    visit(final DeclareAnnotation node, final Object data)\n
    visit(final DeclareErrorOrWarning node, final Object data)\n
    visit(final DeclareParents node, final Object data)\n
    visit(final DeclarePrecedence node, final Object data)\n
    visit(final DeclareSoft node, final Object data)\n
    visit(final ExactAnnotationTypePattern node, final Object data)\n
    visit(final ExactTypePattern node, final Object data)\n
    visit(final HandlerPointcut node, final Object data)\n
    visit(final IfPointcut node, final Object data)\n
    visit(final KindedPointcut node, final Object data)\n
    visit(final ModifiersPattern node, final Object data)\n
    visit(final NamePattern node, final Object data)\n
    visit(final NotAnnotationTypePattern node, final Object data)\n
    visit(final NotPointcut node, final Object data)\n
    visit(final NotTypePattern node, final Object data)\n
    visit(final OrAnnotationTypePattern node, final Object data)\n
    visit(final OrPointcut node, final Object data)\n
    visit(final OrTypePattern node, final Object data)\n
    visit(final PerCflow node, final Object data)\n
    visit(final PerFromSuper node, final Object data)\n
    visit(final PerObject node, final Object data)\n
    visit(final PerSingleton node, final Object data)\n
    visit(final PerTypeWithin node, final Object data)\n
    visit(final PatternNode node, final Object data)\n
    visit(final ReferencePointcut node, final Object data)\n
    visit(final SignaturePattern node, final Object data)\n
    visit(final ThisOrTargetAnnotationPointcut node, final Object data)\n
    visit(final ThisOrTargetPointcut node, final Object data)\n
    visit(final ThrowsPattern node, final Object data)\n
    visit(final TypePatternList node, final Object data)\n
    visit(final WildAnnotationTypePattern node, final Object data)\n
    visit(final WildTypePattern node, final Object data)\n
    visit(final WithinAnnotationPointcut node, final Object data)\n
    visit(final WithinCodeAnnotationPointcut node, final Object data)\n
    visit(final WithinPointcut node, final Object data)\n
    visit(final WithincodePointcut node, final Object data)\n
    visit(final Pointcut.MatchesNothingPointcut node, final Object data)\n
    visit(final TypeVariablePattern node, final Object data)\n
    visit(final TypeVariablePatternList node, final Object data)\n
    visit(final HasMemberTypePattern node, final Object data)\n
    visit(final TypeCategoryTypePattern node, final Object data)\n
    '''
