type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(STFontCollectionIndex.class.getClassLoader(), \"schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2\").resolveHandle(\"stfontcollectionindex6766type\")"
MAJOR = "Enum  Enum.forString(\"major\")"
MINOR = "Enum  Enum.forString(\"minor\")"
NONE = "Enum  Enum.forString(\"none\")"
INT_MAJOR = "int  1"
INT_MINOR = "int  2"
INT_NONE = "int  3"
