type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(STPathShadeType.class.getClassLoader(), \"schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2\").resolveHandle(\"stpathshadetype93c3type\")"
SHAPE = "Enum  Enum.forString(\"shape\")"
CIRCLE = "Enum  Enum.forString(\"circle\")"
RECT = "Enum  Enum.forString(\"rect\")"
INT_SHAPE = "int  1"
INT_CIRCLE = "int  2"
INT_RECT = "int  3"
