type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(STTextWrappingType.class.getClassLoader(), \"schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2\").resolveHandle(\"sttextwrappingtype4b4etype\")"
NONE = "Enum  Enum.forString(\"none\")"
SQUARE = "Enum  Enum.forString(\"square\")"
INT_NONE = "int  1"
INT_SQUARE = "int  2"
