type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(STTextStrikeType.class.getClassLoader(), \"schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2\").resolveHandle(\"sttextstriketype4744type\")"
NO_STRIKE = "Enum  Enum.forString(\"noStrike\")"
SNG_STRIKE = "Enum  Enum.forString(\"sngStrike\")"
DBL_STRIKE = "Enum  Enum.forString(\"dblStrike\")"
INT_NO_STRIKE = "int  1"
INT_SNG_STRIKE = "int  2"
INT_DBL_STRIKE = "int  3"
