type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(STTextHorzOverflowType.class.getClassLoader(), \"schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2\").resolveHandle(\"sttexthorzoverflowtype6003type\")"
OVERFLOW = "Enum  Enum.forString(\"overflow\")"
CLIP = "Enum  Enum.forString(\"clip\")"
INT_OVERFLOW = "int  1"
INT_CLIP = "int  2"
