type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(Uri.class.getClassLoader(), \"schemaorg_apache_xmlbeans.system.s8C3F193EE11A2F798ACF65489B9E6078\").resolveHandle(\"uribad9attrtype\")"
HTTP_SCHEMAS_MICROSOFT_COM_OFFICE_2006_KEY_ENCRYPTOR_PASSWORD = "Enum  Enum.forString(\"http://schemas.microsoft.com/office/2006/keyEncryptor/password\")"
HTTP_SCHEMAS_MICROSOFT_COM_OFFICE_2006_KEY_ENCRYPTOR_CERTIFICATE = "Enum  Enum.forString(\"http://schemas.microsoft.com/office/2006/keyEncryptor/certificate\")"
INT_HTTP_SCHEMAS_MICROSOFT_COM_OFFICE_2006_KEY_ENCRYPTOR_PASSWORD = "int  1"
INT_HTTP_SCHEMAS_MICROSOFT_COM_OFFICE_2006_KEY_ENCRYPTOR_CERTIFICATE = "int  2"
