type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(STCipherChaining.class.getClassLoader(), \"schemaorg_apache_xmlbeans.system.s8C3F193EE11A2F798ACF65489B9E6078\").resolveHandle(\"stcipherchaining1e98type\")"
CHAINING_MODE_CBC = "Enum  Enum.forString(\"ChainingModeCBC\")"
CHAINING_MODE_CFB = "Enum  Enum.forString(\"ChainingModeCFB\")"
INT_CHAINING_MODE_CBC = "int  1"
INT_CHAINING_MODE_CFB = "int  2"
