type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((Attribute$1.class$org$apache$xmlbeans$impl$xb$xsdschema$Attribute$Use == null) ? (Attribute$1.class$org$apache$xmlbeans$impl$xb$xsdschema$Attribute$Use = Attribute$1.class$(\"org.apache.xmlbeans.impl.xb.xsdschema.Attribute$Use\")) : Attribute$1.class$org$apache$xmlbeans$impl$xb$xsdschema$Attribute$Use).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLSCHEMA\").resolveHandle(\"usea41aattrtype\")"
PROHIBITED = "Enum  Enum.forString(\"prohibited\")"
OPTIONAL = "Enum  Enum.forString(\"optional\")"
REQUIRED = "Enum  Enum.forString(\"required\")"
INT_PROHIBITED = "int  1"
INT_OPTIONAL = "int  2"
INT_REQUIRED = "int  3"
