type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((BlockSet$1.class$org$apache$xmlbeans$impl$xb$xsdschema$BlockSet$Member2$Item == null) ? (BlockSet$1.class$org$apache$xmlbeans$impl$xb$xsdschema$BlockSet$Member2$Item = BlockSet$1.class$(\"org.apache.xmlbeans.impl.xb.xsdschema.BlockSet$Member2$Item\")) : BlockSet$1.class$org$apache$xmlbeans$impl$xb$xsdschema$BlockSet$Member2$Item).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLSCHEMA\").resolveHandle(\"anon421ctype\")"
ALL = "Enum  Enum.forString(\"#all\")"
INT_ALL = "int  1"
EXTENSION = "Enum  DerivationControl.EXTENSION"
RESTRICTION = "Enum  DerivationControl.RESTRICTION"
SUBSTITUTION = "Enum  DerivationControl.SUBSTITUTION"
INT_EXTENSION = "int  2"
INT_RESTRICTION = "int  3"
INT_SUBSTITUTION = "int  1"
