type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((DerivationControl$1.class$org$apache$xmlbeans$impl$xb$xsdschema$DerivationControl == null) ? (DerivationControl$1.class$org$apache$xmlbeans$impl$xb$xsdschema$DerivationControl = DerivationControl$1.class$(\"org.apache.xmlbeans.impl.xb.xsdschema.DerivationControl\")) : DerivationControl$1.class$org$apache$xmlbeans$impl$xb$xsdschema$DerivationControl).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLSCHEMA\").resolveHandle(\"derivationcontrola5dftype\")"
SUBSTITUTION = "Enum  Enum.forString(\"substitution\")"
EXTENSION = "Enum  Enum.forString(\"extension\")"
RESTRICTION = "Enum  Enum.forString(\"restriction\")"
LIST = "Enum  Enum.forString(\"list\")"
UNION = "Enum  Enum.forString(\"union\")"
INT_SUBSTITUTION = "int  1"
INT_EXTENSION = "int  2"
INT_RESTRICTION = "int  3"
INT_LIST = "int  4"
INT_UNION = "int  5"
