type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((NamespaceList$1.class$org$apache$xmlbeans$impl$xb$xsdschema$NamespaceList$Member2$Item$Member == null) ? (NamespaceList$1.class$org$apache$xmlbeans$impl$xb$xsdschema$NamespaceList$Member2$Item$Member = NamespaceList$1.class$(\"org.apache.xmlbeans.impl.xb.xsdschema.NamespaceList$Member2$Item$Member\")) : NamespaceList$1.class$org$apache$xmlbeans$impl$xb$xsdschema$NamespaceList$Member2$Item$Member).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLSCHEMA\").resolveHandle(\"anon0c73type\")"
ANY = "Enum  Enum.forString(\"##any\")"
OTHER = "Enum  Enum.forString(\"##other\")"
INT_ANY = "int  1"
INT_OTHER = "int  2"
TARGET_NAMESPACE = "Enum  Enum.forString(\"##targetNamespace\")"
LOCAL = "Enum  Enum.forString(\"##local\")"
INT_TARGET_NAMESPACE = "int  1"
INT_LOCAL = "int  2"
