type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((SimpleDerivationSet$1.class$org$apache$xmlbeans$impl$xb$xsdschema$SimpleDerivationSet$Member2$Item == null) ? (SimpleDerivationSet$1.class$org$apache$xmlbeans$impl$xb$xsdschema$SimpleDerivationSet$Member2$Item = SimpleDerivationSet$1.class$(\"org.apache.xmlbeans.impl.xb.xsdschema.SimpleDerivationSet$Member2$Item\")) : SimpleDerivationSet$1.class$org$apache$xmlbeans$impl$xb$xsdschema$SimpleDerivationSet$Member2$Item).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLSCHEMA\").resolveHandle(\"anonf38etype\")"
ALL = "Enum  Enum.forString(\"#all\")"
INT_ALL = "int  1"
LIST = "Enum  DerivationControl.LIST"
UNION = "Enum  DerivationControl.UNION"
RESTRICTION = "Enum  DerivationControl.RESTRICTION"
INT_LIST = "int  4"
INT_UNION = "int  5"
INT_RESTRICTION = "int  3"
