type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((TypeDerivationControl$1.class$org$apache$xmlbeans$impl$xb$xsdschema$TypeDerivationControl == null) ? (TypeDerivationControl$1.class$org$apache$xmlbeans$impl$xb$xsdschema$TypeDerivationControl = TypeDerivationControl$1.class$(\"org.apache.xmlbeans.impl.xb.xsdschema.TypeDerivationControl\")) : TypeDerivationControl$1.class$org$apache$xmlbeans$impl$xb$xsdschema$TypeDerivationControl).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLSCHEMA\").resolveHandle(\"typederivationcontrol3239type\")"
EXTENSION = "Enum  DerivationControl.EXTENSION"
RESTRICTION = "Enum  DerivationControl.RESTRICTION"
LIST = "Enum  DerivationControl.LIST"
UNION = "Enum  DerivationControl.UNION"
INT_EXTENSION = "int  2"
INT_RESTRICTION = "int  3"
INT_LIST = "int  4"
INT_UNION = "int  5"
