type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((Wildcard$1.class$org$apache$xmlbeans$impl$xb$xsdschema$Wildcard$ProcessContents == null) ? (Wildcard$1.class$org$apache$xmlbeans$impl$xb$xsdschema$Wildcard$ProcessContents = Wildcard$1.class$(\"org.apache.xmlbeans.impl.xb.xsdschema.Wildcard$ProcessContents\")) : Wildcard$1.class$org$apache$xmlbeans$impl$xb$xsdschema$Wildcard$ProcessContents).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLSCHEMA\").resolveHandle(\"processcontents864aattrtype\")"
SKIP = "Enum  Enum.forString(\"skip\")"
LAX = "Enum  Enum.forString(\"lax\")"
STRICT = "Enum  Enum.forString(\"strict\")"
INT_SKIP = "int  1"
INT_LAX = "int  2"
INT_STRICT = "int  3"
