HELO = "int  0"
MAIL = "int  1"
RCPT = "int  2"
DATA = "int  3"
SEND = "int  4"
SOML = "int  5"
SAML = "int  6"
RSET = "int  7"
VRFY = "int  8"
EXPN = "int  9"
HELP = "int  10"
NOOP = "int  11"
TURN = "int  12"
QUIT = "int  13"
HELLO = "int  0"
LOGIN = "int  0"
MAIL_FROM = "int  1"
RECIPIENT = "int  2"
SEND_MESSAGE_DATA = "int  3"
SEND_FROM = "int  4"
SEND_OR_MAIL_FROM = "int  5"
SEND_AND_MAIL_FROM = "int  6"
RESET = "int  7"
VERIFY = "int  8"
EXPAND = "int  9"
LOGOUT = "int  13"
def getCommand():
    '''    public static final String getCommand(final int command)
    '''
