ABBREV = "String  \"ABBREV\""
ALTREP = "String  \"ALTREP\""
CN = "String  \"CN\""
CUTYPE = "String  \"CUTYPE\""
DELEGATED_FROM = "String  \"DELEGATED-FROM\""
DELEGATED_TO = "String  \"DELEGATED-TO\""
DIR = "String  \"DIR\""
ENCODING = "String  \"ENCODING\""
FMTTYPE = "String  \"FMTTYPE\""
FBTYPE = "String  \"FBTYPE\""
LANGUAGE = "String  \"LANGUAGE\""
MEMBER = "String  \"MEMBER\""
PARTSTAT = "String  \"PARTSTAT\""
RANGE = "String  \"RANGE\""
RELATED = "String  \"RELATED\""
RELTYPE = "String  \"RELTYPE\""
ROLE = "String  \"ROLE\""
RSVP = "String  \"RSVP\""
SCHEDULE_AGENT = "String  \"SCHEDULE-AGENT\""
SCHEDULE_STATUS = "String  \"SCHEDULE-STATUS\""
SENT_BY = "String  \"SENT-BY\""
TYPE = "String  \"TYPE\""
TZID = "String  \"TZID\""
VALUE = "String  \"VALUE\""
VVENUE = "String  \"VVENUE\""
EXPERIMENTAL_PREFIX = "String  \"X-\""
def ():
    '''returns Parameter\n\n
    (final String aName, final ParameterFactory factory)\n
    '''
