PRODID = "String  \"PRODID\""
VERSION = "String  \"VERSION\""
CALSCALE = "String  \"CALSCALE\""
METHOD = "String  \"METHOD\""
BUSYTYPE = "String  \"BUSYTYPE\""
CLASS = "String  \"CLASS\""
CREATED = "String  \"CREATED\""
DESCRIPTION = "String  \"DESCRIPTION\""
DTSTART = "String  \"DTSTART\""
GEO = "String  \"GEO\""
LAST_MODIFIED = "String  \"LAST-MODIFIED\""
LOCATION = "String  \"LOCATION\""
ORGANIZER = "String  \"ORGANIZER\""
PERCENT_COMPLETE = "String  \"PERCENT-COMPLETE\""
PRIORITY = "String  \"PRIORITY\""
DTSTAMP = "String  \"DTSTAMP\""
SEQUENCE = "String  \"SEQUENCE\""
STATUS = "String  \"STATUS\""
SUMMARY = "String  \"SUMMARY\""
TRANSP = "String  \"TRANSP\""
UID = "String  \"UID\""
URL = "String  \"URL\""
RECURRENCE_ID = "String  \"RECURRENCE-ID\""
COMPLETED = "String  \"COMPLETED\""
DUE = "String  \"DUE\""
FREEBUSY = "String  \"FREEBUSY\""
TZID = "String  \"TZID\""
TZNAME = "String  \"TZNAME\""
TZOFFSETFROM = "String  \"TZOFFSETFROM\""
TZOFFSETTO = "String  \"TZOFFSETTO\""
TZURL = "String  \"TZURL\""
ACTION = "String  \"ACTION\""
REPEAT = "String  \"REPEAT\""
TRIGGER = "String  \"TRIGGER\""
REQUEST_STATUS = "String  \"REQUEST-STATUS\""
DTEND = "String  \"DTEND\""
DURATION = "String  \"DURATION\""
ATTACH = "String  \"ATTACH\""
ATTENDEE = "String  \"ATTENDEE\""
CATEGORIES = "String  \"CATEGORIES\""
COMMENT = "String  \"COMMENT\""
CONTACT = "String  \"CONTACT\""
EXDATE = "String  \"EXDATE\""
EXRULE = "String  \"EXRULE\""
RELATED_TO = "String  \"RELATED-TO\""
RESOURCES = "String  \"RESOURCES\""
RDATE = "String  \"RDATE\""
RRULE = "String  \"RRULE\""
EXPERIMENTAL_PREFIX = "String  \"X-\""
COUNTRY = "String  \"COUNTRY\""
EXTENDED_ADDRESS = "String  \"EXTENDED-ADDRESS\""
LOCALITY = "String  \"LOCALITY\""
LOCATION_TYPE = "String  \"LOCATION-TYPE\""
NAME = "String  \"NAME\""
POSTALCODE = "String  \"POSTAL-CODE\""
REGION = "String  \"REGION\""
STREET_ADDRESS = "String  \"STREET-ADDRESS\""
TEL = "String  \"TEL\""
ACKNOWLEDGED = "String  \"ACKNOWLEDGED\""
def hashCode():
    '''returns int\n\n
    hashCode()\n
    '''
def copy():
    '''returns Property\n\n
    copy()\n
    '''
