type = "SchemaType  (SchemaType)XmlBeans.typeSystemForClassLoader(((SpaceAttribute$1.class$org$apache$xmlbeans$impl$xb$xmlschema$SpaceAttribute$Space == null) ? (SpaceAttribute$1.class$org$apache$xmlbeans$impl$xb$xmlschema$SpaceAttribute$Space = SpaceAttribute$1.class$(\"org.apache.xmlbeans.impl.xb.xmlschema.SpaceAttribute$Space\")) : SpaceAttribute$1.class$org$apache$xmlbeans$impl$xb$xmlschema$SpaceAttribute$Space).getClassLoader(), \"schemaorg_apache_xmlbeans.system.sXMLLANG\").resolveHandle(\"spaceb986attrtype\")"
DEFAULT = "Enum  Enum.forString(\"default\")"
PRESERVE = "Enum  Enum.forString(\"preserve\")"
INT_DEFAULT = "int  1"
INT_PRESERVE = "int  2"
