START_VALUE = "Value  new StringValue((short)21, "full")"
MIDDLE_VALUE = "Value  new StringValue((short)21, "middle")"
END_VALUE = "Value  new StringValue((short)21, "end")"
FULL_VALUE = "Value  new StringValue((short)21, "full")"
NORMAL_VALUE = "Value  new StringValue((short)21, "normal")"
