META = "String  \"/meta\""
META_HANDSHAKE = "String  \"/meta/handshake\""
META_CONNECT = "String  \"/meta/connect\""
META_SUBSCRIBE = "String  \"/meta/subscribe\""
META_UNSUBSCRIBE = "String  \"/meta/unsubscribe\""
META_DISCONNECT = "String  \"/meta/disconnect\""
