COPYRIGHT = "String  \"\n\n(C) Copyright IBM Corp. 2003, 2007.\n\n\""
TYPE_ANY = "int  0"
TYPE_NONE = "int  0"
TYPE_APPROXIMATEMATCH = "int  1"
TYPE_TRANSLITERATION = "int  2"
TYPE_USERDEFINED_MIN = "int  1024"
