def LoggingStatement():
'''public LoggingStatement(final Statement s)
'''
pass
def unwrap():
'''public <T> T unwrap(final Class<T> iface)
'''
pass
def isWrapperFor():
'''public boolean isWrapperFor(final Class<?> iface)
'''
pass
def addBatch():
'''public void addBatch(final String sql)
'''
pass
def cancel():
'''public void cancel()
'''
pass
def clearBatch():
'''public void clearBatch()
'''
pass
def clearWarnings():
'''public void clearWarnings()
'''
pass
def close():
'''public void close()
'''
pass
def execute():
'''public boolean execute(final String sql)
public boolean execute(final String sql, final int autoGeneratedKeys)
public boolean execute(final String sql, final int[] columnIndexes)
public boolean execute(final String sql, final String[] columnNames)
'''
pass
def executeBatch():
'''public int[] executeBatch()
'''
pass
def executeQuery():
'''public ResultSet executeQuery(final String sql)
'''
pass
def executeUpdate():
'''public int executeUpdate(final String sql)
public int executeUpdate(final String sql, final int autoGeneratedKeys)
public int executeUpdate(final String sql, final int[] columnIndexes)
public int executeUpdate(final String sql, final String[] columnNames)
'''
pass
def getConnection():
'''public Connection getConnection()
'''
pass
def getFetchDirection():
'''public int getFetchDirection()
'''
pass
def getFetchSize():
'''public int getFetchSize()
'''
pass
def getGeneratedKeys():
'''public ResultSet getGeneratedKeys()
'''
pass
def getMaxFieldSize():
'''public int getMaxFieldSize()
'''
pass
def getMaxRows():
'''public int getMaxRows()
'''
pass
def getMoreResults():
'''public boolean getMoreResults()
public boolean getMoreResults(final int current)
'''
pass
def getQueryTimeout():
'''public int getQueryTimeout()
'''
pass
def getResultSet():
'''public ResultSet getResultSet()
'''
pass
def getResultSetConcurrency():
'''public int getResultSetConcurrency()
'''
pass
def getResultSetHoldability():
'''public int getResultSetHoldability()
'''
pass
def getResultSetType():
'''public int getResultSetType()
'''
pass
def getUpdateCount():
'''public int getUpdateCount()
'''
pass
def getWarnings():
'''public SQLWarning getWarnings()
'''
pass
def setCursorName():
'''public void setCursorName(final String name)
'''
pass
def setEscapeProcessing():
'''public void setEscapeProcessing(final boolean enable)
'''
pass
def setFetchDirection():
'''public void setFetchDirection(final int direction)
'''
pass
def setFetchSize():
'''public void setFetchSize(final int rows)
'''
pass
def setMaxFieldSize():
'''public void setMaxFieldSize(final int max)
'''
pass
def setMaxRows():
'''public void setMaxRows(final int max)
'''
pass
def setQueryTimeout():
'''public void setQueryTimeout(final int seconds)
'''
pass
def isClosed():
'''public boolean isClosed()
'''
pass
def setPoolable():
'''public void setPoolable(final boolean poolable)
'''
pass
def isPoolable():
'''public boolean isPoolable()
'''
pass
def closeOnCompletion():
'''public void closeOnCompletion()
'''
pass
def isCloseOnCompletion():
'''public boolean isCloseOnCompletion()
'''
pass
