SQLLOG_Execute = "String  \"SQLlog.execute\""
SQLLOG_Query = "String  \"SQLlog.query\""
SQLLOG_Result = "String  \"SQLlog.result\""
SQLLOG_OPEN = "String  \"SQLlog.open\""
SQLLOG_CLOSE = "String  \"SQLlog.close\""
SQLLOG_UNSUPPORTED = "String  \"SQLLog.unsupported\""
SQLLOG_PARAMETERS = "String  \"SQLLog.parameters\""
def log():
    '''public static void log(final String loggerName, final Object msg)
    '''
def getLoggingConnection():
    '''public static Connection getLoggingConnection(final Connection con)
    public static Connection getLoggingConnection(final Connection con, final LogSQL logger)
    '''
def setSQLLogger():
    '''public void setSQLLogger(final LogSQL logger)
    '''
def clearWarnings():
    '''public void clearWarnings()
    '''
def close():
    '''public void close()
    '''
def commit():
    '''public void commit()
    '''
def createArrayOf():
    '''public Array createArrayOf(final String typeName, final Object[] elements)
    '''
def createBlob():
    '''public Blob createBlob()
    '''
def createClob():
    '''public Clob createClob()
    '''
def createNClob():
    '''public NClob createNClob()
    '''
def createSQLXML():
    '''public SQLXML createSQLXML()
    '''
def createStatement():
    '''public Statement createStatement()
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency)
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
    '''
def createStruct():
    '''public Struct createStruct(final String typeName, final Object[] attributes)
    '''
def getAutoCommit():
    '''public boolean getAutoCommit()
    '''
def getCatalog():
    '''public String getCatalog()
    '''
def getClientInfo():
    '''public Properties getClientInfo()
    public String getClientInfo(final String name)
    '''
def getHoldability():
    '''public int getHoldability()
    '''
def getMetaData():
    '''public DatabaseMetaData getMetaData()
    '''
def getTransactionIsolation():
    '''public int getTransactionIsolation()
    '''
def getWarnings():
    '''public SQLWarning getWarnings()
    '''
def isClosed():
    '''public boolean isClosed()
    '''
def isReadOnly():
    '''public boolean isReadOnly()
    '''
def isValid():
    '''public boolean isValid(final int timeout)
    '''
def nativeSQL():
    '''public String nativeSQL(final String sql)
    '''
def prepareCall():
    '''public CallableStatement prepareCall(final String sql)
    public CallableStatement prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency)
    public CallableStatement prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
    '''
def prepareStatement():
    '''public PreparedStatement prepareStatement(final String sql)
    public PreparedStatement prepareStatement(final String sql, final int autoGeneratedKeys)
    public PreparedStatement prepareStatement(final String sql, final int[] columnIndexes)
    public PreparedStatement prepareStatement(final String sql, final String[] columnNames)
    public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency)
    public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
    '''
def releaseSavepoint():
    '''public void releaseSavepoint(final Savepoint savepoint)
    '''
def rollback():
    '''public void rollback()
    public void rollback(final Savepoint savepoint)
    '''
def setAutoCommit():
    '''public void setAutoCommit(final boolean autoCommit)
    '''
def setCatalog():
    '''public void setCatalog(final String catalog)
    '''
def setClientInfo():
    '''public void setClientInfo(final Properties properties)
    public void setClientInfo(final String name, final String value)
    '''
def setHoldability():
    '''public void setHoldability(final int holdability)
    '''
def setReadOnly():
    '''public void setReadOnly(final boolean readOnly)
    '''
def setSavepoint():
    '''public Savepoint setSavepoint()
    public Savepoint setSavepoint(final String name)
    '''
def setTransactionIsolation():
    '''public void setTransactionIsolation(final int level)
    '''
def setTypeMap():
    '''public void setTypeMap(final Map<String, Class<?>> map)
    '''
def isWrapperFor():
    '''public boolean isWrapperFor(final Class<?> iface)
    '''
def unwrap():
    '''public <T> T unwrap(final Class<T> iface)
    '''
def setNetworkTimeout():
    '''public void setNetworkTimeout(final Executor executor, final int milliseconds)
    '''
def getNetworkTimeout():
    '''public int getNetworkTimeout()
    '''
def setSchema():
    '''public void setSchema(final String schema)
    '''
def getSchema():
    '''public String getSchema()
    '''
def abort():
    '''public void abort(final Executor executor)
    '''
