CONTEXTCHANGE = "String  \"MTConnection.setContext\""
UNSUPPORTED = "String  \"MTConnection.unsupported\""
def setEnableUpdateTeantCodeDefaultValue():
    '''returns None\n\n
    setEnableUpdateTeantCodeDefaultValue(final boolean enableUpdateTeantCodeDefaultValue)\n
    '''
def ():
    '''returns MTConnection\n\n
    (final Connection conDB, final Properties properties)\n
    '''
def clearWarnings():
    '''returns None\n\n
    clearWarnings()\n
    '''
def close():
    '''returns None\n\n
    close()\n
    '''
def commit():
    '''returns None\n\n
    commit()\n
    '''
def getContextConnection():
    '''returns Connection\n\n
    getContextConnection(final MTContext context)\n
    '''
def getContext():
    '''returns MTContext\n\n
    getContext()\n
    '''
def createArrayOf():
    '''returns Array\n\n
    createArrayOf(final String arg0, final Object[] arg1)\n
    '''
def createBlob():
    '''returns Blob\n\n
    createBlob()\n
    '''
def createClob():
    '''returns Clob\n\n
    createClob()\n
    '''
def createNClob():
    '''returns NClob\n\n
    createNClob()\n
    '''
def createSQLXML():
    '''returns SQLXML\n\n
    createSQLXML()\n
    '''
def createStatement():
    '''returns Statement\n\n
    createStatement()\n
    createStatement(final int resultSetType, final int resultSetConcurrency)\n
    createStatement(final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)\n
    '''
def createStruct():
    '''returns Struct\n\n
    createStruct(final String arg0, final Object[] arg1)\n
    '''
def getAutoCommit():
    '''returns boolean\n\n
    getAutoCommit()\n
    '''
def getCatalog():
    '''returns String\n\n
    getCatalog()\n
    '''
def getClientInfo():
    '''returns String\n\n
    getClientInfo()\n
    getClientInfo(final String arg0)\n
    '''
def getHoldability():
    '''returns int\n\n
    getHoldability()\n
    '''
def getMetaData():
    '''returns DatabaseMetaData\n\n
    getMetaData()\n
    '''
def getTransactionIsolation():
    '''returns int\n\n
    getTransactionIsolation()\n
    '''
def getWarnings():
    '''returns SQLWarning\n\n
    getWarnings()\n
    '''
def isClosed():
    '''returns boolean\n\n
    isClosed()\n
    '''
def isReadOnly():
    '''returns boolean\n\n
    isReadOnly()\n
    '''
def isValid():
    '''returns boolean\n\n
    isValid(final int arg0)\n
    '''
def nativeSQL():
    '''returns String\n\n
    nativeSQL(final String arg0)\n
    '''
def prepareCall():
    '''returns CallableStatement\n\n
    prepareCall(final String sql)\n
    prepareCall(final String arg0, final int arg1, final int arg2)\n
    prepareCall(final String arg0, final int arg1, final int arg2, final int arg3)\n
    '''
def prepareStatement():
    '''returns PreparedStatement\n\n
    prepareStatement(final String sql)\n
    prepareStatement(final String sql, final int autoGeneratedKeys)\n
    prepareStatement(final String sql, final int[] columnIndexes)\n
    prepareStatement(final String sql, final String[] columnNames)\n
    prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency)\n
    prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)\n
    '''
def releaseSavepoint():
    '''returns None\n\n
    releaseSavepoint(final Savepoint arg0)\n
    '''
def rollback():
    '''returns None\n\n
    rollback()\n
    rollback(final Savepoint savepoint)\n
    '''
def setAutoCommit():
    '''returns None\n\n
    setAutoCommit(final boolean autoCommit)\n
    '''
def setCatalog():
    '''returns None\n\n
    setCatalog(final String arg0)\n
    '''
def setClientInfo():
    '''returns None\n\n
    setClientInfo(final Properties arg0)\n
    setClientInfo(final String arg0, final String arg1)\n
    '''
def setHoldability():
    '''returns None\n\n
    setHoldability(final int arg0)\n
    '''
def setReadOnly():
    '''returns None\n\n
    setReadOnly(final boolean arg0)\n
    '''
def setSavepoint():
    '''returns Savepoint\n\n
    setSavepoint()\n
    setSavepoint(final String arg0)\n
    '''
def setTransactionIsolation():
    '''returns None\n\n
    setTransactionIsolation(final int arg0)\n
    '''
def setTypeMap():
    '''returns None\n\n
    setTypeMap(final Map<String, Class<?>> arg0)\n
    '''
def isWrapperFor():
    '''returns boolean\n\n
    isWrapperFor(final Class<?> iface)\n
    '''
def setStorageType():
    '''returns None\n\n
    setStorageType(final String tbname, final MTStorageType st)\n
    '''
def getStorageType():
    '''returns MTStorageType\n\n
    getStorageType(String tbname)\n
    '''
def getContextForSql():
    '''returns List<ContextSql>\n\n
    getContextForSql(final String sql)\n
    '''
def getContextForQuery():
    '''returns MTContext\n\n
    getContextForQuery(final String sql)\n
    '''
def getTenantContexts():
    '''returns Set<MTContext>\n\n
    getTenantContexts()\n
    '''
def getAllContexts():
    '''returns Set<MTContext>\n\n
    getAllContexts()\n
    '''
def setTargetContexts():
    '''returns None\n\n
    setTargetContexts(final Collection<MTContext> c)\n
    '''
def setTargetContext():
    '''returns None\n\n
    setTargetContext(final MTContext c)\n
    '''
def getTargetContext():
    '''returns List<MTContext>\n\n
    getTargetContext()\n
    '''
def setTargetContextByName():
    '''returns None\n\n
    setTargetContextByName(final String context)\n
    '''
def pushContext():
    '''returns None\n\n
    pushContext(final MTContext context)\n
    pushContext(final List<MTContext> contextList)\n
    '''
def popContext():
    '''returns None\n\n
    popContext()\n
    '''
def setNetworkTimeout():
    '''returns None\n\n
    setNetworkTimeout(final Executor executor, final int milliseconds)\n
    '''
def getNetworkTimeout():
    '''returns int\n\n
    getNetworkTimeout()\n
    '''
def setSchema():
    '''returns None\n\n
    setSchema(final String schema)\n
    '''
def getSchema():
    '''returns String\n\n
    getSchema()\n
    '''
def abort():
    '''returns None\n\n
    abort(final Executor executor)\n
    '''
