def MTPreparedStatement():
    '''    public MTPreparedStatement(final MTConnection mtConnection, final String sql)
    public MTPreparedStatement(final MTConnection mtConnection, final String sql, final int autoGeneratedKeys)
    public MTPreparedStatement(final MTConnection mtConnection, final String sql, final int[] columnIndexes)
    public MTPreparedStatement(final MTConnection mtConnection, final String sql, final String[] columnNames)
    public MTPreparedStatement(final MTConnection mtConnection, final String sql, final int resultSetType, final int resultSetConcurrency)
    public MTPreparedStatement(final MTConnection mtConnection, final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
    '''
def setNull():
    '''    public void setNull(final int parameterIndex, final int sqlType)
    public void setNull(final int parameterIndex, final int sqlType, final String arg2)
    '''
def addBatch():
    '''    public void addBatch()
    '''
def clearParameters():
    '''    public void clearParameters()
    '''
def execute():
    '''    public boolean execute()
    '''
def executeQuery():
    '''    public ResultSet executeQuery()
    '''
def executeUpdate():
    '''    public int executeUpdate()
    '''
def getMetaData():
    '''    public ResultSetMetaData getMetaData()
    '''
def getParameterMetaData():
    '''    public ParameterMetaData getParameterMetaData()
    '''
def setArray():
    '''    public void setArray(final int parameterIndex, final Array x)
    '''
def setAsciiStream():
    '''    public void setAsciiStream(final int parameterIndex, final InputStream x)
    public void setAsciiStream(final int parameterIndex, final InputStream x, final int length)
    public void setAsciiStream(final int parameterIndex, final InputStream x, final long length)
    '''
def setBigDecimal():
    '''    public void setBigDecimal(final int parameterIndex, final BigDecimal x)
    '''
def setBinaryStream():
    '''    public void setBinaryStream(final int parameterIndex, final InputStream x)
    public void setBinaryStream(final int parameterIndex, final InputStream x, final int length)
    public void setBinaryStream(final int parameterIndex, final InputStream x, final long length)
    '''
def setBlob():
    '''    public void setBlob(final int parameterIndex, final Blob x)
    public void setBlob(final int parameterIndex, final InputStream inputStream)
    public void setBlob(final int parameterIndex, final InputStream inputStream, final long length)
    '''
def setBoolean():
    '''    public void setBoolean(final int parameterIndex, final boolean x)
    '''
def setByte():
    '''    public void setByte(final int parameterIndex, final byte x)
    '''
def setBytes():
    '''    public void setBytes(final int parameterIndex, final byte[] x)
    '''
def setCharacterStream():
    '''    public void setCharacterStream(final int parameterIndex, final Reader reader)
    public void setCharacterStream(final int parameterIndex, final Reader reader, final int length)
    public void setCharacterStream(final int parameterIndex, final Reader reader, final long length)
    '''
def setClob():
    '''    public void setClob(final int parameterIndex, final Clob x)
    public void setClob(final int parameterIndex, final Reader reader)
    public void setClob(final int parameterIndex, final Reader reader, final long length)
    '''
def setDate():
    '''    public void setDate(final int parameterIndex, final Date x)
    public void setDate(final int parameterIndex, final Date x, final Calendar cal)
    '''
def setDouble():
    '''    public void setDouble(final int parameterIndex, final double x)
    '''
def setFloat():
    '''    public void setFloat(final int parameterIndex, final float x)
    '''
def setInt():
    '''    public void setInt(final int parameterIndex, final int x)
    '''
def setLong():
    '''    public void setLong(final int parameterIndex, final long x)
    '''
def setNCharacterStream():
    '''    public void setNCharacterStream(final int parameterIndex, final Reader value)
    public void setNCharacterStream(final int parameterIndex, final Reader value, final long length)
    '''
def setNClob():
    '''    public void setNClob(final int parameterIndex, final NClob value)
    public void setNClob(final int parameterIndex, final Reader reader)
    public void setNClob(final int parameterIndex, final Reader reader, final long length)
    '''
def setNString():
    '''    public void setNString(final int parameterIndex, final String value)
    '''
def setObject():
    '''    public void setObject(final int parameterIndex, final Object x)
    public void setObject(final int parameterIndex, final Object x, final int targetSqlType)
    public void setObject(final int parameterIndex, final Object x, final int targetSqlType, final int scaleOrLength)
    '''
def setRef():
    '''    public void setRef(final int parameterIndex, final Ref x)
    '''
def setRowId():
    '''    public void setRowId(final int parameterIndex, final RowId x)
    '''
def setSQLXML():
    '''    public void setSQLXML(final int parameterIndex, final SQLXML xmlObject)
    '''
def setShort():
    '''    public void setShort(final int parameterIndex, final short x)
    '''
def setString():
    '''    public void setString(final int parameterIndex, final String x)
    '''
def setTime():
    '''    public void setTime(final int parameterIndex, final Time x)
    public void setTime(final int parameterIndex, final Time x, final Calendar cal)
    '''
def setTimestamp():
    '''    public void setTimestamp(final int parameterIndex, final Timestamp x)
    public void setTimestamp(final int parameterIndex, final Timestamp x, final Calendar cal)
    '''
def setURL():
    '''    public void setURL(final int parameterIndex, final URL x)
    '''
def setUnicodeStream():
    '''    public void setUnicodeStream(final int parameterIndex, final InputStream x, final int length)
    '''
