def MTPreparedStatement():
'''public MTPreparedStatement(final MTConnection mtConnection, final String sql)
public MTPreparedStatement(final MTConnection mtConnection, final String sql, final int autoGeneratedKeys)
public MTPreparedStatement(final MTConnection mtConnection, final String sql, final int[] columnIndexes)
public MTPreparedStatement(final MTConnection mtConnection, final String sql, final String[] columnNames)
public MTPreparedStatement(final MTConnection mtConnection, final String sql, final int resultSetType, final int resultSetConcurrency)
public MTPreparedStatement(final MTConnection mtConnection, final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
'''
pass
def setNull():
'''public void setNull(final int parameterIndex, final int sqlType)
public void setNull(final int parameterIndex, final int sqlType, final String arg2)
'''
pass
def addBatch():
'''public void addBatch()
'''
pass
def clearParameters():
'''public void clearParameters()
'''
pass
def execute():
'''public boolean execute()
'''
pass
def executeQuery():
'''public ResultSet executeQuery()
'''
pass
def executeUpdate():
'''public int executeUpdate()
'''
pass
def getMetaData():
'''public ResultSetMetaData getMetaData()
'''
pass
def getParameterMetaData():
'''public ParameterMetaData getParameterMetaData()
'''
pass
def setArray():
'''public void setArray(final int parameterIndex, final Array x)
'''
pass
def setAsciiStream():
'''public void setAsciiStream(final int parameterIndex, final InputStream x)
public void setAsciiStream(final int parameterIndex, final InputStream x, final int length)
public void setAsciiStream(final int parameterIndex, final InputStream x, final long length)
'''
pass
def setBigDecimal():
'''public void setBigDecimal(final int parameterIndex, final BigDecimal x)
'''
pass
def setBinaryStream():
'''public void setBinaryStream(final int parameterIndex, final InputStream x)
public void setBinaryStream(final int parameterIndex, final InputStream x, final int length)
public void setBinaryStream(final int parameterIndex, final InputStream x, final long length)
'''
pass
def setBlob():
'''public void setBlob(final int parameterIndex, final Blob x)
public void setBlob(final int parameterIndex, final InputStream inputStream)
public void setBlob(final int parameterIndex, final InputStream inputStream, final long length)
'''
pass
def setBoolean():
'''public void setBoolean(final int parameterIndex, final boolean x)
'''
pass
def setByte():
'''public void setByte(final int parameterIndex, final byte x)
'''
pass
def setBytes():
'''public void setBytes(final int parameterIndex, final byte[] x)
'''
pass
def setCharacterStream():
'''public void setCharacterStream(final int parameterIndex, final Reader reader)
public void setCharacterStream(final int parameterIndex, final Reader reader, final int length)
public void setCharacterStream(final int parameterIndex, final Reader reader, final long length)
'''
pass
def setClob():
'''public void setClob(final int parameterIndex, final Clob x)
public void setClob(final int parameterIndex, final Reader reader)
public void setClob(final int parameterIndex, final Reader reader, final long length)
'''
pass
def setDate():
'''public void setDate(final int parameterIndex, final Date x)
public void setDate(final int parameterIndex, final Date x, final Calendar cal)
'''
pass
def setDouble():
'''public void setDouble(final int parameterIndex, final double x)
'''
pass
def setFloat():
'''public void setFloat(final int parameterIndex, final float x)
'''
pass
def setInt():
'''public void setInt(final int parameterIndex, final int x)
'''
pass
def setLong():
'''public void setLong(final int parameterIndex, final long x)
'''
pass
def setNCharacterStream():
'''public void setNCharacterStream(final int parameterIndex, final Reader value)
public void setNCharacterStream(final int parameterIndex, final Reader value, final long length)
'''
pass
def setNClob():
'''public void setNClob(final int parameterIndex, final NClob value)
public void setNClob(final int parameterIndex, final Reader reader)
public void setNClob(final int parameterIndex, final Reader reader, final long length)
'''
pass
def setNString():
'''public void setNString(final int parameterIndex, final String value)
'''
pass
def setObject():
'''public void setObject(final int parameterIndex, final Object x)
public void setObject(final int parameterIndex, final Object x, final int targetSqlType)
public void setObject(final int parameterIndex, final Object x, final int targetSqlType, final int scaleOrLength)
'''
pass
def setRef():
'''public void setRef(final int parameterIndex, final Ref x)
'''
pass
def setRowId():
'''public void setRowId(final int parameterIndex, final RowId x)
'''
pass
def setSQLXML():
'''public void setSQLXML(final int parameterIndex, final SQLXML xmlObject)
'''
pass
def setShort():
'''public void setShort(final int parameterIndex, final short x)
'''
pass
def setString():
'''public void setString(final int parameterIndex, final String x)
'''
pass
def setTime():
'''public void setTime(final int parameterIndex, final Time x)
public void setTime(final int parameterIndex, final Time x, final Calendar cal)
'''
pass
def setTimestamp():
'''public void setTimestamp(final int parameterIndex, final Timestamp x)
public void setTimestamp(final int parameterIndex, final Timestamp x, final Calendar cal)
'''
pass
def setURL():
'''public void setURL(final int parameterIndex, final URL x)
'''
pass
def setUnicodeStream():
'''public void setUnicodeStream(final int parameterIndex, final InputStream x, final int length)
'''
pass
