def ():
    '''returns MTPreparedStatement\n\n
    (final MTConnection mtConnection, final String sql)\n
    (final MTConnection mtConnection, final String sql, final int autoGeneratedKeys)\n
    (final MTConnection mtConnection, final String sql, final int[] columnIndexes)\n
    (final MTConnection mtConnection, final String sql, final String[] columnNames)\n
    (final MTConnection mtConnection, final String sql, final int resultSetType, final int resultSetConcurrency)\n
    (final MTConnection mtConnection, final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)\n
    '''
def setNull():
    '''returns None\n\n
    setNull(final int parameterIndex, final int sqlType)\n
    setNull(final int parameterIndex, final int sqlType, final String arg2)\n
    '''
def addBatch():
    '''returns None\n\n
    addBatch()\n
    '''
def clearParameters():
    '''returns None\n\n
    clearParameters()\n
    '''
def execute():
    '''returns boolean\n\n
    execute()\n
    '''
def executeQuery():
    '''returns ResultSet\n\n
    executeQuery()\n
    '''
def executeUpdate():
    '''returns int\n\n
    executeUpdate()\n
    '''
def getMetaData():
    '''returns ResultSetMetaData\n\n
    getMetaData()\n
    '''
def getParameterMetaData():
    '''returns ParameterMetaData\n\n
    getParameterMetaData()\n
    '''
def setArray():
    '''returns None\n\n
    setArray(final int parameterIndex, final Array x)\n
    '''
def setAsciiStream():
    '''returns None\n\n
    setAsciiStream(final int parameterIndex, final InputStream x)\n
    setAsciiStream(final int parameterIndex, final InputStream x, final int length)\n
    setAsciiStream(final int parameterIndex, final InputStream x, final long length)\n
    '''
def setBigDecimal():
    '''returns None\n\n
    setBigDecimal(final int parameterIndex, final BigDecimal x)\n
    '''
def setBinaryStream():
    '''returns None\n\n
    setBinaryStream(final int parameterIndex, final InputStream x)\n
    setBinaryStream(final int parameterIndex, final InputStream x, final int length)\n
    setBinaryStream(final int parameterIndex, final InputStream x, final long length)\n
    '''
def setBlob():
    '''returns None\n\n
    setBlob(final int parameterIndex, final Blob x)\n
    setBlob(final int parameterIndex, final InputStream inputStream)\n
    setBlob(final int parameterIndex, final InputStream inputStream, final long length)\n
    '''
def setBoolean():
    '''returns None\n\n
    setBoolean(final int parameterIndex, final boolean x)\n
    '''
def setByte():
    '''returns None\n\n
    setByte(final int parameterIndex, final byte x)\n
    '''
def setBytes():
    '''returns None\n\n
    setBytes(final int parameterIndex, final byte[] x)\n
    '''
def setCharacterStream():
    '''returns None\n\n
    setCharacterStream(final int parameterIndex, final Reader reader)\n
    setCharacterStream(final int parameterIndex, final Reader reader, final int length)\n
    setCharacterStream(final int parameterIndex, final Reader reader, final long length)\n
    '''
def setClob():
    '''returns None\n\n
    setClob(final int parameterIndex, final Clob x)\n
    setClob(final int parameterIndex, final Reader reader)\n
    setClob(final int parameterIndex, final Reader reader, final long length)\n
    '''
def setDate():
    '''returns None\n\n
    setDate(final int parameterIndex, final Date x)\n
    setDate(final int parameterIndex, final Date x, final Calendar cal)\n
    '''
def setDouble():
    '''returns None\n\n
    setDouble(final int parameterIndex, final double x)\n
    '''
def setFloat():
    '''returns None\n\n
    setFloat(final int parameterIndex, final float x)\n
    '''
def setInt():
    '''returns None\n\n
    setInt(final int parameterIndex, final int x)\n
    '''
def setLong():
    '''returns None\n\n
    setLong(final int parameterIndex, final long x)\n
    '''
def setNCharacterStream():
    '''returns None\n\n
    setNCharacterStream(final int parameterIndex, final Reader value)\n
    setNCharacterStream(final int parameterIndex, final Reader value, final long length)\n
    '''
def setNClob():
    '''returns None\n\n
    setNClob(final int parameterIndex, final NClob value)\n
    setNClob(final int parameterIndex, final Reader reader)\n
    setNClob(final int parameterIndex, final Reader reader, final long length)\n
    '''
def setNString():
    '''returns None\n\n
    setNString(final int parameterIndex, final String value)\n
    '''
def setObject():
    '''returns None\n\n
    setObject(final int parameterIndex, final Object x)\n
    setObject(final int parameterIndex, final Object x, final int targetSqlType)\n
    setObject(final int parameterIndex, final Object x, final int targetSqlType, final int scaleOrLength)\n
    '''
def setRef():
    '''returns None\n\n
    setRef(final int parameterIndex, final Ref x)\n
    '''
def setRowId():
    '''returns None\n\n
    setRowId(final int parameterIndex, final RowId x)\n
    '''
def setSQLXML():
    '''returns None\n\n
    setSQLXML(final int parameterIndex, final SQLXML xmlObject)\n
    '''
def setShort():
    '''returns None\n\n
    setShort(final int parameterIndex, final short x)\n
    '''
def setString():
    '''returns None\n\n
    setString(final int parameterIndex, final String x)\n
    '''
def setTime():
    '''returns None\n\n
    setTime(final int parameterIndex, final Time x)\n
    setTime(final int parameterIndex, final Time x, final Calendar cal)\n
    '''
def setTimestamp():
    '''returns None\n\n
    setTimestamp(final int parameterIndex, final Timestamp x)\n
    setTimestamp(final int parameterIndex, final Timestamp x, final Calendar cal)\n
    '''
def setURL():
    '''returns None\n\n
    setURL(final int parameterIndex, final URL x)\n
    '''
def setUnicodeStream():
    '''returns None\n\n
    setUnicodeStream(final int parameterIndex, final InputStream x, final int length)\n
    '''
