def ():
    '''returns MTStatement\n\n
    (final MTConnection mtConnection)\n
    (final MTConnection con, final int resultSetType, final int resultSetConcurrency)\n
    (final MTConnection con, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)\n
    '''
def addBatch():
    '''returns None\n\n
    addBatch(final String sql)\n
    '''
def cancel():
    '''returns None\n\n
    cancel()\n
    '''
def clearBatch():
    '''returns None\n\n
    clearBatch()\n
    '''
def clearWarnings():
    '''returns None\n\n
    clearWarnings()\n
    '''
def close():
    '''returns None\n\n
    close()\n
    '''
def execute():
    '''returns boolean\n\n
    execute(final String sql)\n
    execute(final String sql, final int autoGeneratedKeys)\n
    execute(final String sql, final int[] columnIndexes)\n
    execute(final String sql, final String[] columnNames)\n
    '''
def executeBatch():
    '''returns int[]\n\n
    executeBatch()\n
    '''
def executeQuery():
    '''returns ResultSet\n\n
    executeQuery(final String sql)\n
    '''
def executeUpdate():
    '''returns int\n\n
    executeUpdate(final String sql)\n
    executeUpdate(final String sql, final int autoGeneratedKeys)\n
    executeUpdate(final String sql, final int[] columnIndexes)\n
    executeUpdate(final String sql, final String[] columnNames)\n
    '''
def getConnection():
    '''returns Connection\n\n
    getConnection()\n
    '''
def getFetchDirection():
    '''returns int\n\n
    getFetchDirection()\n
    '''
def getFetchSize():
    '''returns int\n\n
    getFetchSize()\n
    '''
def getGeneratedKeys():
    '''returns ResultSet\n\n
    getGeneratedKeys()\n
    '''
def getMaxFieldSize():
    '''returns int\n\n
    getMaxFieldSize()\n
    '''
def getMaxRows():
    '''returns int\n\n
    getMaxRows()\n
    '''
def getMoreResults():
    '''returns boolean\n\n
    getMoreResults()\n
    getMoreResults(final int current)\n
    '''
def getQueryTimeout():
    '''returns int\n\n
    getQueryTimeout()\n
    '''
def getResultSet():
    '''returns ResultSet\n\n
    getResultSet()\n
    '''
def getResultSetConcurrency():
    '''returns int\n\n
    getResultSetConcurrency()\n
    '''
def getResultSetHoldability():
    '''returns int\n\n
    getResultSetHoldability()\n
    '''
def getResultSetType():
    '''returns int\n\n
    getResultSetType()\n
    '''
def getUpdateCount():
    '''returns int\n\n
    getUpdateCount()\n
    '''
def getWarnings():
    '''returns SQLWarning\n\n
    getWarnings()\n
    '''
def isClosed():
    '''returns boolean\n\n
    isClosed()\n
    '''
def isPoolable():
    '''returns boolean\n\n
    isPoolable()\n
    '''
def setCursorName():
    '''returns None\n\n
    setCursorName(final String name)\n
    '''
def setEscapeProcessing():
    '''returns None\n\n
    setEscapeProcessing(final boolean enable)\n
    '''
def setFetchDirection():
    '''returns None\n\n
    setFetchDirection(final int direction)\n
    '''
def setFetchSize():
    '''returns None\n\n
    setFetchSize(final int rows)\n
    '''
def setMaxFieldSize():
    '''returns None\n\n
    setMaxFieldSize(final int max)\n
    '''
def setMaxRows():
    '''returns None\n\n
    setMaxRows(final int max)\n
    '''
def setPoolable():
    '''returns None\n\n
    setPoolable(final boolean poolable)\n
    '''
def setQueryTimeout():
    '''returns None\n\n
    setQueryTimeout(final int seconds)\n
    '''
def isWrapperFor():
    '''returns boolean\n\n
    isWrapperFor(final Class<?> arg0)\n
    '''
def closeOnCompletion():
    '''returns None\n\n
    closeOnCompletion()\n
    '''
def isCloseOnCompletion():
    '''returns boolean\n\n
    isCloseOnCompletion()\n
    '''
