def MTStatement():
    '''public MTStatement(final MTConnection mtConnection)
    public MTStatement(final MTConnection con, final int resultSetType, final int resultSetConcurrency)
    public MTStatement(final MTConnection con, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability)
    '''
def addBatch():
    '''public void addBatch(final String sql)
    '''
def cancel():
    '''public void cancel()
    '''
def clearBatch():
    '''public void clearBatch()
    '''
def clearWarnings():
    '''public void clearWarnings()
    '''
def close():
    '''public void close()
    '''
def execute():
    '''public boolean execute(final String sql)
    public boolean execute(final String sql, final int autoGeneratedKeys)
    public boolean execute(final String sql, final int[] columnIndexes)
    public boolean execute(final String sql, final String[] columnNames)
    '''
def executeBatch():
    '''public int[] executeBatch()
    '''
def executeQuery():
    '''public ResultSet executeQuery(final String sql)
    '''
def executeUpdate():
    '''public int executeUpdate(final String sql)
    public int executeUpdate(final String sql, final int autoGeneratedKeys)
    public int executeUpdate(final String sql, final int[] columnIndexes)
    public int executeUpdate(final String sql, final String[] columnNames)
    '''
def getConnection():
    '''public Connection getConnection()
    '''
def getFetchDirection():
    '''public int getFetchDirection()
    '''
def getFetchSize():
    '''public int getFetchSize()
    '''
def getGeneratedKeys():
    '''public ResultSet getGeneratedKeys()
    '''
def getMaxFieldSize():
    '''public int getMaxFieldSize()
    '''
def getMaxRows():
    '''public int getMaxRows()
    '''
def getMoreResults():
    '''public boolean getMoreResults()
    public boolean getMoreResults(final int current)
    '''
def getQueryTimeout():
    '''public int getQueryTimeout()
    '''
def getResultSet():
    '''public ResultSet getResultSet()
    '''
def getResultSetConcurrency():
    '''public int getResultSetConcurrency()
    '''
def getResultSetHoldability():
    '''public int getResultSetHoldability()
    '''
def getResultSetType():
    '''public int getResultSetType()
    '''
def getUpdateCount():
    '''public int getUpdateCount()
    '''
def getWarnings():
    '''public SQLWarning getWarnings()
    '''
def isClosed():
    '''public boolean isClosed()
    '''
def isPoolable():
    '''public boolean isPoolable()
    '''
def setCursorName():
    '''public void setCursorName(final String name)
    '''
def setEscapeProcessing():
    '''public void setEscapeProcessing(final boolean enable)
    '''
def setFetchDirection():
    '''public void setFetchDirection(final int direction)
    '''
def setFetchSize():
    '''public void setFetchSize(final int rows)
    '''
def setMaxFieldSize():
    '''public void setMaxFieldSize(final int max)
    '''
def setMaxRows():
    '''public void setMaxRows(final int max)
    '''
def setPoolable():
    '''public void setPoolable(final boolean poolable)
    '''
def setQueryTimeout():
    '''public void setQueryTimeout(final int seconds)
    '''
def isWrapperFor():
    '''public boolean isWrapperFor(final Class<?> arg0)
    '''
def unwrap():
    '''public <T> T unwrap(final Class<T> arg0)
    '''
def closeOnCompletion():
    '''public void closeOnCompletion()
    '''
def isCloseOnCompletion():
    '''public boolean isCloseOnCompletion()
    '''
