JDBC_ERROR_BASE = "int  17000"
JDBC_MAX_ERRORS = "int  2000"
JDBC_MAX_17000_ERROR = "int  17499"
JDBC_MAX_18700_ERROR = "int  18999"
EOJ_SUCCESS = "int  0"
EOJ_ERROR = "int  1"
EOJ_IOEXCEPTION = "int  2"
EOJ_INVALID_COLUMN_INDEX = "int  3"
EOJ_INVALID_COLUMN_TYPE = "int  4"
EOJ_UNSUPPORTED_COLUMN_TYPE = "int  5"
EOJ_INVALID_COLUMN_NAME = "int  6"
EOJ_INVALID_DYNAMIC_COLUMN = "int  7"
EOJ_CLOSED_CONNECTION = "int  8"
EOJ_CLOSED_STATEMENT = "int  9"
EOJ_CLOSED_RESULTSET = "int  10"
EOJ_EXHAUSTED_RESULTSET = "int  11"
EOJ_TYPE_CONFLICT = "int  12"
EOJ_WAS_NULL = "int  13"
EOJ_RESULTSET_BEFORE_FIRST_ROW = "int  14"
EOJ_STATEMENT_WAS_CANCELLED = "int  15"
EOJ_STATEMENT_TIMED_OUT = "int  16"
EOJ_CURSOR_ALREADY_INITIALIZED = "int  17"
EOJ_INVALID_CURSOR = "int  18"
EOJ_CAN_ONLY_DESCRIBE_A_QUERY = "int  19"
EOJ_INVALID_ROW_PREFETCH = "int  20"
EOJ_MISSING_DEFINES = "int  21"
EOJ_MISSING_DEFINES_AT_INDEX = "int  22"
EOJ_UNSUPPORTED_FEATURE = "int  23"
EOJ_NO_DATA_READ = "int  24"
EOJ_IS_DEFINES_NULL_ERROR = "int  25"
EOJ_NUMERIC_OVERFLOW = "int  26"
EOJ_STREAM_CLOSED = "int  27"
EOJ_NO_NEW_DEFINE_IF_RESULT_SET_NOT_CLOSED = "int  28"
EOJ_READ_ONLY = "int  29"
EOJ_INVALID_TRANSLEVEL = "int  30"
EOJ_AUTO_CLOSE_ONLY = "int  31"
EOJ_ROW_PREFETCH_NOT_ZERO = "int  32"
EOJ_MALFORMED_SQL92 = "int  33"
EOJ_NON_SUPPORTED_SQL92_TOKEN = "int  34"
EOJ_NON_SUPPORTED_CHAR_SET = "int  35"
EOJ_ORACLE_NUMBER_EXCEPTION = "int  36"
EOJ_FAIL_CONVERSION_UTF8_TO_UCS2 = "int  37"
EOJ_CONVERSION_BYTE_ARRAY_ERROR = "int  38"
EOJ_CONVERSION_CHAR_ARRAY_ERROR = "int  39"
EOJ_SUB_SUB_PROTOCOL_ERROR = "int  40"
EOJ_INVALID_IN_OUT_BINDS = "int  41"
EOJ_INVALID_BATCH_VALUE = "int  42"
EOJ_INVALID_STREAM_SIZE = "int  43"
EOJ_DATASET_ITEMS_NOT_ALLOCATED = "int  44"
EOJ_BEYOND_BINDS_BATCH = "int  45"
EOJ_INVALID_RANK = "int  46"
EOJ_TDS_FORMAT_ERROR = "int  47"
EOJ_UNDEFINED_TYPE = "int  48"
EOJ_INCONSISTENT_ADT = "int  49"
EOJ_NOSUCHELEMENT = "int  50"
EOJ_NOT_AN_OBJECT_TYPE = "int  51"
EOJ_INVALID_REF = "int  52"
EOJ_INVALID_SIZE = "int  53"
EOJ_INVALID_LOB_LOCATOR = "int  54"
EOJ_FAIL_CONVERSION_CHARACTER = "int  55"
EOJ_UNSUPPORTED_CHARSET = "int  56"
EOJ_CLOSED_LOB = "int  57"
EOJ_INVALID_NLS_RATIO = "int  58"
EOJ_CONVERSION_JAVA_ERROR = "int  59"
EOJ_FAIL_CREATE_DESC = "int  60"
EOJ_NO_DESCRIPTOR = "int  61"
EOJ_INVALID_REF_CURSOR = "int  62"
EOJ_NOT_IN_A_TRANSACTION = "int  63"
EOJ_DATABASE_IS_NULL = "int  64"
EOJ_CONV_WAS_NULL = "int  65"
EOJ_ACCESS_SPECIFIC_IMPL = "int  66"
EOJ_INVALID_URL = "int  67"
EOJ_INVALID_ARGUMENTS = "int  68"
EOJ_USE_XA_EXPLICIT = "int  69"
EOJ_INVALID_DATASIZE_LENGTH = "int  70"
EOJ_EXCEEDED_VARRAY_LENGTH = "int  71"
EOJ_VALUE_TOO_BIG = "int  72"
EOJ_INVALID_NAME_PATTERN = "int  74"
EOJ_INVALID_FORWARD_RSET_OP = "int  75"
EOJ_INVALID_READONLY_RSET_OP = "int  76"
EOJ_FAIL_REF_SETVALUE = "int  77"
EOJ_CONNECTIONS_ALREADY_EXIST = "int  78"
EOJ_USER_CREDENTIALS_FAIL = "int  79"
EOJ_INVALID_BATCH_COMMAND = "int  80"
EOJ_BATCH_ERROR = "int  81"
EOJ_NO_CURRENT_ROW = "int  82"
EOJ_NOT_ON_INSERT_ROW = "int  83"
EOJ_ON_INSERT_ROW = "int  84"
EOJ_UPDATE_CONFLICTS = "int  85"
EOJ_NULL_INSERT_ROW_VALUE = "int  86"
WARN_IGNORE_FETCH_DIRECTION = "int  87"
EOJ_UNSUPPORTED_SYNTAX = "int  88"
EOJ_INTERNAL_ERROR = "int  89"
EOJ_OPER_NOT_ALLOWED = "int  90"
WARN_ALTERNATE_RSET_TYPE = "int  91"
EOJ_NO_JDBC_AT_END_OF_CALL = "int  92"
EOJ_WARN_SUCCESS_WITH_INFO = "int  93"
EOJ_VERSION_MISMATCH = "int  94"
EOJ_NO_STMT_CACHE_SIZE = "int  95"
EOJ_INVALID_ELEMENT_TYPE = "int  97"
EOJ_INVALID_EMPTYLOB_OP = "int  98"
EOJ_INVALID_INDEXTABLE_ARRAY_LENGTH = "int  99"
EOJ_INVALID_JAVA_OBJECT = "int  100"
EOJ_CONNECTIONPOOL_INVALID_PROPERTIES = "int  101"
EOJ_BFILE_IS_READONLY = "int  102"
EOJ_WRONG_CONNECTION_TYPE_FOR_METHOD = "int  103"
EOJ_NULL_SQL_STRING = "int  104"
EOJ_SESSION_TZ_NOT_SET = "int  105"
EOJ_CONNECTIONPOOL_INVALID_CONFIG = "int  106"
EOJ_CONNECTIONPOOL_INVALID_PROXY_TYPE = "int  107"
WARN_DEFINE_COLUMN_TYPE = "int  108"
EOJ_STANDARD_ENCODING_NOT_FOUND = "int  109"
EOJ_THIN_WARNING = "int  110"
EOJ_WARN_CONN_CACHE_TIMEOUT = "int  111"
EOJ_WARN_THREAD_TIMEOUT_INTERVAL = "int  112"
EOJ_WARN_THREAD_INTERVAL_TOO_BIG = "int  113"
EOJ_LOCAL_COMMIT_IN_GLOBAL_TXN = "int  114"
EOJ_LOCAL_ROLLBACK_IN_GLOBAL_TXN = "int  115"
EOJ_AUTOCOMMIT_IN_GLOBAL_TXN = "int  116"
EOJ_SETSVPT_IN_GLOBAL_TXN = "int  117"
EOJ_GETID_FOR_NAMED_SVPT = "int  118"
EOJ_GETNAME_FOR_UNNAMED_SVPT = "int  119"
EOJ_SETSVPT_WITH_AUTOCOMMIT = "int  120"
EOJ_ROLLBACK_WITH_AUTOCOMMIT = "int  121"
EOJ_ROLLBACK_TO_SVPT_IN_GLOBAL_TXN = "int  122"
EOJ_INVALID_STMT_CACHE_SIZE = "int  123"
EOJ_WARN_CACHE_INACTIVITY_TIMEOUT = "int  124"
EOJ_IMPROPER_STATEMENT_TYPE = "int  125"
EOJ_FIXED_WAIT_TIMEOUT = "int  126"
EOJ_WARN_CACHE_FIXEDWAIT_TIMEOUT = "int  127"
EOJ_INVALID_QUERY_STRING = "int  128"
EOJ_INVALID_DML_STRING = "int  129"
EOJ_QUERY_TIMEOUT_CLASS_NOT_FOUND = "int  130"
EOJ_QUERY_TIMEOUT_INVALID_STATE = "int  131"
EOJ_INVALID_OBJECT_TO_CONVERT = "int  132"
EOJ_INVALID_IDENTIFIER_OR_LITERAL = "int  133"
EOJ_PARAMETER_NAME_TOO_LONG = "int  134"
EOJ_PARAMETER_NAME_APPEARS_MORE_THAN_ONCE = "int  135"
EOJ_MALFORMED_DLNK_URL = "int  136"
EOJ_INVALID_CACHE_ENABLED_DATASOURCE = "int  137"
EOJ_INVALID_CONNECTION_CACHE_NAME = "int  138"
EOJ_INVALID_CONNECTION_CACHE_PROPERTIES = "int  139"
EOJ_CONNECTION_CACHE_ALREADY_EXISTS = "int  140"
EOJ_CONNECTION_CACHE_DOESNOT_EXIST = "int  141"
EOJ_CONNECTION_CACHE_DISABLED = "int  142"
EOJ_INVALID_CACHED_CONNECTION = "int  143"
EOJ_STMT_NOT_EXECUTED = "int  144"
EOJ_INVALID_ONS_EVENT = "int  145"
EOJ_INVALID_ONS_EVENT_VERSION = "int  146"
EOJ_UNKNOWN_PARAMETER_NAME = "int  147"
EOJ_T4C_ONLY = "int  148"
EOJ_ALREADY_PROXY = "int  149"
EOJ_PROXY_WRONG_ARG = "int  150"
EOJ_CLOB_TOO_LARGE = "int  151"
EOJ_METHOD_FOR_LOGICAL_CONNECTION_ONLY = "int  152"
EOJ_METHOD_FOR_PHYSICAL_CONNECTION_ONLY = "int  153"
EOJ_EX_MAP_ORACLE_TO_UCS = "int  154"
EOJ_EX_MAP_UCS_TO_ORACLE = "int  155"
EOJ_E2E_METRIC_ARRAY_SIZE = "int  156"
EOJ_SETSTRING_LIMIT = "int  157"
EOJ_INVALID_DURATION = "int  158"
EOJ_E2E_METRIC_TOO_LONG = "int  159"
EOJ_E2E_SEQUENCE_NUMBER_OUT_OF_RANGE = "int  160"
EOJ_INVALID_TXN_MODE = "int  161"
EOJ_UNSUPPORTED_HOLDABILITY = "int  162"
EOJ_GETXACONN_WHEN_CACHE_ENABLED = "int  163"
EOJ_GETXARESOURCE_FROM_PHYSICAL_CONN = "int  164"
EOJ_PRIVATE_JDBC_NOT_PRESENT = "int  165"
EOJ_NO_FETCH_ON_PLSQL = "int  166"
EOJ_ORACLEPKI_JAR_NOT_FOUND = "int  167"
EOJ_PKI_WALLET_ERROR = "int  168"
EOJ_NO_STREAM_BIND_ALLOWED = "int  169"
EOJ_APP_CTXT_NULL_NAMESPACE = "int  170"
EOJ_APP_CTXT_ATTR_TOO_LONG = "int  171"
EOJ_APP_CTXT_VAL_TOO_LONG = "int  172"
EOJ_DML_RETURNING_PARAM_NOT_REGISTERED = "int  173"
EOJ_APP_CTXT_INVALID_NAMESPACE = "int  174"
EOJ_REMOTE_ONS_CONFIG_ERROR = "int  175"
EOJ_UNKNOWN_LOCALE = "int  176"
EOJ_DOES_NOT_WRAP_INTERFACE = "int  177"
EOJ_ANYTYPE_PICKLER = "int  178"
EOJ_KOTAD_MAGIC_NUMBER_ERROR = "int  179"
EOJ_KOTAD_FORMAT_ERROR = "int  180"
EOJ_CHARACTER_CONVERTER_GENERAL_ERROR = "int  181"
EOJ_CHARACTER_CONVERTER_OVERRUN_ERROR = "int  182"
EOJ_CHARACTER_CONVERTER_IMPOSSIBLE_ERROR = "int  183"
EOJ_INCORRECT_FORM_OF_USE = "int  184"
EOJ_CONNECTION_PROPERTIES_DEFAULT_MISSING = "int  185"
EOJ_CONNECTION_PROPERTIES_ACCESSMODE_MISSING = "int  186"
EOJ_CONNECTION_PROPERTIES_INVALID_TYPE = "int  187"
EOJ_CONNECTION_PROPERTIES_REFLECTION_ILLEGAL_ACCESS = "int  188"
EOJ_CONNECTION_PROPERTIES_MISSING_INSTANCE_VARIABLE = "int  189"
EOJ_CONNECTION_PROPERTIES_FORMAT_ERROR = "int  190"
EOJ_INVALID_COMMIT_OPTIONS = "int  191"
EOJ_FREED_LOB = "int  192"
EOJ_INVALID_AQ_MESSAGE_FORMAT = "int  193"
EOJ_MARK_RESET_NOT_SUPPORTED = "int  194"
EOJ_INVALID_MARK = "int  195"
EOJ_READAHEAD_LIMIT_EXCEEDED = "int  196"
EOJ_INCORRECT_PARAMETER_USAGE = "int  197"
EOJ_SESSION_TIME_ZONE_NOT_SET = "int  198"
EOJ_SESSION_TIME_ZONE_NOT_SUPPORTED = "int  199"
EOJ_HETEROXA_GET_UTF_OPENSTR = "int  200"
EOJ_HETEROXA_GET_UTF_CLOSESTR = "int  201"
EOJ_HETEROXA_GET_UTF_RMNAME = "int  202"
EOJ_HETEROXA_JHANDLE_SIZE = "int  203"
EOJ_HETEROXA_ARRAY_TOO_SHORT = "int  204"
EOJ_HETEROXA_SVCCTX_HANDLE = "int  205"
EOJ_HETEROXA_ENV_HANDLE = "int  206"
EOJ_HETEROXA_NULL_TNSENTRY = "int  207"
EOJ_HETEROXA_OPEN_RMERR = "int  213"
EOJ_HETEROXA_OPEN_INVAL = "int  215"
EOJ_HETEROXA_OPEN_PROTO = "int  216"
EOJ_HETEROXA_CLOSE_RMERR = "int  233"
EOJ_HETEROXA_CLOSE_INVAL = "int  235"
EOJ_HETEROXA_CLOSE_PROTO = "int  236"
EOJ_NTF_UNKNOWN_LOCALHOST = "int  240"
EOJ_NTF_SECURITY_MANAGER = "int  241"
EOJ_NTF_TCP_OPTION = "int  242"
EOJ_NTF_TIMEOUT_OPTION = "int  243"
EOJ_DCN_CHANGELAG_OPTION = "int  244"
EOJ_NTF_DELETE_REG_WRONG_INSTANCE = "int  245"
EOJ_NTF_NULL_LISTENER = "int  246"
EOJ_NTF_PLSQL_LISTENER = "int  247"
EOJ_NTF_DUP_LISTENER = "int  248"
EOJ_NTF_RM_MISSING_LISTENER = "int  249"
EOJ_NTF_TCPPORT_ALREADY_USED = "int  250"
EOJ_NTF_CLOSED_REGISTRATION = "int  251"
EOJ_AQ_UNDEFINED_PAYLOAD_TYPE = "int  252"
EOJ_INVALID_NAME_FOR_CLIENTINFO = "int  253"
EOJ_OUT_OF_MEMORY_ERROR = "int  254"
EOJ_CANNOT_DISABLE_FCF = "int  255"
EOJ_INSTANCE_PROP_NOT_AVAILABLE = "int  256"
EOJ_INVALID_DRIVER_NAME_ATTR = "int  257"
EOJ_SYNONYM_LOOP_DETECTED = "int  258"
EOJ_MISSING_JAR_FOR_XML = "int  259"
EOJ_READ_EMPTY_SQLXML = "int  260"
EOJ_NOT_READABLE_SQLXML = "int  261"
EOJ_NOT_WRITEABLE_SQLXML = "int  262"
EOJ_UNSUPPORTED_SQLXML_RESULT_TYPE = "int  263"
EOJ_UNSUPPORTED_SQLXML_SOURCE_TYPE = "int  264"
EOJ_INVALID_TIMEZONE_NAME = "int  265"
EOJ_USER_STREAM_BIND_EXCEPTION = "int  266"
EOJ_INVALID_LOB_PREFETCH_SIZE = "int  267"
EOJ_INVALID_DATE_YEAR = "int  268"
EOJ_OCI_FATAL_ERROR = "int  269"
EOJ_DUPLICATE_STREAM_PARAMETER = "int  270"
EOJ_SETPLSQLINDEXTABLE_NULL_ARRAY = "int  271"
EOJ_SETPLSQLINDEXTABLE_ZERO_ARRAY = "int  272"
EOJ_CALLCOMMIT_WITH_AUTOCOMMIT = "int  273"
EOJ_CALLROLLBACK_WITH_AUTOCOMMIT = "int  274"
EOJ_RESULTSET_MAXROWS_LIMIT_REACHED = "int  275"
EOJ_ATTEMPT_TO_USE_RESERVED_NAMESPACE = "int  276"
EOJ_CANNOT_OPEN_TRANSLATION_FILE = "int  277"
EOJ_TRANSLATION_FILE_PARSING_ERROR = "int  278"
EOJ_TRANSLATE_QUERY_IN_LOCAL_MODE = "int  279"
EOJ_SERVER_TRANSLATION_ERROR = "int  280"
EOJ_NULL_FACTORY = "int  281"
EOJ_NULL_CLASS = "int  282"
EOJ_NO_RESULTSET = "int  283"
EOJ_NULL_EXECUTOR = "int  284"
EOJ_NEGATIVE_TIMEOUT = "int  285"
EOJ_RECURSIVE_EXECUTION = "int  286"
EOJ_NTF_REGISTRATION_FAILED = "int  287"
EOJ_SERVER_QUERY_TRANSLATION_NULL = "int  288"
EOJ_RESULTSET_AFTER_LAST_ROW = "int  289"
EOJ_BIND_CHECKSUM_MISMATCH = "int  290"
EOJ_FREED_ARRAY = "int  291"
EOJ_NO_VALID_LOGON_METHOD = "int  292"
EOJ_INVALID_VALUE_ALLOWEDLOGONVERSION = "int  293"
EOJ_SCHEMA_CHANGED = "int  294"
EOJ_REQUIRE_SELECT = "int  295"
EOJ_NULL_URL = "int  296"
EOJ_INVALID_SESSION_PURITY = "int  297"
EOJ_DRCP_ATTACH_TIMEOUT = "int  298"
EOJ_PLSQL_BOOLEAN_SUPPORT_UNAVAILABLE_IN_SVR = "int  299"
EOJ_INVAILD_IDENTIFIER = "int  300"
EOJ_JRS_UNABLE_CONNECT_VIA_DS = "int  300"
EOJ_JRS_AUTH_PROPS_NOT_SET = "int  301"
EOJ_JRS_CONN_NOT_OPEN = "int  302"
EOJ_JRS_DEL_ROWS_INVISIBLE = "int  303"
EOJ_JRS_SYNC_PROVIDER = "int  304"
EOJ_JRS_RESULTSET_NOT_OPEN = "int  305"
EOJ_JRS_FETCH_DIR_FOR_SCROLL = "int  306"
EOJ_JRS_FETCH_REV_FOR_FWD_TYPE = "int  307"
EOJ_JRS_INVALID_FETCH_DIR = "int  308"
EOJ_JRS_ROWSET_NOT_WRITABLE = "int  309"
EOJ_JRS_INVALID_PARAM_INDEX = "int  310"
EOJ_JRS_CNVT_COL_TO_STREAM = "int  311"
EOJ_JRS_CANT_COVT_COL_TO_STRM = "int  312"
EOJ_JRS_CALL_NEXT_PREV_FIRST = "int  313"
EOJ_JRS_INVALID_OP_FWD_TYPE = "int  314"
EOJ_JRS_NO_ROWS_CHANGED = "int  315"
EOJ_JRS_MAP_IN_TOCOLLECTION = "int  316"
EOJ_JRS_ROW_NOT_INSERTED = "int  317"
EOJ_JRS_ROW_NOT_DELETED = "int  318"
EOJ_JRS_ROW_NOT_UPDATED = "int  319"
EOJ_JRS_NOT_ALL_COLS_SET = "int  320"
EOJ_JRS_CONV_READER_TO_STR = "int  321"
EOJ_JRS_STREAM_READ = "int  322"
EOJ_JRS_INVALID_PARAM_TYPE = "int  323"
EOJ_JRS_INVALID_NUM_KEY_COLS = "int  324"
EOJ_JRS_INVALID_PAGE_SIZE = "int  325"
EOJ_JRS_MARK_INS_ROW_ORIG = "int  326"
EOJ_JRS_INVALID_OP_BEFORE_INS = "int  327"
EOJ_JRS_INVALID_OP_ON_RESULTSET = "int  328"
EOJ_JRS_INVALID_OP_BEFORE_PAGING = "int  329"
EOJ_JRS_INVALID_ROW_NUM_PARAM = "int  330"
EOJ_JRS_NEGATIVE_START_POS = "int  331"
EOJ_JRS_NULL_RESULTSET_TO_POPULATE = "int  332"
EOJ_JRS_FEW_ROWS_START_POPULATE = "int  333"
EOJ_JRS_NO_MATCH_COL_INDEXES_SET = "int  334"
EOJ_JRS_NO_MATCH_COL_NAMES_SET = "int  335"
EOJ_JRS_INVALID_MATCH_COL_INDEX = "int  336"
EOJ_JRS_INVALID_MATCH_COL_NAME = "int  337"
EOJ_JRS_CANT_SET_MATCH_COL_INDEX = "int  338"
EOJ_JRS_CANT_SET_MATCH_COL_NAME = "int  339"
EOJ_JRS_COL_INDEX_NOT_BEEN_SET = "int  340"
EOJ_JRS_COL_NAME_NOT_BEEN_SET = "int  341"
EOJ_JRS_CANT_OBTAIN_CONNECTION = "int  342"
EOJ_JRS_TABLE_NAME_IN_SQL = "int  343"
EOJ_JRS_WRONG_ROWSET_SCROLL_TYPE = "int  344"
EOJ_JRS_OBJ_NOT_SATISFY_FILTER = "int  345"
EOJ_JRS_SERIAL_BLOB_CONSTRUCTOR = "int  346"
EOJ_JRS_SERIAL_CLOB_CONSTRUCTOR = "int  347"
EOJ_JRS_CANT_CREATE_OBJ_COPY = "int  348"
EOJ_JRS_ERROR_CREATE_OBJ_COPY = "int  349"
EOJ_JRS_EMPTY_ROWSET_PARAM = "int  350"
EOJ_JRS_PARAM_NOT_A_ROWSET = "int  351"
EOJ_JRS_UNSUPPORTED_JOIN_TYPE = "int  352"
EOJ_JRS_ROWSET_MATCH_COL_NUM_DIFF = "int  353"
EOJ_JRS_UNSUPPORTED_3RD_PARTY = "int  354"
EOJ_JRS_INVALID_XMLREADER = "int  355"
EOJ_JRS_INVALID_XMLWRITER = "int  356"
EOJ_JRS_NON_NULLABLE_PROPERTY = "int  357"
EOJ_JRS_NON_NULLABLE_METADATA = "int  358"
EOJ_JRS_INVALID_WEBROWSET_ARG = "int  359"
REPLAY_ERROR_SET_CONTAINER = "int  366"
NO_REPLAY_INSUFFICIENT_MEMORY = "int  367"
GETLTXID_CALLED_IN_REPLAY_INIT_CALLBACK = "int  368"
NO_REPLAY_RECONNECT_AC_CHANGED = "int  369"
EOJ_NO_REPLAY = "int  370"
NO_REPLAY_ACTIVE_TXN = "int  371"
NO_REPLAY_NONREPLAYABLE_CALL = "int  372"
NO_REPLAY_LAST_CALL_PLSQL = "int  373"
NO_REPLAY_TXN_MONITORING_FAILED = "int  374"
NO_REPLAY_BEGIN_REPLAY_FAILED = "int  375"
NO_REPLAY_END_REPLAY_FAILED = "int  376"
NO_REPLAY_INITIATION_TIMEOUT_EXCEEDED = "int  377"
NO_REPLAY_RETRIES_EXCEEDED = "int  378"
NO_REPLAY_INIT_CALLBACK_FAILURE = "int  379"
NO_REPLAY_ACTIVE_TXN_IN_INIT_CALLBACK = "int  380"
NO_REPLAY_AFTER_ENDREQUEST = "int  381"
NO_REPLAY_RECONNECT_RETRIES_EXCEEDED = "int  382"
NO_REPLAY_GET_REPLAY_CONTEXT_FAILED = "int  383"
NO_REPLAY_SERVER_CM_DISABLED = "int  384"
NO_REPLAY_PREPARE_REPLAY_FAILED = "int  385"
NO_REPLAY_EMBEDDED_COMMIT = "int  386"
EOJ_REPLAY_ERROR = "int  387"
REPLAY_ERROR_CHECKSUM_MISMATCH = "int  388"
REPLAY_ERROR_ERRCODES_MESG_MISMATCH = "int  389"
REPLAY_ERROR_ACTIVE_TXN = "int  390"
BEGIN_REQUEST_CALLED_DURING_REQUEST = "int  391"
BEGIN_REQUEST_CALLED_WITH_OPEN_TXN = "int  392"
END_REQUEST_CALLED_WITH_OPEN_TXN = "int  393"
SVR_TOO_OLD_TO_SUPPORT_REPLAY = "int  394"
REPLAY_SUPPORT_UNAVAILABLE_IN_SVR = "int  395"
SVR_FAILOVER_TYPE_NOT_TRANSACTION = "int  396"
NO_REPLAY_CONCRETE_CLASSES = "int  397"
NO_REPLAY_SVR_NOREPLAY_FORCE = "int  398"
NO_REPLAY_SVR_DIRECTIVE_MISMATCH = "int  399"
TTC_ERR_BASE = "int  400"
TTC0000 = "int  401"
TTC0001 = "int  402"
TTC0002 = "int  403"
TTC0003 = "int  404"
TTC0004 = "int  405"
TTC0005 = "int  406"
TTC0100 = "int  407"
TTC0101 = "int  408"
TTC0102 = "int  409"
TTC0103 = "int  410"
TTC0104 = "int  411"
TTC0105 = "int  412"
TTC0106 = "int  413"
TTC0107 = "int  414"
TTC0108 = "int  415"
TTC0109 = "int  416"
TTC0110 = "int  417"
TTC0111 = "int  418"
TTC0112 = "int  419"
TTC0113 = "int  420"
TTC0114 = "int  421"
TTC0115 = "int  422"
TTC0116 = "int  423"
TTC0117 = "int  424"
TTC0118 = "int  425"
TTC0119 = "int  426"
TTC0120 = "int  427"
TTC0200 = "int  428"
TTC0201 = "int  429"
TTC0202 = "int  430"
TTC0203 = "int  431"
TTC0204 = "int  432"
TTC0205 = "int  433"
TTC0206 = "int  434"
TTC0207 = "int  435"
TTC0208 = "int  436"
TTC0209 = "int  437"
TTC0210 = "int  438"
TTC0211 = "int  439"
TTC0212 = "int  440"
TTC0213 = "int  441"
TTC0214 = "int  442"
TTC0217 = "int  444"
TTC0218 = "int  445"
TTC0219 = "int  446"
TTC0220 = "int  447"
TTC0221 = "int  448"
TTC0222 = "int  449"
TTC0223 = "int  450"
TTC0224 = "int  451"
TTC0225 = "int  452"
TTC0226 = "int  453"
EOJ_CONFIG_FILE_READ = "int  1700"
EOJ_CONFIG_FILE_PARSE = "int  1701"
EOJ_MULTIPLE_CREDENTIALS_FOUND = "int  1702"
EOJ_RESULT_DESCRIPTION_CHANGED = "int  1703"
def newSQLException():
    '''    public static SQLException newSQLException(final OracleConnection oracleConnection, final String s, final int n)
    public static SQLException newSQLException(final OracleConnection oracleConnection, final String s, final int n, final Throwable cause)
    public static SQLException newSQLException(final OracleConnection oracleConnection, final int n)
    '''
def createSqlException():
    '''    public static SQLException createSqlException(final OracleConnection oracleConnection, final String s, final int n, final Throwable t)
    public static SQLException createSqlException(final OracleConnection oracleConnection, final String s, final int n)
    public static SQLException createSqlException(final int n, final Object o)
    public static SQLException createSqlException(final OracleConnection oracleConnection, final int n, final Object o, final Throwable t)
    public static SQLException createSqlException(final OracleConnection oracleConnection, final int n, final Object o)
    public static SQLException createSqlException(final OracleSQLException ex)
    public static SQLException createSqlException(final OracleConnection oracleConnection, final OracleSQLException cause)
    public static SQLException createSqlException(final OracleConnection oracleConnection, final SQLException nextException, final int n, final Object o)
    public static SQLException createSqlException(final int n)
    public static SQLException createSqlException(final OracleConnection oracleConnection, final int n)
    public static SQLException createSqlException(final IOException ex)
    public static SQLException createSqlException(final OracleConnection oracleConnection, final IOException ex)
    public static SQLException createSqlException(final Exception ex)
    public static SQLException createSqlException(final OracleConnection oracleConnection, final Exception ex)
    '''
def addSqlException():
    '''    public static void addSqlException(final SQLException ex, final String s, final int n)
    '''
def createBatchUpdateException():
    '''    public static BatchUpdateException createBatchUpdateException(final SQLException nextException, int n, final int[] array)
    public static BatchUpdateException createBatchUpdateException(final String reason, final String sqlState, final int vendorCode, int n, final int[] array)
    public static BatchUpdateException createBatchUpdateException(final int n, final Object o, final int n2, final int[] array)
    public static BatchUpdateException createBatchUpdateException(final int n, final int n2, final int[] array)
    public static BatchUpdateException createBatchUpdateException(final SQLException ex, final int n, final long[] array)
    public static BatchUpdateException createBatchUpdateException(final SQLException nextException, final String str, int n, final long[] array)
    public static BatchUpdateException createBatchUpdateException(final String reason, final String sqlState, final int vendorCode, int n, final long[] array)
    public static BatchUpdateException createBatchUpdateException(final int n, final Object o, final int n2, final long[] array)
    public static BatchUpdateException createBatchUpdateException(final int n, final int n2, final long[] array)
    '''
def createUnsupportedFeatureSqlException():
    '''    public static SQLFeatureNotSupportedException createUnsupportedFeatureSqlException()
    public static SQLFeatureNotSupportedException createUnsupportedFeatureSqlException(final String s)
    '''
def createSQLFeatureNotSupportedException():
    '''    public static SQLFeatureNotSupportedException createSQLFeatureNotSupportedException()
    public static SQLFeatureNotSupportedException createSQLFeatureNotSupportedException(final String s)
    '''
def createSQLClientInfoException():
    '''    public static SQLClientInfoException createSQLClientInfoException(final int n, final Map<String, ClientInfoStatus> failedProperties, final Throwable cause)
    '''
def createIOException():
    '''    public static IOException createIOException(final SQLException cause)
    '''
def createXAException():
    '''    public static XAException createXAException(final int errcode)
    public static XAException createXAException(final String s, final int errorCode)
    '''
def newSqlWarning():
    '''    public static SQLWarning newSqlWarning(final String s, final int n)
    public static SQLWarning newSqlWarning(final int n, final Object o)
    public static SQLWarning newSqlWarning(final int n)
    '''
def addSqlWarning():
    '''    public static SQLWarning addSqlWarning(final SQLWarning sqlWarning, final String reason, final int vendorCode)
    public static SQLWarning addSqlWarning(final SQLWarning sqlWarning, final SQLWarning nextWarning)
    public static SQLWarning addSqlWarning(final SQLWarning sqlWarning, final int n, final Object o)
    public static SQLWarning addSqlWarning(final SQLWarning sqlWarning, final int n)
    '''
def ErrorToSQLState():
    '''    public static String ErrorToSQLState(final int n)
    '''
def getVendorCode():
    '''    public static int getVendorCode(final int n)
    '''
def test():
    '''    public static void test()
    '''
def printSqlException():
    '''    public static void printSqlException(final SQLException ex)
    '''
