langXML = "String  \"RDF/XML\""
langXMLAbbrev = "String  \"RDF/XML-ABBREV\""
langNTriple = "String  \"N-TRIPLE\""
langN3 = "String  \"N3\""
langTurtle = "String  \"TURTLE\""
langBDB = "String  \"RDF/BDB\""
langSQL = "String  \"RDF/SQL\""
encodingUTF8 = "String  \"utf-8\""
