SASL_MECHANISM = "String  \"sasl.mechanism\""
SASL_MECHANISM_DOC = "String  \"SASL mechanism used for client connections. This may be any mechanism for which a security provider is available. GSSAPI is the default mechanism.\""
GSSAPI_MECHANISM = "String  \"GSSAPI\""
DEFAULT_SASL_MECHANISM = "String  \"GSSAPI\""
SASL_ENABLED_MECHANISMS = "String  \"sasl.enabled.mechanisms\""
SASL_ENABLED_MECHANISMS_DOC = "String  \"The list of SASL mechanisms enabled in the Kafka server. The list may contain any mechanism for which a security provider is available. Only GSSAPI is enabled by default.\""
SASL_JAAS_CONFIG = "String  \"sasl.jaas.config\""
SASL_JAAS_CONFIG_DOC = "String  \"JAAS login context parameters for SASL connections in the format used by JAAS configuration files. JAAS configuration file format is described <a href=\\"http://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/tutorials/LoginConfigFile.html\\">here</a>. The format for the value is: '<loginModuleClass> <controlFlag> (<optionName>=<optionValue>)*;'\""
SASL_KERBEROS_SERVICE_NAME = "String  \"sasl.kerberos.service.name\""
SASL_KERBEROS_SERVICE_NAME_DOC = "String  \"The Kerberos principal name that Kafka runs as. This can be defined either in Kafka's JAAS config or in Kafka's config.\""
SASL_KERBEROS_KINIT_CMD = "String  \"sasl.kerberos.kinit.cmd\""
SASL_KERBEROS_KINIT_CMD_DOC = "String  \"Kerberos kinit command path.\""
DEFAULT_KERBEROS_KINIT_CMD = "String  \"/usr/bin/kinit\""
SASL_KERBEROS_TICKET_RENEW_WINDOW_FACTOR = "String  \"sasl.kerberos.ticket.renew.window.factor\""
SASL_KERBEROS_TICKET_RENEW_WINDOW_FACTOR_DOC = "String  \"Login thread will sleep until the specified window factor of time from last refresh to ticket's expiry has been reached, at which time it will try to renew the ticket.\""
DEFAULT_KERBEROS_TICKET_RENEW_WINDOW_FACTOR = "double  0.8"
SASL_KERBEROS_TICKET_RENEW_JITTER = "String  \"sasl.kerberos.ticket.renew.jitter\""
SASL_KERBEROS_TICKET_RENEW_JITTER_DOC = "String  \"Percentage of random jitter added to the renewal time.\""
DEFAULT_KERBEROS_TICKET_RENEW_JITTER = "double  0.05"
SASL_KERBEROS_MIN_TIME_BEFORE_RELOGIN = "String  \"sasl.kerberos.min.time.before.relogin\""
SASL_KERBEROS_MIN_TIME_BEFORE_RELOGIN_DOC = "String  \"Login thread sleep time between refresh attempts.\""
DEFAULT_KERBEROS_MIN_TIME_BEFORE_RELOGIN = "long  60000L"
SASL_KERBEROS_PRINCIPAL_TO_LOCAL_RULES = "String  \"sasl.kerberos.principal.to.local.rules\""
SASL_KERBEROS_PRINCIPAL_TO_LOCAL_RULES_DOC = "String  \"A list of rules for mapping from principal names to short names (typically operating system usernames). The rules are evaluated in order and the first rule that matches a principal name is used to map it to a short name. Any later rules in the list are ignored. By default, principal names of the form {username}/{hostname}@{REALM} are mapped to {username}. For more details on the format please see <a href=\\"#security_authz\\"> security authorization and acls</a>. Note that this configuration is ignored if an extension of KafkaPrincipalBuilder is provided by the <code>principal.builder.class</code> configuration.\""
