autoclass_lastrundate = "String mxe.tsd.autoclass.lastrundate""
autoclass_enable = "String mxe.tsd.autoclass.enable""
autoclass_minprobability = "String mxe.tsd.autoclass.minprobability""
autoclass_maxprobdisplay = "String mxe.tsd.autoclass.maxprobdisplay""
autoclass_returnparent = "String mxe.tsd.autoclass.returnparent""
