HTTP_CONNECTION = "String  \"http.connection\""
HTTP_REQUEST = "String  \"http.request\""
HTTP_RESPONSE = "String  \"http.response\""
HTTP_TARGET_HOST = "String  \"http.target_host\""
HTTP_PROXY_HOST = "String  \"http.proxy_host\""
HTTP_REQ_SENT = "String  \"http.request_sent\""
