CR = "int  13"
LF = "int  10"
SP = "int  32"
HT = "int  9"
TRANSFER_ENCODING = "String  \"Transfer-Encoding\""
CONTENT_LEN = "String  \"Content-Length\""
CONTENT_TYPE = "String  \"Content-Type\""
CONTENT_ENCODING = "String  \"Content-Encoding\""
EXPECT_DIRECTIVE = "String  \"Expect\""
CONN_DIRECTIVE = "String  \"Connection\""
TARGET_HOST = "String  \"Host\""
USER_AGENT = "String  \"User-Agent\""
DATE_HEADER = "String  \"Date\""
SERVER_HEADER = "String  \"Server\""
EXPECT_CONTINUE = "String  \"100-continue\""
CONN_CLOSE = "String  \"Close\""
CONN_KEEP_ALIVE = "String  \"Keep-Alive\""
CHUNK_CODING = "String  \"chunked\""
IDENTITY_CODING = "String  \"identity\""
UTF_8 = "String  \"UTF-8\""
UTF_16 = "String  \"UTF-16\""
US_ASCII = "String  \"US-ASCII\""
ASCII = "String  \"ASCII\""
ISO_8859_1 = "String  \"ISO-8859-1\""
DEFAULT_CONTENT_CHARSET = "String  \"ISO-8859-1\""
DEFAULT_PROTOCOL_CHARSET = "String  \"US-ASCII\""
OCTET_STREAM_TYPE = "String  \"application/octet-stream\""
PLAIN_TEXT_TYPE = "String  \"text/plain\""
CHARSET_PARAM = "String  \"; charset=\""
DEFAULT_CONTENT_TYPE = "String  \"application/octet-stream\""
def isWhitespace():
    '''    public static boolean isWhitespace(final char ch)
    '''
