_value1 = "String  \"account\""
_value2 = "String  \"adaptiveAnalyticsService\""
_value3 = "String  \"adminFolder\""
_value4 = "String  \"agentDefinition\""
_value5 = "String  \"agentDefinitionView\""
_value6 = "String  \"agentOutputHotList\""
_value7 = "String  \"agentService\""
_value8 = "String  \"agentState\""
_value9 = "String  \"agentTaskDefinition\""
_value10 = "String  \"agentTaskState\""
_value11 = "String  \"aliasRoot\""
_value12 = "String  \"analysis\""
_value13 = "String  \"annotation\""
_value14 = "String  \"annotationFolder\""
_value15 = "String  \"annotationService\""
_value16 = "String  \"archiveLocation\""
_value17 = "String  \"batchReportService\""
_value18 = "String  \"cacheOutput\""
_value19 = "String  \"capability\""
_value20 = "String  \"catalog\""
_value21 = "String  \"catalogFolder\""
_value22 = "String  \"configuration\""
_value23 = "String  \"configurationFolder\""
_value24 = "String  \"contact\""
_value25 = "String  \"content\""
_value26 = "String  \"contentManagerCacheService\""
_value27 = "String  \"contentManagerService\""
_value28 = "String  \"contentTask\""
_value29 = "String  \"credential\""
_value30 = "String  \"dashboard\""
_value31 = "String  \"dataAdvisorService\""
_value32 = "String  \"dataIntegrationService\""
_value33 = "String  \"dataMovementService\""
_value34 = "String  \"dataMovementTask\""
_value35 = "String  \"dataMovementTaskAlias\""
_value36 = "String  \"dataSource\""
_value37 = "String  \"dataSourceConnection\""
_value38 = "String  \"dataSourceCredential\""
_value39 = "String  \"dataSourceNameBinding\""
_value40 = "String  \"dataSourceSignon\""
_value41 = "String  \"deliveryService\""
_value42 = "String  \"deploymentDetail\""
_value43 = "String  \"dimensionManagementService\""
_value44 = "String  \"directory\""
_value45 = "String  \"dispatcher\""
_value46 = "String  \"distributionList\""
_value47 = "String  \"document\""
_value48 = "String  \"documentContent\""
_value49 = "String  \"documentVersion\""
_value50 = "String  \"drillPath\""
_value51 = "String  \"eventManagementService\""
_value52 = "String  \"EVService\""
_value53 = "String  \"exportDeployment\""
_value54 = "String  \"favoritesFolder\""
_value55 = "String  \"folder\""
_value56 = "String  \"graphic\""
_value57 = "String  \"graphicsService\""
_value58 = "String  \"group\""
_value59 = "String  \"history\""
_value60 = "String  \"historyDetail\""
_value61 = "String  \"historyDetailAgentService\""
_value62 = "String  \"historyDetailDataMovementService\""
_value63 = "String  \"historyDetailDeploymentSummary\""
_value64 = "String  \"historyDetailMigrationService\""
_value65 = "String  \"historyDetailRelatedHistory\""
_value66 = "String  \"historyDetailRelatedReports\""
_value67 = "String  \"historyDetailReportService\""
_value68 = "String  \"historyDetailRequestArguments\""
_value69 = "String  \"humanTask\""
_value70 = "String  \"humanTaskService\""
_value71 = "String  \"idVizService\""
_value72 = "String  \"importDeployment\""
_value73 = "String  \"indexDataService\""
_value74 = "String  \"indexSearchService\""
_value75 = "String  \"indexUpdateService\""
_value76 = "String  \"indexUpdateTask\""
_value77 = "String  \"installedComponent\""
_value78 = "String  \"interactiveReport\""
_value79 = "String  \"jobDefinition\""
_value80 = "String  \"jobService\""
_value81 = "String  \"jobStepDefinition\""
_value82 = "String  \"launchable\""
_value83 = "String  \"logService\""
_value84 = "String  \"memo\""
_value85 = "String  \"metadataService\""
_value86 = "String  \"metricsDataSourceETLTask\""
_value87 = "String  \"metricsExportTask\""
_value88 = "String  \"metricsFileImportTask\""
_value89 = "String  \"metricsMaintenanceTask\""
_value90 = "String  \"metricsManagerService\""
_value91 = "String  \"migrationService\""
_value92 = "String  \"migrationTask\""
_value93 = "String  \"mobileService\""
_value94 = "String  \"model\""
_value95 = "String  \"modelView\""
_value96 = "String  \"monitorService\""
_value97 = "String  \"mruFolder\""
_value98 = "String  \"namespace\""
_value99 = "String  \"namespaceFolder\""
_value100 = "String  \"nil\""
_value101 = "String  \"output\""
_value102 = "String  \"package\""
_value103 = "String  \"packageConfiguration\""
_value104 = "String  \"page\""
_value105 = "String  \"pageDefinition\""
_value106 = "String  \"pagelet\""
_value107 = "String  \"pageletFolder\""
_value108 = "String  \"pageletInstance\""
_value109 = "String  \"periodical\""
_value110 = "String  \"personalization\""
_value111 = "String  \"personalizationFolder\""
_value112 = "String  \"planningAdministrationConsoleService\""
_value113 = "String  \"planningApplication\""
_value114 = "String  \"planningDataService\""
_value115 = "String  \"planningMacroTask\""
_value116 = "String  \"planningRuntimeService\""
_value117 = "String  \"planningTask\""
_value118 = "String  \"planningTaskService\""
_value119 = "String  \"portal\""
_value120 = "String  \"portalPackage\""
_value121 = "String  \"portalSkin\""
_value122 = "String  \"portalSkinFolder\""
_value123 = "String  \"portlet\""
_value124 = "String  \"portletFolder\""
_value125 = "String  \"portletInstance\""
_value126 = "String  \"portletProducer\""
_value127 = "String  \"powerPlay8Report\""
_value128 = "String  \"powerPlay8ReportView\""
_value129 = "String  \"powerPlayCube\""
_value130 = "String  \"powerPlayReport\""
_value131 = "String  \"powerPlayService\""
_value132 = "String  \"presentationService\""
_value133 = "String  \"printer\""
_value134 = "String  \"query\""
_value135 = "String  \"queryService\""
_value136 = "String  \"queryServiceTask\""
_value137 = "String  \"relationalMetadataService\""
_value138 = "String  \"report\""
_value139 = "String  \"reportCache\""
_value140 = "String  \"reportDataService\""
_value141 = "String  \"reportDataServiceAgentDefinition\""
_value142 = "String  \"reportService\""
_value143 = "String  \"reportTemplate\""
_value144 = "String  \"reportVersion\""
_value145 = "String  \"reportView\""
_value146 = "String  \"repositoryService\""
_value147 = "String  \"resource\""
_value148 = "String  \"rolapDataSource\""
_value149 = "String  \"rolapVirtualDataSource\""
_value150 = "String  \"role\""
_value151 = "String  \"root\""
_value152 = "String  \"runTimeState\""
_value153 = "String  \"saCAMService\""
_value154 = "String  \"schedule\""
_value155 = "String  \"securedFeature\""
_value156 = "String  \"securedFunction\""
_value157 = "String  \"session\""
_value158 = "String  \"shortcut\""
_value159 = "String  \"shortcutAgentRSSTask\""
_value160 = "String  \"shortcutRSSTask\""
_value161 = "String  \"SQL\""
_value162 = "String  \"storedProcedureTask\""
_value163 = "String  \"subscriptionFolder\""
_value164 = "String  \"systemMetricThresholds\""
_value165 = "String  \"systemService\""
_value166 = "String  \"tenant\""
_value167 = "String  \"tenants\""
_value168 = "String  \"transientStateFolder\""
_value169 = "String  \"uiProfile\""
_value170 = "String  \"uiProfileFolder\""
_value171 = "String  \"URL\""
_value172 = "String  \"urlRSSTask\""
_value173 = "String  \"visualization\""
_value174 = "String  \"webServiceTask\""
def getValue():
    '''returns String\n\n
    getValue()\n
    '''
def equals():
    '''returns boolean\n\n
    equals(final Object obj)\n
    '''
def hashCode():
    '''returns int\n\n
    hashCode()\n
    '''
def toString():
    '''returns String\n\n
    toString()\n
    '''
def readResolve():
    '''returns Object\n\n
    readResolve()\n
    '''
