GREGORIAN = "String  \"gregorian\""
ISLAMIC = "String  \"islamic\""
HEBREW = "String  \"hebrew\""
DOJO_ISLAMIC = "String  \"dojox.date.islamic\""
DOJO_HEBREW = "String  \"dojox.date.hebrew\""
ICU_GREGORIAN = "String  \"gregorian\""
ICU_ISLAMIC = "String  \"islamic-civil\""
ICU_HEBREW = "String  \"hebrew\""
