CALCAPPLYTO = "String  CALCAPPLYTO""
CALCLEVEL = "String  CALCLEVEL""
CALCMETHOD = "String  CALCMETHOD""
CALCEXPRESSION = "String  CALCEXPRESSION""
CALCEXPRESSIONHOURS = "String  CALCEXPRESSIONHOURS""
UNITSOFWORKMULTIPLIER = "String  UNITSOFWORKMULTIPLIER""
DYNAMIC = "String  DYNAMIC""
APPLYNONDYNAMICCALC = "String  APPLYNONDYNAMICCALC""
UNITSOFWORK = "String  UNITSOFWORK""
TOTALWORKUNITS = "String  TOTALWORKUNITS""
JOBTASKID = "String  JOBTASKID""
JOBITEMID = "String  JOBITEMID""
JOBLABORID = "String  JOBLABORID""
attributesToCopyForTask = "String[]  { "JOBTASKID" }"
attributesToCopyForLabor = "String[]  { "JOBLABORID" }"
attributesToCopyForItem = "String[]  { "JOBITEMID" }"
CALCMETHOD_STATIC = "String  STATIC""
CALCMETHOD_PROPORTIONAL = "String  PROPORTIONAL""
CALCMETHOD_LEVEL = "String  LEVEL""
CALCMETHOD_PROPORTIONAL_ATTRIBUTE = "String  ATTR_PROP""
CALCMETHOD_LEVEL_ATTRIBUTE = "String  ATTR_LVL""
def toString():
'''public String toString()
'''
pass
def fromStringTo():
'''public static CalcApplyTo fromStringTo(final String val)
'''
pass
