INDEX_SIZE_ERR = "short  1"
DOMSTRING_SIZE_ERR = "short  2"
HIERARCHY_REQUEST_ERR = "short  3"
WRONG_DOCUMENT_ERR = "short  4"
INVALID_CHARACTER_ERR = "short  5"
NO_DATA_ALLOWED_ERR = "short  6"
NO_MODIFICATION_ALLOWED_ERR = "short  7"
NOT_FOUND_ERR = "short  8"
NOT_SUPPORTED_ERR = "short  9"
INUSE_ATTRIBUTE_ERR = "short  10"
INVALID_STATE_ERR = "short  11"
SYNTAX_ERR = "short  12"
INVALID_MODIFICATION_ERR = "short  13"
NAMESPACE_ERR = "short  14"
INVALID_ACCESS_ERR = "short  15"
VALIDATION_ERR = "short  16"
TYPE_MISMATCH_ERR = "short  17"
def DOMException():
    '''public DOMException(final short code, final String message)
    '''
