CONTENT_TYPE = "String  Content-Type""
CONTENT_TRANSFER_ENC = "String  Content-Transfer-Encoding""
CONTENT_DISPOSITION = "String  Content-Disposition""
ENC_8BIT = "String  8bit""
ENC_BINARY = "String  binary""
