OSLC4J_PUBLIC_URI = "String  org.eclipse.lyo.oslc4j.publicURI""
OSLC4J_DISABLE_HOST_RESOLUTION = "String  org.eclipse.lyo.oslc4j.disableHostResolution""
OSLC4J_SELECTED_PROPERTIES = "String  org.eclipse.lyo.oslc4j.selected.properties""
OSLC4J_NEXT_PAGE = "String  org.eclipse.lyo.oslc4j.next.page""
OSLC4J_TOTAL_COUNT = "String  org.eclipse.lyo.oslc4j.total.count""
