Select = "String  \"SELECT\""
Insert = "String  \"INSERT\""
Update = "String  \"UPDATE\""
Delete = "String  \"DELETE\""
Merge = "String  \"MERGE\""
Call = "String  \"CALL\""
Other = "String  \"OTHER\""
