META_SETBKCOLOR = "int  513"
META_SETBKMODE = "int  258"
META_SETMAPMODE = "int  259"
META_SETROP2 = "int  260"
META_SETRELABS = "int  261"
META_SETPOLYFILLMODE = "int  262"
META_SETSTRETCHBLTMODE = "int  263"
META_SETTEXTCHAREXTRA = "int  264"
META_SETTEXTCOLOR = "int  521"
META_SETTEXTJUSTIFICATION = "int  522"
META_SETWINDOWORG = "int  523"
META_SETWINDOWEXT = "int  524"
META_SETVIEWPORTORG = "int  525"
META_SETVIEWPORTEXT = "int  526"
META_OFFSETWINDOWORG = "int  527"
META_SCALEWINDOWEXT = "int  1040"
META_OFFSETVIEWPORTORG = "int  529"
META_SCALEVIEWPORTEXT = "int  1042"
META_LINETO = "int  531"
META_MOVETO = "int  532"
META_EXCLUDECLIPRECT = "int  1045"
META_INTERSECTCLIPRECT = "int  1046"
META_ARC = "int  2071"
META_ELLIPSE = "int  1048"
META_FLOODFILL = "int  1049"
META_PIE = "int  2074"
META_RECTANGLE = "int  1051"
META_ROUNDRECT = "int  1564"
META_PATBLT = "int  1565"
META_SAVEDC = "int  30"
META_SETPIXEL = "int  1055"
META_OFFSETCLIPRGN = "int  544"
META_TEXTOUT = "int  1313"
META_BITBLT = "int  2338"
META_STRETCHBLT = "int  2851"
META_POLYGON = "int  804"
META_POLYLINE = "int  805"
META_ESCAPE = "int  1574"
META_RESTOREDC = "int  295"
META_FILLREGION = "int  552"
META_FRAMEREGION = "int  1065"
META_INVERTREGION = "int  298"
META_PAINTREGION = "int  299"
META_SELECTCLIPREGION = "int  300"
META_SELECTOBJECT = "int  301"
META_SETTEXTALIGN = "int  302"
META_CHORD = "int  2096"
META_SETMAPPERFLAGS = "int  561"
META_EXTTEXTOUT = "int  2610"
META_SETDIBTODEV = "int  3379"
META_SELECTPALETTE = "int  564"
META_REALIZEPALETTE = "int  53"
META_ANIMATEPALETTE = "int  1078"
META_SETPALENTRIES = "int  55"
META_POLYPOLYGON = "int  1336"
META_RESIZEPALETTE = "int  313"
META_DIBBITBLT = "int  2368"
META_DIBSTRETCHBLT = "int  2881"
META_DIBCREATEPATTERNBRUSH = "int  322"
META_STRETCHDIB = "int  3907"
META_EXTFLOODFILL = "int  1352"
META_DELETEOBJECT = "int  496"
META_CREATEPALETTE = "int  247"
META_CREATEPATTERNBRUSH = "int  505"
META_CREATEPENINDIRECT = "int  762"
META_CREATEFONTINDIRECT = "int  763"
META_CREATEBRUSHINDIRECT = "int  764"
META_CREATEREGION = "int  1791"
def ():
    '''returns MetaDo\n\n
    (final InputStream in, final PdfContentByte cb)\n
    '''
def readAll():
    '''returns None\n\n
    readAll()\n
    '''
def outputText():
    '''returns None\n\n
    outputText(final int x, final int y, final int flag, final int x1, final int y1, final int x2, final int y2, final String text)\n
    '''
def isNullStrokeFill():
    '''returns boolean\n\n
    isNullStrokeFill(final boolean isRectangle)\n
    '''
def strokeAndFill():
    '''returns None\n\n
    strokeAndFill()\n
    '''
