defaultPollingInterval__ = "int  120"
defaultStatisticsCollectionInterval__ = "int  900"
defaultMaxClientInfoToLogPerDataSource__ = "int  1000"
defaultConnectTimeout__ = "int  20"
defaultReadTimeout__ = "int  50"
defaultCachingIntervalForMonitoredData__ = "int  300"
defaultInMemoryCacheLimitForMonitoredData__ = "long  500000000L"
