TITLE_PROPERTY = "String  \"Title\""
MODIFIED_PROPERTY = "String  \"Modified\""
DOCUMENT_TEMPLATE_PROPERTY = "String  \"DocumentTemplate\""
APPLICATION_PROPERTY = "String  \"Application\""
EDITABLE_PROPERTY = "String  \"Editable\""
SAVEABLE_PROPERTY = "String  \"Saveable\""
ATTACHED_DOCUMENTS_PROPERTY = "String  \"AttachedDocuments\""
DOCUMENT_OWNER_PROPERTY = "String  \"DocumentOwner\""
