TITLE_PROPERTY = "String  \"Title\""
OWN_TITLE_PROPERTY = "String  \"OwnTitle\""
CLOSE_ALL_WINDOWS_CMD = "String  \"CloseAllWindows\""
CLOSE_WINDOW_CMD = "String  \"CloseWindow\""
PREVIOUS_WINDOW_CMD = "String  \"PreviousWindow\""
NEXT_WINDOW_CMD = "String  \"NextWindow\""
