DOCUMENT_TEMPLATE_PROPERTY = "String  \"DocumentTemplate\""
APPLICATION_PROPERTY = "String  \"Application\""
DOCUMENT_PROPERTY = "String  \"Document\""
CONFIGURATION_NAME_PROPERTY = "String  \"ConfigurationName\""
DOCUMENT_VIEWS_PROPERTY = "String  \"Views\""
ACTIVE_VIEW_PROPERTY = "String  \"ActiveView\""
CONTAINER_TEMPLATE_PROPERTY = "String  \"ContainerTemplate\""
VISIBILITY_PROPERTY = "String  \"ContainerVisibility\""
