version = "int  8"
minorVersion = "int  8"
subMinorVersion = "int  0"
patchLevel = "int  0"
buildNumber = "int  3753"
releaseDate = "int  20110929"
jlmManaged = "boolean  false"
fullInstaller = "boolean  true"
