SEND_TYPE_NOTSET = "int  1"
SEND_TYPE_MIME = "int  2"
SEND_TYPE_DIME = "int  3"
SEND_TYPE_MTOM = "int  4"
SEND_TYPE_NONE = "int  5"
SEND_TYPE_MAX = "int  5"
SEND_TYPE_DEFAULT = "int  2"
CIDprefix = "String  cid:""
